version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "gomod"
    directory: "/control-plane"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ui"
