import type { DomainItem } from './types';

export const INITIAL_DOMAINS: DomainItem[] = [
  {
    id: 'dom-1',
    domain: 'api.example.com',
    rootDomain: 'example.com',
    status: 'Active',
    tlsType: "Let's Encrypt",
    tlsExpiry: '2025-11-24',
    tlsAutoRenew: true,
    minTlsVersion: 'TLSv1.3',
    hstsEnabled: true,
    ocspStapling: true,
    upstream: 'http://10.0.1.10:8080',
    upstreamAlgorithm: 'round_robin',
    healthCheckPath: '/healthz',
    upstreamServers: [
      { url: 'http://10.0.1.10:8080', weight: 1, maxFails: 3, failTimeout: '10s', healthy: true },
      { url: 'http://10.0.1.11:8080', weight: 1, maxFails: 3, failTimeout: '10s', healthy: true },
    ],
    rulesCount: 6,
    policiesCount: 2,
    ipRulesCount: 1,
    rateLimitsCount: 3,
    tags: ['api', 'prod'],
    createdAt: '2025-08-20 10:14',
    updatedAt: '2025-08-26 10:14',
    createdBy: 'admin',
    description: 'Main API domain for public services.',
    nodeBindings: [
      { nodeId: 'node-sg-01', nodeName: 'SG Edge Controller 01', ip: '10.0.1.1', ports: [80, 443], status: 'Synced', lastSynced: '2025-08-26 10:14' },
      { nodeId: 'node-sg-02', nodeName: 'SG Edge Controller 02', ip: '10.0.1.2', ports: [80, 443], status: 'Synced', lastSynced: '2025-08-26 10:14' },
      { nodeId: 'node-us-01', nodeName: 'US East Edge 01', ip: '10.0.2.1', ports: [80, 443], status: 'Synced', lastSynced: '2025-08-26 10:13' },
    ],
    recentActivities: [
      {
        id: 'act-1',
        type: 'updated',
        title: 'Domain updated',
        description: 'Updated TLS certificate',
        timestamp: '2025-08-26 10:14',
        color: 'emerald',
      },
      {
        id: 'act-2',
        type: 'rule',
        title: 'Rule attached',
        description: 'SQL Injection Protection',
        timestamp: '2025-08-25 16:20',
        color: 'blue',
      },
      {
        id: 'act-3',
        type: 'created',
        title: 'Domain created',
        description: 'By admin',
        timestamp: '2025-08-20 10:14',
        color: 'slate',
      },
    ],
  },
  {
    id: 'dom-2',
    domain: 'admin.example.com',
    rootDomain: 'example.com',
    status: 'Active',
    tlsType: 'Custom Cert',
    tlsExpiry: '2026-03-15',
    tlsAutoRenew: false,
    minTlsVersion: 'TLSv1.3',
    hstsEnabled: true,
    ocspStapling: true,
    upstream: 'http://10.0.1.20:8080',
    upstreamAlgorithm: 'ip_hash',
    healthCheckPath: '/api/health',
    upstreamServers: [
      { url: 'http://10.0.1.20:8080', weight: 2, maxFails: 2, failTimeout: '5s', healthy: true },
    ],
    rulesCount: 4,
    policiesCount: 3,
    ipRulesCount: 5,
    rateLimitsCount: 2,
    tags: ['admin', 'internal'],
    createdAt: '2025-08-15 09:00',
    updatedAt: '2025-08-25 16:22',
    createdBy: 'admin',
    description: 'Internal administration portal with strict IP whitelisting.',
    nodeBindings: [
      { nodeId: 'node-sg-01', nodeName: 'SG Edge Controller 01', ip: '10.0.1.1', ports: [80, 443], status: 'Synced', lastSynced: '2025-08-25 16:22' },
    ],
    recentActivities: [
      {
        id: 'act-4',
        type: 'policy',
        title: 'Policy modified',
        description: 'Added strict corporate IP CIDR filter',
        timestamp: '2025-08-25 16:22',
        color: 'purple',
      },
      {
        id: 'act-5',
        type: 'created',
        title: 'Domain created',
        description: 'By admin',
        timestamp: '2025-08-15 09:00',
        color: 'slate',
      },
    ],
  },
  {
    id: 'dom-3',
    domain: 'www.example.com',
    rootDomain: 'example.com',
    status: 'Active',
    tlsType: "Let's Encrypt",
    tlsExpiry: '2025-11-20',
    tlsAutoRenew: true,
    minTlsVersion: 'TLSv1.2',
    hstsEnabled: true,
    ocspStapling: false,
    upstream: 'http://10.0.1.10:8080',
    upstreamAlgorithm: 'round_robin',
    healthCheckPath: '/',
    upstreamServers: [
      { url: 'http://10.0.1.10:8080', weight: 1, maxFails: 3, failTimeout: '10s', healthy: true },
    ],
    rulesCount: 3,
    policiesCount: 1,
    ipRulesCount: 0,
    rateLimitsCount: 1,
    tags: ['public'],
    createdAt: '2025-08-10 11:30',
    updatedAt: '2025-08-24 09:11',
    createdBy: 'admin',
    description: 'Corporate landing and public marketing website.',
    recentActivities: [
      {
        id: 'act-6',
        type: 'updated',
        title: 'Domain settings saved',
        description: 'Enabled HTTP/2 edge push',
        timestamp: '2025-08-24 09:11',
        color: 'emerald',
      },
    ],
  },
  {
    id: 'dom-4',
    domain: 'app.vietnam.com',
    rootDomain: 'vietnam.com',
    status: 'Inactive',
    tlsType: 'Custom Cert',
    tlsExpiry: '2025-10-01',
    tlsAutoRenew: false,
    minTlsVersion: 'TLSv1.2',
    hstsEnabled: false,
    ocspStapling: false,
    upstream: 'http://10.10.1.5:8080',
    upstreamAlgorithm: 'round_robin',
    healthCheckPath: '/ping',
    upstreamServers: [
      { url: 'http://10.10.1.5:8080', weight: 1, maxFails: 2, failTimeout: '15s', healthy: false },
    ],
    rulesCount: 1,
    policiesCount: 1,
    ipRulesCount: 0,
    rateLimitsCount: 0,
    tags: ['staging'],
    createdAt: '2025-08-01 14:20',
    updatedAt: '2025-08-20 14:33',
    createdBy: 'operator',
    description: 'Regional application staging cluster.',
    recentActivities: [
      {
        id: 'act-7',
        type: 'updated',
        title: 'Status changed to Inactive',
        description: 'Maintenance scheduled',
        timestamp: '2025-08-20 14:33',
        color: 'amber',
      },
    ],
  },
  {
    id: 'dom-5',
    domain: 'auth.example.com',
    rootDomain: 'example.com',
    status: 'Active',
    tlsType: 'mTLS',
    tlsExpiry: '2026-08-12',
    tlsAutoRenew: true,
    minTlsVersion: 'TLSv1.3',
    hstsEnabled: true,
    ocspStapling: true,
    clientCaSubject: 'CN=Aurora Internal Root CA, O=Aurora Corp',
    upstream: 'https://auth.internal:8443',
    upstreamAlgorithm: 'least_conn',
    healthCheckPath: '/health',
    upstreamServers: [
      { url: 'https://auth.internal:8443', weight: 1, maxFails: 3, failTimeout: '5s', healthy: true },
    ],
    rulesCount: 5,
    policiesCount: 2,
    ipRulesCount: 2,
    rateLimitsCount: 4,
    tags: ['auth', 'secure'],
    createdAt: '2025-08-12 08:15',
    updatedAt: '2025-08-26 11:02',
    createdBy: 'admin',
    description: 'Single Sign-On and Identity Provider service requiring mutual TLS.',
    recentActivities: [
      {
        id: 'act-8',
        type: 'security',
        title: 'mTLS CA bundle updated',
        description: 'Rotated root certificate authority',
        timestamp: '2025-08-26 11:02',
        color: 'purple',
      },
      {
        id: 'act-9',
        type: 'rule',
        title: 'Brute force rule attached',
        description: 'Rate limit auth POST endpoints',
        timestamp: '2025-08-22 14:10',
        color: 'blue',
      },
    ],
  },
  {
    id: 'dom-6',
    domain: 'static.example.com',
    rootDomain: 'example.com',
    status: 'Active',
    tlsType: "Let's Encrypt",
    tlsExpiry: '2025-11-18',
    tlsAutoRenew: true,
    minTlsVersion: 'TLSv1.3',
    hstsEnabled: true,
    ocspStapling: true,
    upstream: 'http://10.0.2.10:8080',
    upstreamAlgorithm: 'round_robin',
    healthCheckPath: '/status',
    rulesCount: 2,
    policiesCount: 1,
    ipRulesCount: 0,
    rateLimitsCount: 1,
    tags: ['static', 'cdn'],
    createdAt: '2025-08-14 16:00',
    updatedAt: '2025-08-22 08:45',
    createdBy: 'admin',
    description: 'Static asset delivery with aggressive edge caching.',
    recentActivities: [
      {
        id: 'act-10',
        type: 'updated',
        title: 'Cache rule updated',
        description: 'Edge TTL extended to 30 days',
        timestamp: '2025-08-22 08:45',
        color: 'emerald',
      },
    ],
  },
  {
    id: 'dom-7',
    domain: 'blog.example.com',
    rootDomain: 'example.com',
    status: 'Active',
    tlsType: "Let's Encrypt",
    tlsExpiry: '2025-11-19',
    tlsAutoRenew: true,
    minTlsVersion: 'TLSv1.2',
    hstsEnabled: true,
    ocspStapling: false,
    upstream: 'http://10.0.1.11:8080',
    upstreamAlgorithm: 'round_robin',
    healthCheckPath: '/',
    rulesCount: 1,
    policiesCount: 1,
    ipRulesCount: 0,
    rateLimitsCount: 1,
    tags: ['blog'],
    createdAt: '2025-08-16 10:00',
    updatedAt: '2025-08-21 13:12',
    createdBy: 'admin',
    description: 'Engineering and company announcements publication.',
    recentActivities: [
      {
        id: 'act-11',
        type: 'updated',
        title: 'Cert renewed',
        description: 'Auto-renewed by Let\'s Encrypt client',
        timestamp: '2025-08-21 13:12',
        color: 'emerald',
      },
    ],
  },
  {
    id: 'dom-8',
    domain: 'dev.example.com',
    rootDomain: 'example.com',
    status: 'Inactive',
    tlsType: 'Self-signed',
    tlsExpiry: '2025-09-10',
    tlsAutoRenew: false,
    minTlsVersion: 'TLSv1.2',
    hstsEnabled: false,
    ocspStapling: false,
    upstream: 'http://10.0.3.10:8080',
    upstreamAlgorithm: 'round_robin',
    healthCheckPath: '/dev-ping',
    rulesCount: 0,
    policiesCount: 0,
    ipRulesCount: 1,
    rateLimitsCount: 0,
    tags: ['dev'],
    createdAt: '2025-08-19 15:45',
    updatedAt: '2025-08-20 10:01',
    createdBy: 'developer',
    description: 'Internal development sandbox environment.',
    recentActivities: [
      {
        id: 'act-12',
        type: 'created',
        title: 'Domain created',
        description: 'Self-signed certificate attached for staging testing',
        timestamp: '2025-08-20 10:01',
        color: 'slate',
      },
    ],
  },
  {
    id: 'dom-9',
    domain: 'b2b.example.com',
    rootDomain: 'example.com',
    status: 'Active',
    tlsType: 'mTLS',
    tlsExpiry: '2026-08-05',
    tlsAutoRenew: true,
    minTlsVersion: 'TLSv1.3',
    hstsEnabled: true,
    ocspStapling: true,
    clientCaSubject: 'CN=Partner B2B Federation CA, O=Global FinTech',
    upstream: 'https://b2b.internal:8443',
    upstreamAlgorithm: 'least_conn',
    healthCheckPath: '/healthz',
    rulesCount: 4,
    policiesCount: 2,
    ipRulesCount: 3,
    rateLimitsCount: 2,
    tags: ['b2b', 'partner'],
    createdAt: '2025-08-05 13:00',
    updatedAt: '2025-08-19 17:20',
    createdBy: 'admin',
    description: 'B2B integration endpoints secured by client certificate auth.',
    recentActivities: [
      {
        id: 'act-13',
        type: 'security',
        title: 'Partner cert rotated',
        description: 'Updated reciprocal TLS trust store',
        timestamp: '2025-08-19 17:20',
        color: 'purple',
      },
    ],
  },
  {
    id: 'dom-10',
    domain: 'shop.example.com',
    rootDomain: 'example.com',
    status: 'Active',
    tlsType: "Let's Encrypt",
    tlsExpiry: '2025-11-15',
    tlsAutoRenew: true,
    minTlsVersion: 'TLSv1.3',
    hstsEnabled: true,
    ocspStapling: true,
    upstream: 'http://10.0.1.12:8080',
    upstreamAlgorithm: 'round_robin',
    healthCheckPath: '/api/v1/health',
    rulesCount: 3,
    policiesCount: 2,
    ipRulesCount: 1,
    rateLimitsCount: 2,
    tags: ['shop', 'ecommerce'],
    createdAt: '2025-08-02 10:30',
    updatedAt: '2025-08-18 09:37',
    createdBy: 'admin',
    description: 'Online storefront e-commerce checkout and catalog.',
    recentActivities: [
      {
        id: 'act-14',
        type: 'rule',
        title: 'Anti-scraping enabled',
        description: 'Rate limit applied on /catalog endpoints',
        timestamp: '2025-08-18 09:37',
        color: 'blue',
      },
    ],
  },
  {
    id: 'dom-11',
    domain: 'gateway.internal.net',
    rootDomain: 'internal.net',
    status: 'Active',
    tlsType: 'mTLS',
    tlsExpiry: '2026-09-01',
    tlsAutoRenew: true,
    minTlsVersion: 'TLSv1.3',
    hstsEnabled: true,
    ocspStapling: true,
    clientCaSubject: 'CN=Mesh Inter-service CA, O=Aurora Cloud',
    upstream: 'https://gateway.internal:9443',
    upstreamAlgorithm: 'least_conn',
    healthCheckPath: '/healthz',
    rulesCount: 5,
    policiesCount: 2,
    ipRulesCount: 2,
    rateLimitsCount: 3,
    tags: ['internal', 'secure'],
    createdAt: '2025-07-28 09:00',
    updatedAt: '2025-08-17 14:15',
    createdBy: 'admin',
    description: 'Internal microservice RPC gateway with strict mTLS authentication.',
    recentActivities: [
      {
        id: 'act-15',
        type: 'updated',
        title: 'Routing updated',
        description: 'Added canary upstream targets',
        timestamp: '2025-08-17 14:15',
        color: 'emerald',
      },
    ],
  },
  {
    id: 'dom-12',
    domain: 'docs.example.com',
    rootDomain: 'example.com',
    status: 'Active',
    tlsType: "Let's Encrypt",
    tlsExpiry: '2025-11-12',
    tlsAutoRenew: true,
    minTlsVersion: 'TLSv1.2',
    hstsEnabled: true,
    ocspStapling: false,
    upstream: 'http://10.0.2.20:8080',
    upstreamAlgorithm: 'round_robin',
    healthCheckPath: '/',
    rulesCount: 1,
    policiesCount: 1,
    ipRulesCount: 0,
    rateLimitsCount: 1,
    tags: ['public'],
    createdAt: '2025-07-20 16:45',
    updatedAt: '2025-08-15 11:20',
    createdBy: 'admin',
    description: 'Developer documentation and public API references.',
    recentActivities: [
      {
        id: 'act-16',
        type: 'created',
        title: 'Domain created',
        description: 'By admin',
        timestamp: '2025-07-20 16:45',
        color: 'slate',
      },
    ],
  },
];
