use super::schema::Spec;
use std::path::Path;
use tracing::info;

pub struct MaterializeResult {
    pub nginx_changed: bool,
}

/// Atomically write bytes to destination path using a .tmp file.
/// Returns Ok(true) if file content changed, Ok(false) if identical.
pub async fn atomic_write_if_changed(dest: &Path, content: &[u8]) -> std::io::Result<bool> {
    if let Some(parent) = dest.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }

    if dest.exists()
        && let Ok(existing) = tokio::fs::read(dest).await
        && existing == content
    {
        return Ok(false);
    }

    let tmp = dest.with_extension(format!("tmp.{}", std::process::id()));
    tokio::fs::write(&tmp, content).await?;
    tokio::fs::rename(&tmp, dest).await?;
    Ok(true)
}

/// Materialize declarative Spec to concrete NGINX filesystem configuration files.
pub async fn materialize_nginx(
    spec: &Spec,
    policy_dir: &Path,
    routing_dir: &Path,
) -> Result<MaterializeResult, Box<dyn std::error::Error + Send + Sync>> {
    let mut changed = false;

    // 1. WAF Policy
    let policy_path = policy_dir.join("active-policy.json");
    let policy_json = if let Some(ref raw) = spec.waf.raw_json {
        raw.clone()
    } else if !spec.waf.rules.is_empty() {
        serde_json::to_string_pretty(&serde_json::json!({
            "schema_version": 2,
            "generation": spec.release_id,
            "rules": spec.waf.rules,
        }))?
    } else {
        let block_paths = if spec.waf.block_paths.is_empty() {
            vec!["/blocked".to_string(), "/__aurora_blocked".to_string()]
        } else {
            spec.waf.block_paths.clone()
        };
        serde_json::to_string_pretty(&serde_json::json!({
            "schema_version": 1,
            "block_paths": block_paths,
        }))?
    };
    if atomic_write_if_changed(&policy_path, policy_json.as_bytes()).await? {
        info!(
            "Updated active-policy.json (release_id: {})",
            spec.release_id
        );
        changed = true;
    }

    // 2. Access Policy
    let access_path = policy_dir.join("active-access.json");
    let access_json = if let Some(ref raw) = spec.access.raw_json {
        raw.clone()
    } else {
        serde_json::to_string_pretty(&serde_json::json!({
            "schema_version": 1,
            "generation": spec.access.generation.unwrap_or(0),
            "rules": spec.access.rules,
        }))?
    };
    if atomic_write_if_changed(&access_path, access_json.as_bytes()).await? {
        info!("Updated active-access.json");
        changed = true;
    }

    // 3. Upstreams Config
    let upstreams_path = policy_dir.join("active-upstreams.conf");
    let upstreams_content = if let Some(ref raw) = spec.upstreams_conf {
        raw.clone()
    } else if !spec.upstreams.is_empty() {
        let mut buf = String::from("# Generated by Aurora Dataplane Agent\n");
        for up in &spec.upstreams {
            buf.push_str(&format!("upstream {} {{\n", up.name));
            for s in &up.servers {
                buf.push_str(&format!("    server {} weight={};\n", s.addr, s.weight));
            }
            buf.push_str("}\n");
        }
        buf
    } else {
        "# No active upstreams configured\n".to_string()
    };
    if atomic_write_if_changed(&upstreams_path, upstreams_content.as_bytes()).await? {
        info!("Updated active-upstreams.conf");
        changed = true;
    }

    // 4. Domain Routing Config
    let routing_path = routing_dir.join("active-domain-routing.conf");
    let routing_content = if let Some(ref raw) = spec.routing_conf {
        raw.clone()
    } else if !spec.routing.domains.is_empty() {
        let mut buf = String::from("# Generated by Aurora Dataplane Agent\n");
        for d in &spec.routing.domains {
            buf.push_str(&format!("server {{\n    listen 80;\n    server_name {};\n    include /etc/nginx/domain-waf.conf;\n", d.host));
            for loc in &d.locations {
                buf.push_str(&format!(
                    "    location {} {{\n        proxy_pass http://{};\n    }}\n",
                    loc.path, loc.upstream
                ));
            }
            buf.push_str("}\n");
        }
        buf
    } else {
        "# No configured domains yet\n".to_string()
    };
    if atomic_write_if_changed(&routing_path, routing_content.as_bytes()).await? {
        info!("Updated active-domain-routing.conf");
        changed = true;
    }

    // 5. Extensions NGINX Directives (HTTP block)
    let extensions_http_path = policy_dir.join("active-extensions-http.conf");
    let extensions_http_content = generate_extensions_http_conf(&spec.extensions.dynamic);
    if atomic_write_if_changed(&extensions_http_path, extensions_http_content.as_bytes()).await? {
        info!("Updated active-extensions-http.conf");
        changed = true;
    }

    // 6. Extensions NGINX Directives (Server block)
    let extensions_path = policy_dir.join("active-extensions.conf");
    let extensions_content = generate_extensions_nginx_conf(&spec.extensions.dynamic);
    if atomic_write_if_changed(&extensions_path, extensions_content.as_bytes()).await? {
        info!("Updated active-extensions.conf");
        changed = true;
    }

    // 7. Dynamic Extension Modules (load_module directives)
    let modules_dir = routing_dir.join("dependencies/current");
    if !modules_dir.exists() {
        let _ = tokio::fs::create_dir_all(&modules_dir).await;
    }
    let modules_path = modules_dir.join("modules.conf");
    let modules_content = generate_modules_conf(&spec.extensions.dynamic);
    if atomic_write_if_changed(&modules_path, modules_content.as_bytes()).await? {
        info!("Updated modules.conf for dynamic extension modules");
        changed = true;
    }

    Ok(MaterializeResult {
        nginx_changed: changed,
    })
}

fn generate_modules_conf(
    extensions: &std::collections::HashMap<String, serde_yaml::Value>,
) -> String {
    let mut buf =
        String::from("# Generated by Aurora Dataplane Agent for dynamic extension modules\n");
    let mut has_modules = false;

    for (name, val) in extensions {
        if let serde_yaml::Value::Mapping(map) = val {
            let enabled = map
                .get(serde_yaml::Value::String("enabled".to_string()))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);

            if !enabled {
                continue;
            }

            if name == "compression-brotli" {
                buf.push_str("load_module /opt/aurora-dependencies/brotli/ngx_http_brotli_filter_module.so;\n");
                buf.push_str("load_module /opt/aurora-dependencies/brotli/ngx_http_brotli_static_module.so;\n");
                has_modules = true;
            }
        }
    }

    if !has_modules {
        buf.push_str("# No dynamic modules loaded\n");
    }
    buf
}

fn generate_extensions_http_conf(
    extensions: &std::collections::HashMap<String, serde_yaml::Value>,
) -> String {
    let mut buf = String::from("# Generated by Aurora Dataplane Agent for HTTP-level extension directives\n");
    let mut has_directives = false;

    for (name, val) in extensions {
        if let serde_yaml::Value::Mapping(map) = val {
            let enabled = map
                .get(serde_yaml::Value::String("enabled".to_string()))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);

            if !enabled {
                continue;
            }

            match name.as_str() {
                "rate-limit" => {
                    let rate = map
                        .get(serde_yaml::Value::String("rate".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(100);
                    let period_secs = map
                        .get(serde_yaml::Value::String("period_secs".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(1);
                    let rate_str = if period_secs == 60 {
                        format!("{}r/m", rate)
                    } else {
                        format!("{}r/s", rate.max(1))
                    };
                    buf.push_str(&format!(
                        "limit_req_zone $binary_remote_addr zone=aurora_rate_limit:10m rate={};\n",
                        rate_str
                    ));
                    has_directives = true;
                }
                "rate-limit-local" => {
                    let refill_rate = map
                        .get(serde_yaml::Value::String("refill_rate".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(100);
                    buf.push_str(&format!(
                        "limit_req_zone $binary_remote_addr zone=aurora_rate_limit_local:10m rate={}r/s;\n",
                        refill_rate.max(1)
                    ));
                    has_directives = true;
                }
                "connection-limit" => {
                    buf.push_str("limit_conn_zone $binary_remote_addr zone=aurora_conn_limit:10m;\n");
                    has_directives = true;
                }
                _ => {}
            }
        }
    }

    if !has_directives {
        buf.push_str("# No active HTTP-level extension directives\n");
    }
    buf
}

fn generate_extensions_nginx_conf(
    extensions: &std::collections::HashMap<String, serde_yaml::Value>,
) -> String {
    let mut buf = String::from("# Generated by Aurora Dataplane Agent for active extensions\n");
    let mut has_directives = false;

    for (name, val) in extensions {
        if let serde_yaml::Value::Mapping(map) = val {
            let enabled = map
                .get(serde_yaml::Value::String("enabled".to_string()))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);

            if !enabled {
                continue;
            }

            match name.as_str() {
                "rate-limit" => {
                    let burst = map
                        .get(serde_yaml::Value::String("burst".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(200);
                    let rejected_code = map
                        .get(serde_yaml::Value::String("rejected_code".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(429);
                    buf.push_str(&format!("limit_req_status {};\n", rejected_code));
                    buf.push_str(&format!("limit_req zone=aurora_rate_limit burst={} nodelay;\n", burst));
                    has_directives = true;
                }
                "rate-limit-local" => {
                    let capacity = map
                        .get(serde_yaml::Value::String("capacity".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(1000);
                    let rejected_code = map
                        .get(serde_yaml::Value::String("rejected_code".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(429);
                    buf.push_str(&format!("limit_req_status {};\n", rejected_code));
                    buf.push_str(&format!("limit_req zone=aurora_rate_limit_local burst={} nodelay;\n", capacity));
                    has_directives = true;
                }
                "connection-limit" => {
                    let max_conn = map
                        .get(serde_yaml::Value::String("max_connections_per_ip".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(50);
                    let rejected_code = map
                        .get(serde_yaml::Value::String("rejected_code".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(503);
                    buf.push_str(&format!("limit_conn_status {};\n", rejected_code));
                    buf.push_str(&format!("limit_conn aurora_conn_limit {};\n", max_conn));
                    has_directives = true;
                }
                "bandwidth-limit" => {
                    if let Some(rate) = map
                        .get(serde_yaml::Value::String("rate_kb_per_sec".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("limit_rate {}k;\n", rate));
                        has_directives = true;
                    }
                    if let Some(burst) = map
                        .get(serde_yaml::Value::String("burst_kb".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("limit_rate_after {}k;\n", burst));
                        has_directives = true;
                    }
                }
                "cors" => {
                    let allow_credentials = map
                        .get(serde_yaml::Value::String("allow_credentials".to_string()))
                        .and_then(|v| v.as_bool())
                        .unwrap_or(false);

                    let origin_header = if allow_credentials {
                        "$http_origin"
                    } else if let Some(serde_yaml::Value::Sequence(origins)) = map.get(serde_yaml::Value::String("allow_origins".to_string())) {
                        if origins.len() == 1 {
                            origins[0].as_str().unwrap_or("*")
                        } else {
                            "$http_origin"
                        }
                    } else {
                        "*"
                    };

                    let methods = if let Some(serde_yaml::Value::Sequence(seq)) = map.get(serde_yaml::Value::String("allow_methods".to_string())) {
                        seq.iter().filter_map(|v| v.as_str()).collect::<Vec<_>>().join(", ")
                    } else {
                        "GET, POST, PUT, DELETE, PATCH, OPTIONS".to_string()
                    };

                    let headers = if let Some(serde_yaml::Value::Sequence(seq)) = map.get(serde_yaml::Value::String("allow_headers".to_string())) {
                        seq.iter().filter_map(|v| v.as_str()).collect::<Vec<_>>().join(", ")
                    } else {
                        "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-API-Key,X-Request-ID".to_string()
                    };

                    let max_age = map
                        .get(serde_yaml::Value::String("max_age".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(86400);

                    buf.push_str(&format!("add_header 'Access-Control-Allow-Origin' '{}' always;\n", origin_header));
                    buf.push_str(&format!("add_header 'Access-Control-Allow-Methods' '{}' always;\n", methods));
                    buf.push_str(&format!("add_header 'Access-Control-Allow-Headers' '{}' always;\n", headers));
                    buf.push_str(&format!("add_header 'Access-Control-Max-Age' '{}' always;\n", max_age));

                    if allow_credentials {
                        buf.push_str("add_header 'Access-Control-Allow-Credentials' 'true' always;\n");
                    }

                    if let Some(serde_yaml::Value::Sequence(seq)) = map.get(serde_yaml::Value::String("expose_headers".to_string())) {
                        let exp = seq.iter().filter_map(|v| v.as_str()).collect::<Vec<_>>().join(", ");
                        if !exp.is_empty() {
                            buf.push_str(&format!("add_header 'Access-Control-Expose-Headers' '{}' always;\n", exp));
                        }
                    }

                    // Handle preflight OPTIONS
                    buf.push_str("if ($request_method = 'OPTIONS') {\n    return 204;\n}\n");

                    has_directives = true;
                }
                "request-header-transform" => {
                    if let Some(serde_yaml::Value::Mapping(add_map)) = map.get(serde_yaml::Value::String("add_headers".to_string())) {
                        for (k, v) in add_map {
                            if let (Some(ks), Some(vs)) = (k.as_str(), v.as_str()) {
                                buf.push_str(&format!("proxy_set_header {} \"{}\";\n", ks, vs.replace('"', "\\\"")));
                                has_directives = true;
                            }
                        }
                    }
                    if let Some(serde_yaml::Value::Sequence(rem_seq)) = map.get(serde_yaml::Value::String("remove_headers".to_string())) {
                        for k in rem_seq {
                            if let Some(ks) = k.as_str() {
                                buf.push_str(&format!("proxy_set_header {} \"\";\n", ks));
                                has_directives = true;
                            }
                        }
                    }
                }
                "response-header-transform" => {
                    if let Some(serde_yaml::Value::Mapping(add_map)) = map.get(serde_yaml::Value::String("add_headers".to_string())) {
                        for (k, v) in add_map {
                            if let (Some(ks), Some(vs)) = (k.as_str(), v.as_str()) {
                                buf.push_str(&format!("add_header {} \"{}\" always;\n", ks, vs.replace('"', "\\\"")));
                                has_directives = true;
                            }
                        }
                    }
                    if let Some(serde_yaml::Value::Sequence(rem_seq)) = map.get(serde_yaml::Value::String("remove_headers".to_string())) {
                        for k in rem_seq {
                            if let Some(ks) = k.as_str() {
                                buf.push_str(&format!("proxy_hide_header {};\n", ks));
                                has_directives = true;
                            }
                        }
                    }
                }
                "maintenance-mode" => {
                    let status_code = map
                        .get(serde_yaml::Value::String("status_code".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(503);
                    let retry_after = map
                        .get(serde_yaml::Value::String("retry_after_secs".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(300);
                    let message = map
                        .get(serde_yaml::Value::String("message".to_string()))
                        .and_then(|v| v.as_str())
                        .unwrap_or("Service undergoing planned maintenance. Please retry in a few moments.");
                    let bypass_header = map
                        .get(serde_yaml::Value::String("bypass_header".to_string()))
                        .and_then(|v| v.as_str());

                    buf.push_str(&format!("add_header Retry-After {} always;\n", retry_after));
                    let escaped_msg = message.replace('\'', "'\\''");
                    let body_json = format!("{{\"error\":\"{}\"}}", escaped_msg);

                    if let Some(bypass) = bypass_header {
                        let var_name = bypass.to_ascii_lowercase().replace('-', "_");
                        buf.push_str("set $aurora_maintenance 1;\n");
                        buf.push_str(&format!("if ($http_{}) {{\n    set $aurora_maintenance 0;\n}}\n", var_name));
                        buf.push_str(&format!(
                            "if ($aurora_maintenance = 1) {{\n    return {} '{}';\n}}\n",
                            status_code, body_json
                        ));
                    } else {
                        buf.push_str(&format!("return {} '{}';\n", status_code, body_json));
                    }
                    has_directives = true;
                }
                "request-termination" => {
                    let status_code = map
                        .get(serde_yaml::Value::String("status_code".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(200);
                    if let Some(serde_yaml::Value::Mapping(hdrs)) = map.get(serde_yaml::Value::String("headers".to_string())) {
                        for (k, v) in hdrs {
                            if let (Some(ks), Some(vs)) = (k.as_str(), v.as_str()) {
                                buf.push_str(&format!("add_header {} \"{}\" always;\n", ks, vs.replace('"', "\\\"")));
                            }
                        }
                    }
                    let body = map
                        .get(serde_yaml::Value::String("body".to_string()))
                        .and_then(|v| v.as_str())
                        .unwrap_or("{\"status\":\"mocked\"}");
                    let escaped_body = body.replace('\'', "'\\''");
                    buf.push_str(&format!("return {} '{}';\n", status_code, escaped_body));
                    has_directives = true;
                }
                "uri-rewrite" => {
                    if let Some(serde_yaml::Value::Sequence(rules)) = map.get(serde_yaml::Value::String("rules".to_string())) {
                        for r in rules {
                            if let serde_yaml::Value::Mapping(rmap) = r {
                                if let (Some(pat), Some(rep)) = (
                                    rmap.get(serde_yaml::Value::String("pattern".to_string())).and_then(|v| v.as_str()),
                                    rmap.get(serde_yaml::Value::String("replacement".to_string())).and_then(|v| v.as_str()),
                                ) {
                                    buf.push_str(&format!("rewrite {} {} break;\n", pat, rep));
                                    has_directives = true;
                                }
                            }
                        }
                    }
                }
                "request-size-limit" => {
                    if let Some(bytes) = map
                        .get(serde_yaml::Value::String("max_body_bytes".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("client_max_body_size {};\n", bytes));
                        has_directives = true;
                    }
                }
                "response-buffering" => {
                    buf.push_str("proxy_buffering off;\n");
                    has_directives = true;
                }
                "compression-brotli" => {
                    buf.push_str("brotli on;\n");
                    if let Some(level) = map
                        .get(serde_yaml::Value::String("quality".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("brotli_comp_level {};\n", level));
                    }
                    buf.push_str("brotli_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;\n");
                    has_directives = true;
                }
                "compression-gzip" => {
                    buf.push_str("gzip on;\n");
                    if let Some(level) = map
                        .get(serde_yaml::Value::String("level".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("gzip_comp_level {};\n", level));
                    }
                    buf.push_str("gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;\n");
                    has_directives = true;
                }
                "timeout-policy" => {
                    if let Some(ms) = map
                        .get(serde_yaml::Value::String("connect_timeout_ms".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("proxy_connect_timeout {}ms;\n", ms));
                        has_directives = true;
                    }
                    if let Some(ms) = map
                        .get(serde_yaml::Value::String("read_timeout_ms".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("proxy_read_timeout {}ms;\n", ms));
                        has_directives = true;
                    }
                    if let Some(ms) = map
                        .get(serde_yaml::Value::String("write_timeout_ms".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("proxy_send_timeout {}ms;\n", ms));
                        has_directives = true;
                    }
                }
                _ => {}
            }
        }
    }

    if !has_directives {
        buf.push_str("# No active NGINX-level extension directives\n");
    }
    buf
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_materialize_nginx_files() {
        let base_tmp =
            std::env::temp_dir().join(format!("aurora-spec-test-{}", std::process::id()));
        let policy_dir = base_tmp.join("policy");
        let routing_dir = base_tmp.join("routing");
        let _ = tokio::fs::remove_dir_all(&base_tmp).await;

        let spec = Spec {
            release_id: 99,
            waf: crate::spec::waf::WafSpec {
                mode: "enforce".to_string(),
                block_paths: vec!["/blocked".to_string()],
                ..Default::default()
            },
            upstreams: vec![crate::spec::upstream::UpstreamSpec {
                name: "backend".to_string(),
                servers: vec![crate::spec::upstream::UpstreamServerSpec {
                    addr: "127.0.0.1:8080".to_string(),
                    weight: 2,
                }],
            }],
            ..Default::default()
        };

        let res = materialize_nginx(&spec, &policy_dir, &routing_dir)
            .await
            .expect("materialize");
        assert!(res.nginx_changed);

        assert!(policy_dir.join("active-policy.json").exists());
        assert!(policy_dir.join("active-access.json").exists());
        assert!(policy_dir.join("active-upstreams.conf").exists());
        assert!(policy_dir.join("active-extensions-http.conf").exists());
        assert!(policy_dir.join("active-extensions.conf").exists());
        assert!(routing_dir.join("active-domain-routing.conf").exists());
        assert!(
            routing_dir
                .join("dependencies/current/modules.conf")
                .exists()
        );

        let up_conf = tokio::fs::read_to_string(policy_dir.join("active-upstreams.conf"))
            .await
            .unwrap();
        assert!(up_conf.contains("upstream backend"));
        assert!(up_conf.contains("server 127.0.0.1:8080 weight=2;"));

        // Second run with same spec should NOT report changed
        let res2 = materialize_nginx(&spec, &policy_dir, &routing_dir)
            .await
            .expect("materialize 2");
        assert!(!res2.nginx_changed);
    }

    #[test]
    fn test_extensions_generation() {
        let mut extensions = std::collections::HashMap::new();

        // 1. Rate Limit
        let rl_yaml: serde_yaml::Value = serde_yaml::from_str(
            r#"
            enabled: true
            rate: 50
            burst: 100
            period_secs: 1
            rejected_code: 429
            "#,
        )
        .unwrap();
        extensions.insert("rate-limit".to_string(), rl_yaml);

        // 2. CORS
        let cors_yaml: serde_yaml::Value = serde_yaml::from_str(
            r#"
            enabled: true
            allow_origins: ["https://example.com"]
            allow_methods: ["GET", "POST"]
            allow_headers: ["Authorization", "Content-Type"]
            allow_credentials: true
            max_age: 3600
            "#,
        )
        .unwrap();
        extensions.insert("cors".to_string(), cors_yaml);

        // 3. Maintenance Mode
        let maint_yaml: serde_yaml::Value = serde_yaml::from_str(
            r#"
            enabled: true
            status_code: 503
            bypass_header: "X-Bypass"
            retry_after_secs: 120
            message: "Under upgrade"
            "#,
        )
        .unwrap();
        extensions.insert("maintenance-mode".to_string(), maint_yaml);

        let http_conf = generate_extensions_http_conf(&extensions);
        assert!(http_conf.contains("limit_req_zone $binary_remote_addr zone=aurora_rate_limit:10m rate=50r/s;"));

        let server_conf = generate_extensions_nginx_conf(&extensions);
        assert!(server_conf.contains("limit_req_status 429;"));
        assert!(server_conf.contains("limit_req zone=aurora_rate_limit burst=100 nodelay;"));
        assert!(server_conf.contains("add_header 'Access-Control-Allow-Origin' '$http_origin' always;"));
        assert!(server_conf.contains("add_header 'Access-Control-Allow-Credentials' 'true' always;"));
        assert!(server_conf.contains("add_header Retry-After 120 always;"));
        assert!(server_conf.contains("if ($http_x_bypass)"));
        assert!(server_conf.contains("return 503 '{\"error\":\"Under upgrade\"}';"));
    }
}
