use super::schema::Spec;
use std::path::Path;
use tracing::info;

pub struct MaterializeResult {
    pub nginx_changed: bool,
}

/// Atomically write bytes to destination path using a .tmp file.
/// Returns Ok(true) if file content changed, Ok(false) if identical.
pub async fn atomic_write_if_changed(dest: &Path, content: &[u8]) -> std::io::Result<bool> {
    if let Some(parent) = dest.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }

    if dest.exists()
        && let Ok(existing) = tokio::fs::read(dest).await
        && existing == content
    {
        return Ok(false);
    }

    let tmp = dest.with_extension(format!("tmp.{}", std::process::id()));
    tokio::fs::write(&tmp, content).await?;
    tokio::fs::rename(&tmp, dest).await?;
    Ok(true)
}

/// Materialize declarative Spec to concrete NGINX filesystem configuration files.
pub async fn materialize_nginx(
    spec: &Spec,
    policy_dir: &Path,
    routing_dir: &Path,
) -> Result<MaterializeResult, Box<dyn std::error::Error + Send + Sync>> {
    let mut changed = false;

    // 1. WAF Policy
    let policy_path = policy_dir.join("active-policy.json");
    let policy_json = if let Some(ref raw) = spec.waf.raw_json {
        raw.clone()
    } else if !spec.waf.rules.is_empty() {
        serde_json::to_string_pretty(&serde_json::json!({
            "schema_version": 2,
            "generation": spec.release_id,
            "rules": spec.waf.rules,
        }))?
    } else {
        let block_paths = if spec.waf.block_paths.is_empty() {
            vec!["/blocked".to_string(), "/__aurora_blocked".to_string()]
        } else {
            spec.waf.block_paths.clone()
        };
        serde_json::to_string_pretty(&serde_json::json!({
            "schema_version": 1,
            "block_paths": block_paths,
        }))?
    };
    if atomic_write_if_changed(&policy_path, policy_json.as_bytes()).await? {
        info!(
            "Updated active-policy.json (release_id: {})",
            spec.release_id
        );
        changed = true;
    }

    // 2. Access Policy
    let access_path = policy_dir.join("active-access.json");
    let access_json = if let Some(ref raw) = spec.access.raw_json {
        raw.clone()
    } else {
        serde_json::to_string_pretty(&serde_json::json!({
            "schema_version": 1,
            "generation": spec.access.generation.unwrap_or(0),
            "rules": spec.access.rules,
        }))?
    };
    if atomic_write_if_changed(&access_path, access_json.as_bytes()).await? {
        info!("Updated active-access.json");
        changed = true;
    }

    // 3. Upstreams Config
    let upstreams_path = policy_dir.join("active-upstreams.conf");
    let upstreams_content = if let Some(ref raw) = spec.upstreams_conf {
        raw.clone()
    } else if !spec.upstreams.is_empty() {
        let mut buf = String::from("# Generated by Aurora Dataplane Agent\n");
        for up in &spec.upstreams {
            buf.push_str(&format!("upstream {} {{\n", up.name));
            for s in &up.servers {
                buf.push_str(&format!("    server {} weight={};\n", s.addr, s.weight));
            }
            buf.push_str("}\n");
        }
        buf
    } else {
        "# No active upstreams configured\n".to_string()
    };
    if atomic_write_if_changed(&upstreams_path, upstreams_content.as_bytes()).await? {
        info!("Updated active-upstreams.conf");
        changed = true;
    }

    // 4. Domain Routing Config
    let routing_path = routing_dir.join("active-domain-routing.conf");
    let routing_content = if let Some(ref raw) = spec.routing_conf {
        raw.clone()
    } else if !spec.routing.domains.is_empty() {
        let mut buf = String::from("# Generated by Aurora Dataplane Agent\n");
        for d in &spec.routing.domains {
            buf.push_str(&format!("server {{\n    listen 80;\n    server_name {};\n    include /etc/nginx/domain-waf.conf;\n", d.host));
            for loc in &d.locations {
                buf.push_str(&format!(
                    "    location {} {{\n        proxy_pass http://{};\n    }}\n",
                    loc.path, loc.upstream
                ));
            }
            buf.push_str("}\n");
        }
        buf
    } else {
        "# No configured domains yet\n".to_string()
    };
    if atomic_write_if_changed(&routing_path, routing_content.as_bytes()).await? {
        info!("Updated active-domain-routing.conf");
        changed = true;
    }

    // 5. Extensions NGINX Directives
    let extensions_path = policy_dir.join("active-extensions.conf");
    let extensions_content = generate_extensions_nginx_conf(&spec.extensions.dynamic);
    if atomic_write_if_changed(&extensions_path, extensions_content.as_bytes()).await? {
        info!("Updated active-extensions.conf");
        changed = true;
    }

    // 6. Dynamic Extension Modules (load_module directives)
    let modules_dir = routing_dir.join("dependencies/current");
    if !modules_dir.exists() {
        let _ = tokio::fs::create_dir_all(&modules_dir).await;
    }
    let modules_path = modules_dir.join("modules.conf");
    let modules_content = generate_modules_conf(&spec.extensions.dynamic);
    if atomic_write_if_changed(&modules_path, modules_content.as_bytes()).await? {
        info!("Updated modules.conf for dynamic extension modules");
        changed = true;
    }

    Ok(MaterializeResult {
        nginx_changed: changed,
    })
}

fn generate_modules_conf(
    extensions: &std::collections::HashMap<String, serde_yaml::Value>,
) -> String {
    let mut buf =
        String::from("# Generated by Aurora Dataplane Agent for dynamic extension modules\n");
    let mut has_modules = false;

    for (name, val) in extensions {
        if let serde_yaml::Value::Mapping(map) = val {
            let enabled = map
                .get(serde_yaml::Value::String("enabled".to_string()))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);

            if !enabled {
                continue;
            }

            if name == "compression-brotli" {
                buf.push_str("load_module /opt/aurora-dependencies/brotli/ngx_http_brotli_filter_module.so;\n");
                buf.push_str("load_module /opt/aurora-dependencies/brotli/ngx_http_brotli_static_module.so;\n");
                has_modules = true;
            }
        }
    }

    if !has_modules {
        buf.push_str("# No dynamic modules loaded\n");
    }
    buf
}

fn generate_extensions_nginx_conf(
    extensions: &std::collections::HashMap<String, serde_yaml::Value>,
) -> String {
    let mut buf = String::from("# Generated by Aurora Dataplane Agent for active extensions\n");
    let mut has_directives = false;

    for (name, val) in extensions {
        if let serde_yaml::Value::Mapping(map) = val {
            let enabled = map
                .get(serde_yaml::Value::String("enabled".to_string()))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);

            if !enabled {
                continue;
            }

            match name.as_str() {
                "request-size-limit" => {
                    if let Some(bytes) = map
                        .get(serde_yaml::Value::String("max_body_bytes".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("client_max_body_size {};\n", bytes));
                        has_directives = true;
                    }
                }
                "response-buffering" => {
                    buf.push_str("proxy_buffering off;\n");
                    has_directives = true;
                }
                "compression-brotli" => {
                    buf.push_str("brotli on;\n");
                    if let Some(level) = map
                        .get(serde_yaml::Value::String("quality".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("brotli_comp_level {};\n", level));
                    }
                    buf.push_str("brotli_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;\n");
                    has_directives = true;
                }
                "compression-gzip" => {
                    buf.push_str("gzip on;\n");
                    if let Some(level) = map
                        .get(serde_yaml::Value::String("level".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("gzip_comp_level {};\n", level));
                    }
                    buf.push_str("gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;\n");
                    has_directives = true;
                }
                "timeout-policy" => {
                    if let Some(ms) = map
                        .get(serde_yaml::Value::String("connect_timeout_ms".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("proxy_connect_timeout {}ms;\n", ms));
                        has_directives = true;
                    }
                    if let Some(ms) = map
                        .get(serde_yaml::Value::String("read_timeout_ms".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("proxy_read_timeout {}ms;\n", ms));
                        has_directives = true;
                    }
                    if let Some(ms) = map
                        .get(serde_yaml::Value::String("write_timeout_ms".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("proxy_send_timeout {}ms;\n", ms));
                        has_directives = true;
                    }
                }
                _ => {}
            }
        }
    }

    if !has_directives {
        buf.push_str("# No active NGINX-level extension directives\n");
    }
    buf
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_materialize_nginx_files() {
        let base_tmp =
            std::env::temp_dir().join(format!("aurora-spec-test-{}", std::process::id()));
        let policy_dir = base_tmp.join("policy");
        let routing_dir = base_tmp.join("routing");
        let _ = tokio::fs::remove_dir_all(&base_tmp).await;

        let spec = Spec {
            release_id: 99,
            waf: crate::spec::waf::WafSpec {
                mode: "enforce".to_string(),
                block_paths: vec!["/blocked".to_string()],
                ..Default::default()
            },
            upstreams: vec![crate::spec::upstream::UpstreamSpec {
                name: "backend".to_string(),
                servers: vec![crate::spec::upstream::UpstreamServerSpec {
                    addr: "127.0.0.1:8080".to_string(),
                    weight: 2,
                }],
            }],
            ..Default::default()
        };

        let res = materialize_nginx(&spec, &policy_dir, &routing_dir)
            .await
            .expect("materialize");
        assert!(res.nginx_changed);

        assert!(policy_dir.join("active-policy.json").exists());
        assert!(policy_dir.join("active-access.json").exists());
        assert!(policy_dir.join("active-upstreams.conf").exists());
        assert!(policy_dir.join("active-extensions.conf").exists());
        assert!(routing_dir.join("active-domain-routing.conf").exists());
        assert!(
            routing_dir
                .join("dependencies/current/modules.conf")
                .exists()
        );

        let up_conf = tokio::fs::read_to_string(policy_dir.join("active-upstreams.conf"))
            .await
            .unwrap();
        assert!(up_conf.contains("upstream backend"));
        assert!(up_conf.contains("server 127.0.0.1:8080 weight=2;"));

        // Second run with same spec should NOT report changed
        let res2 = materialize_nginx(&spec, &policy_dir, &routing_dir)
            .await
            .expect("materialize 2");
        assert!(!res2.nginx_changed);
    }
}
