use super::NodeSpec;
use std::path::Path;
use tracing::info;

pub struct MaterializeResult {
    pub nginx_changed: bool,
}

/// Atomically write bytes to destination path using a .tmp file.
/// Returns Ok(true) if file content changed, Ok(false) if identical.
pub async fn atomic_write_if_changed(dest: &Path, content: &[u8]) -> std::io::Result<bool> {
    if let Some(parent) = dest.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }

    if dest.exists()
        && let Ok(existing) = tokio::fs::read(dest).await
        && existing == content
    {
        return Ok(false);
    }

    let tmp = dest.with_extension(format!("tmp.{}", std::process::id()));
    tokio::fs::write(&tmp, content).await?;
    tokio::fs::rename(&tmp, dest).await?;
    Ok(true)
}

/// Materialize declarative NodeSpec to concrete NGINX filesystem configuration files.
pub async fn materialize_nginx(
    spec: &NodeSpec,
    policy_dir: &Path,
    routing_dir: &Path,
) -> Result<MaterializeResult, Box<dyn std::error::Error + Send + Sync>> {
    let mut changed = false;

    // 1. WAF Policy
    let policy_path = policy_dir.join("active-policy.json");
    let policy_json = if let Some(ref raw) = spec.waf.raw_json {
        raw.clone()
    } else if !spec.waf.rules.is_empty() {
        serde_json::to_string_pretty(&serde_json::json!({
            "schema_version": 2,
            "generation": spec.release_id,
            "rules": spec.waf.rules,
        }))?
    } else {
        let block_paths = if spec.waf.block_paths.is_empty() {
            vec!["/blocked".to_string(), "/__aurora_blocked".to_string()]
        } else {
            spec.waf.block_paths.clone()
        };
        serde_json::to_string_pretty(&serde_json::json!({
            "schema_version": 1,
            "block_paths": block_paths,
        }))?
    };
    if atomic_write_if_changed(&policy_path, policy_json.as_bytes()).await? {
        info!(
            "Updated active-policy.json (release_id: {})",
            spec.release_id
        );
        changed = true;
    }

    // 2. Access Policy
    let access_path = policy_dir.join("active-access.json");
    let access_json = if let Some(ref raw) = spec.access.raw_json {
        raw.clone()
    } else {
        serde_json::to_string_pretty(&serde_json::json!({
            "schema_version": 1,
            "generation": spec.access.generation.unwrap_or(0),
            "rules": spec.access.rules,
        }))?
    };
    if atomic_write_if_changed(&access_path, access_json.as_bytes()).await? {
        info!("Updated active-access.json");
        changed = true;
    }

    // 3. Upstreams Config
    let upstreams_path = policy_dir.join("active-upstreams.conf");
    let upstreams_content = if let Some(ref raw) = spec.upstreams_conf {
        raw.clone()
    } else if !spec.upstreams.is_empty() {
        let mut buf = String::from("# Generated by Aurora Dataplane Agent\n");
        for up in &spec.upstreams {
            buf.push_str(&format!("upstream {} {{\n", up.name));
            for s in &up.servers {
                buf.push_str(&format!("    server {} weight={};\n", s.addr, s.weight));
            }
            buf.push_str("}\n");
        }
        buf
    } else {
        "# No active upstreams configured\n".to_string()
    };
    if atomic_write_if_changed(&upstreams_path, upstreams_content.as_bytes()).await? {
        info!("Updated active-upstreams.conf");
        changed = true;
    }

    // 4. Domain Routing Config
    let routing_path = routing_dir.join("active-domain-routing.conf");
    let routing_content = if let Some(ref raw) = spec.routing_conf {
        raw.clone()
    } else if !spec.routing.domains.is_empty() {
        let mut buf = String::from("# Generated by Aurora Dataplane Agent\n");
        for d in &spec.routing.domains {
            buf.push_str(&format!("server {{\n    listen 80;\n    server_name {};\n    include /etc/nginx/domain-waf.conf;\n", d.host));
            for loc in &d.locations {
                buf.push_str(&format!(
                    "    location {} {{\n        proxy_pass http://{};\n    }}\n",
                    loc.path, loc.upstream
                ));
            }
            buf.push_str("}\n");
        }
        buf
    } else {
        "# No configured domains yet\n".to_string()
    };
    if atomic_write_if_changed(&routing_path, routing_content.as_bytes()).await? {
        info!("Updated active-domain-routing.conf");
        changed = true;
    }

    Ok(MaterializeResult {
        nginx_changed: changed,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_materialize_nginx_files() {
        let base_tmp =
            std::env::temp_dir().join(format!("aurora-spec-test-{}", std::process::id()));
        let policy_dir = base_tmp.join("policy");
        let routing_dir = base_tmp.join("routing");
        let _ = tokio::fs::remove_dir_all(&base_tmp).await;

        let spec = NodeSpec {
            release_id: 99,
            waf: crate::spec::WafSpec {
                mode: "enforce".to_string(),
                block_paths: vec!["/blocked".to_string()],
                ..Default::default()
            },
            upstreams: vec![crate::spec::UpstreamSpec {
                name: "backend".to_string(),
                servers: vec![crate::spec::UpstreamServerSpec {
                    addr: "127.0.0.1:8080".to_string(),
                    weight: 2,
                }],
            }],
            ..Default::default()
        };

        let res = materialize_nginx(&spec, &policy_dir, &routing_dir)
            .await
            .expect("materialize");
        assert!(res.nginx_changed);

        assert!(policy_dir.join("active-policy.json").exists());
        assert!(policy_dir.join("active-access.json").exists());
        assert!(policy_dir.join("active-upstreams.conf").exists());
        assert!(routing_dir.join("active-domain-routing.conf").exists());

        let up_conf = tokio::fs::read_to_string(policy_dir.join("active-upstreams.conf"))
            .await
            .unwrap();
        assert!(up_conf.contains("upstream backend"));
        assert!(up_conf.contains("server 127.0.0.1:8080 weight=2;"));

        // Second run with same spec should NOT report changed
        let res2 = materialize_nginx(&spec, &policy_dir, &routing_dir)
            .await
            .expect("materialize 2");
        assert!(!res2.nginx_changed);
    }
}
