-- Migration 0004: Initial seed data in the system

-- Seed policy cluster release namespace sequence
INSERT OR IGNORE INTO sqlite_sequence(name, seq) VALUES('policy_cluster_releases', 1000000000000);

-- Seed default admin user (admin / admin) with Argon2id hash
INSERT OR IGNORE INTO users (id, username, password_hash, salt, role)
VALUES (
    'usr_admin_01',
    'admin',
    '1d13da93081c129149944f1d42952958efc9919908d29e71756ed8ab2ebf8f4e',
    '7e88c0a969f6e52c',
    'admin'
);

-- Seed system settings
INSERT OR IGNORE INTO system_settings (key, value) VALUES
    ('metrics_mode', 'disabled'),
    ('prometheus_url', 'http://127.0.0.1:9090'),
    ('prometheus_job', 'aurora-waf-nodes');

-- Seed default authentication providers (Local enabled by default)
INSERT OR IGNORE INTO auth_providers (id, name, description, enabled, config_json) VALUES
('local', 'Local Database Accounts', 'Authenticate users via local Aurora WAF password store with Argon2id hashing.', 1, '{"password_min_length":8,"require_uppercase":true,"require_number":true}'),
('oidc', 'OIDC / OAuth 2.0 (SSO)', 'Federated Single Sign-On with Google Workspace, Keycloak, Okta, or Entra ID.', 0, '{"issuer_url":"https://accounts.google.com","client_id":"","client_secret":"","redirect_url":"https://waf.local/api/v1/auth/callback/oidc"}'),
('ldap', 'LDAP / Active Directory', 'Corporate centralized identity directory query over secure LDAPS / STARTTLS.', 0, '{"server":"ldap.company.internal","port":636,"use_ssl":true,"bind_dn":"cn=readonly,dc=company,dc=internal","bind_password":"","base_dn":"ou=users,dc=company,dc=internal","user_filter":"(uid=%s)","group_filter":"(memberUid=%s)"}'),
('saml', 'SAML 2.0 Enterprise', 'Security Assertion Markup Language federated integration for corporate IdPs.', 0, '{"idp_metadata_url":"https://idp.company.internal/metadata.xml","entity_id":"urn:aurora:waf:saml","sso_url":"https://idp.company.internal/sso/login"}');

-- Seed default notification channels
INSERT OR IGNORE INTO notification_channels (id, name, description, enabled, config_json) VALUES
('email', 'Email (SMTP)', 'Deliver incident security alerts, daily digest reports, and node health notices via SMTP mail server.', 1, '{"host":"smtp.mailgun.org","port":587,"encryption":"STARTTLS","username":"alerts@mg.aurora-waf.io","password":"","from_address":"alerts@aurora-waf.io","to_addresses":"secops@company.com"}'),
('slack', 'Slack Incoming Webhook', 'Stream real-time incident notifications, threat bursts, and node failover alerts to a designated Slack channel.', 1, '{"webhook_url":"https://example.com/slack-webhook-placeholder","channel":"#waf-alerts","username":"Aurora WAF Bot","mention_critical":true}'),
('telegram', 'Telegram Bot', 'Push direct alerts or group channel messages using an official Telegram bot token and chat target.', 0, '{"bot_token":"","chat_id":"","thread_id":"","parse_mode":"HTML"}'),
('discord', 'Discord Webhook', 'Forward attack blocks and system lifecycle events directly to Discord channels via rich embedded cards.', 0, '{"webhook_url":"","bot_name":"Aurora Guardian","avatar_url":""}'),
('webhook', 'Custom HTTP Webhook', 'Send signed JSON payloads via HTTP POST to SIEM (Splunk, Elastic, Datadog) or custom internal ingestion endpoints.', 0, '{"endpoint_url":"https://siem.internal.corp/events/waf","method":"POST","headers":"Authorization: Bearer placeholder-siem-token\\nX-Source: aurora-waf","secret_token":"","skip_tls_verify":false}'),
('pagerduty', 'PagerDuty & Opsgenie', 'Trigger urgent on-call responder paging and high-severity incident escalation via Events API v2.', 0, '{"routing_key":"","severity":"critical","auto_resolve":true}');

-- Seed default notification trigger rules
INSERT OR IGNORE INTO notification_rules (id, name, description, severity, enabled) VALUES
('rule_critical_threats', 'Critical Threat & Exploit Bursts', 'Triggers on confirmed SQL Injection, Remote Code Execution, and Zero-day path traversal blocks.', 'critical', 1),
('rule_node_offline', 'Node Health & Cluster Degradation', 'Triggers immediately when a data plane node fails heartbeat checks or drops offline.', 'critical', 1),
('rule_ddos_spikes', 'Rate Limiting & DDoS Throttling Spikes', 'Triggers when requests exceed threshold burst rates or IP blacklist enforcement kicks in.', 'high', 1),
('rule_cert_expiry', 'SSL/TLS Certificate Expiration Warning', 'Triggers 30 days and 7 days prior to HTTPS domain certificate expiration.', 'medium', 1),
('rule_config_changes', 'Audit & Security Administrative Events', 'Notifies when WAF rule sets are published, 2FA status changes, or admin credentials update.', 'low', 0);

-- Seed default backup settings singleton record
INSERT OR IGNORE INTO backup_settings (
    id, auto_backup_enabled, cron_expression, s3_enabled, s3_endpoint, s3_bucket, s3_region,
    s3_access_key, s3_secret_key, s3_prefix, s3_retention_days, last_backup_at, last_backup_status, last_backup_destination
) VALUES (
    1, 1, '0 2 * * *', 0, 'https://s3.ap-southeast-1.amazonaws.com', 'aurora-waf-backups', 'ap-southeast-1',
    '', '', 'backups/', 30, '', 'none', 'local'
);

-- Seed default extensions catalog (115 plugins across 11 groups)
INSERT OR IGNORE INTO extensions (id, name, category, description, enabled, config_json) VALUES
-- 1. Security Engine (15)
('waf-core', 'WAF Core Inspection Engine', 'security_engine', 'Core Layer 7 request inspection, anomaly scoring, and enforcement engine.', 1, '{"enabled":true,"mode":"enforce","anomaly_threshold":5,"paranoia_level":1,"block_status":403,"max_body_inspection_size_kb":128,"inspect_query_params":true,"inspect_request_headers":true,"inspect_request_body":true,"inspect_response_body":false}'),
('sqli-protection', 'SQL Injection Protection', 'security_engine', 'Deep token analysis preventing classic, boolean, error-based, and stacked SQLi attacks.', 1, '{"enabled":true,"sensitivity":"high","detect_blind":true,"detect_stacked":true,"detect_time_based":true,"detect_union_select":true,"inspect_cookies":true,"allowed_sql_keywords":["SELECT","FROM"],"action":"block"}'),
('xss-protection', 'Cross-Site Scripting (XSS) Shield', 'security_engine', 'Script tag, inline event, and DOM-based XSS payload sanitization and blocking.', 1, '{"enabled":true,"strip_tags":false,"block_inline_events":true,"inspect_attributes":true,"dom_xss_protection":true,"html_entities_decode":true,"action":"block"}'),
('command-injection-protection', 'OS Command Injection Blocker', 'security_engine', 'Detects shell metacharacters, pipes, backticks, and unauthorized command execution attempts.', 1, '{"enabled":true,"block_pipes":true,"block_backticks":true,"block_subshells":true,"block_system_binaries":true,"inspected_commands":["bash","sh","curl","wget","nc","cat","powershell"],"action":"block"}'),
('path-traversal-protection', 'Directory & Path Traversal Guard', 'security_engine', 'Stops ../, ..%2f, and null-byte directory traversal attacks targeting file system roots.', 1, '{"enabled":true,"strict_uri_decoding":true,"block_null_bytes":true,"max_directory_depth":10,"blocked_patterns":["../","..\\","%2e%2e%2f","%252e%252e%252f"],"action":"block"}'),
('ssrf-protection', 'Server-Side Request Forgery Guard', 'security_engine', 'Restricts outbound fetch URLs and blocks requests targeting cloud metadata and private IP ranges.', 1, '{"enabled":true,"block_private_networks":true,"block_link_local":true,"block_cloud_metadata":true,"blocked_ip_ranges":["10.0.0.0/8","172.16.0.0/12","192.168.0.0/16","169.254.169.254/32","127.0.0.0/8"],"allowed_target_hosts":["api.trusted-partner.com"],"action":"block"}'),
('rce-protection', 'Remote Code Execution Shield', 'security_engine', 'Blocks deserialization exploits, Java/PHP code execution, and OGNL/SpEL injection attacks.', 1, '{"enabled":true,"inspect_deserialization":true,"block_java_gadgets":true,"block_php_serialization":true,"block_ognl_expressions":true,"block_spel_expressions":true,"action":"block"}'),
('protocol-anomaly', 'HTTP Protocol Anomaly Detection', 'security_engine', 'Enforces RFC strict compliance, detects smuggling, bad content-lengths, and malformed headers.', 1, '{"enabled":true,"strict_rfc_headers":true,"block_http_smuggling":true,"max_header_size_kb":32,"max_headers_count":100,"disallow_duplicate_headers":["Content-Length","Host","Transfer-Encoding"],"enforce_uri_length_limit":8192}'),
('bot-detection', 'Automated Bot & Scraper Detection', 'security_engine', 'Identifies headless browsers, automated scrapers, and malicious automation via behavioral fingerprints.', 0, '{"enabled":true,"mode":"challenge","challenge_type":"js","challenge_ttl_seconds":1800,"bypass_verified_bots":true,"verified_bot_categories":["search_engine","uptime_monitor","social_media"],"allow_user_agents":["Googlebot","Bingbot","DuckDuckBot"],"deny_user_agents":["*python-requests*","*curl*","*libwww-perl*","*Scrapy*","*Go-http-client*"],"rate_limit_suspicious":{"enabled":true,"requests_per_minute":60,"action":"captcha"}}'),
('ip-reputation', 'Threat Intelligence & IP Reputation', 'security_engine', 'Dynamic lookup against global threat intelligence feeds, blocklists, and AbuseIPDB scoring.', 0, '{"enabled":true,"min_confidence":80,"cache_ttl_secs":3600,"action":"block","providers":["abuseipdb","alienvault_otx"],"sync_interval_mins":60,"whitelist_cidrs":["127.0.0.1/32"]}'),
('credential-stuffing', 'Credential Stuffing & Brute Force Defense', 'security_engine', 'Tracks failed login velocity per IP and username to mitigate account takeover attacks.', 0, '{"enabled":true,"max_attempts":5,"window_secs":60,"lockout_secs":300,"track_by":"ip_and_username","username_field":"username","target_endpoints":["/api/v1/auth/login","/api/v1/login","/oauth/token"],"action":"block"}'),
('scanner-detection', 'Vulnerability Scanner Fingerprinting', 'security_engine', 'Detects and blocks automated security scanners such as Nikto, Nessus, Acunetix, and sqlmap.', 1, '{"enabled":true,"block_known_scanners":true,"known_scanners":["nikto","sqlmap","nessus","acunetix","nmap","wpscan","zaproxy"],"tar_pit_delay_ms":0,"auto_blacklist_duration_secs":86400}'),
('sensitive-data-detection', 'DLP & Sensitive Data Leak Prevention', 'security_engine', 'Scans outbound response bodies for unmasked credit cards, social security numbers, and private keys.', 0, '{"enabled":true,"mask_credit_cards":true,"mask_ssn":true,"mask_api_keys":true,"mask_jwt_tokens":true,"replacement":"[REDACTED]","inspect_content_types":["application/json","text/plain","text/html"]}'),
('custom-waf-rules', 'Custom Regex & Expression Rules', 'security_engine', 'User-defined declarative rule engine matching paths, headers, query params, and body regex patterns.', 0, '{"enabled":true,"default_action":"pass","rules":[{"id":"block-admin-external","name":"Block external access to internal admin endpoints","field":"uri","operator":"regex_match","pattern":"^/admin/(.*)","action":"block","status":403}]}'),
('owasp-crs', 'OWASP Core Rule Set (CRS v4)', 'security_engine', 'Comprehensive WebAssembly OWASP CRS v4 rule collection covering Top 10 vulnerabilities.', 1, '{"enabled":true,"rule_level":2,"paranoia_level":1,"inbound_anomaly_threshold":5,"outbound_anomaly_threshold":4,"allow_body_inspection":true,"disabled_rule_ids":[920350,942100]}'),

-- 2. Authentication (12)
('basic-auth', 'HTTP Basic Authentication', 'authentication', 'RFC 7617 standard username and password verification with htpasswd / bcrypt support.', 0, '{"enabled":true,"realm":"Restricted Area","hide_credentials":true,"users":[{"username":"api_admin","password_hash":"$2a$12$e8Mr8G7n3pU0yN4p567890abcdefghijklmnopqrstuv"}]}'),
('key-auth', 'API Key Header & Query Validator', 'authentication', 'Fast verification of static or rotating API keys against secure registry.', 0, '{"enabled":true,"header_names":["X-API-Key","apikey"],"query_param_names":["api_key"],"hide_credentials":true,"keys":[{"key":"ak_live_a1b2c3d4e5f67890","client_id":"mobile_app_prod","rate_limit_tier":"tier_standard"}]}'),
('jwt-auth', 'JSON Web Token (JWT) Verifier', 'authentication', 'Cryptographic signature validation for RS256/HS256/ES256 tokens with JWKS endpoint support.', 0, '{"enabled":true,"header_name":"Authorization","header_prefix":"Bearer","cookie_name":"access_token","jwks_url":"https://auth.example.com/.well-known/jwks.json","issuer":"https://auth.example.com/","audience":"https://api.example.com","algorithms":["RS256","ES256"],"verify_expiry":true,"claims_to_verify":{"iss":"https://auth.example.com/"},"forward_claims":["sub","email","roles"]}'),
('hmac-auth', 'HMAC Request Signature Authentication', 'authentication', 'Validates SHA-256 HMAC message authentication codes on sensitive webhook payloads.', 0, '{"enabled":true,"header_name":"X-HMAC-Signature","algorithm":"sha256","secret":"your_hmac_shared_secret_key_32_chars","clock_skew_seconds":300,"signed_headers":["date","host","content-type","digest"]}'),
('oauth2-auth', 'OAuth 2.0 Authorization Server Guard', 'authentication', 'Enforces Authorization Code and Client Credentials flows with token introspection.', 0, '{"enabled":true,"introspection_endpoint":"https://auth.example.com/oauth/v2/introspect","client_id":"gateway_client_id","client_secret":"gateway_client_secret","token_type_hint":"access_token","cache_tokens":true,"cache_ttl_secs":300,"scopes_required":["read","write"]}'),
('openid-connect', 'OpenID Connect (OIDC) Single Sign-On', 'authentication', 'Seamless user identity federation via Keycloak, Okta, Auth0, or Google Identity.', 0, '{"enabled":true,"discovery_url":"https://accounts.google.com/.well-known/openid-configuration","client_id":"oauth_client_id.apps.googleusercontent.com","client_secret":"oauth_client_secret","redirect_uri":"/callback","scopes":["openid","profile","email"],"session_cookie_name":"aurora_oidc_session","bearer_only":false}'),
('mtls-auth', 'Mutual TLS (mTLS) Client Verification', 'authentication', 'Zero-trust mutual certificate validation with Subject Alternative Name (SAN) verification.', 0, '{"enabled":true,"ca_cert":"-----BEGIN CERTIFICATE-----\nMIIDXTCCAkWgAwIBAgIJAL9...\n-----END CERTIFICATE-----","verify_depth":3,"require_client_cert":true,"allowed_common_names":["*.internal.corp","client-node-01"],"san_dns_match":["internal.corp"]}'),
('ldap-auth', 'LDAP & Active Directory Directory Auth', 'authentication', 'Enterprise directory service authentication via LDAP/LDAPS queries.', 0, '{"enabled":true,"server":"ldaps://ldap.example.com:636","base_dn":"ou=users,dc=example,dc=org","bind_dn":"cn=admin,dc=example,dc=org","bind_password":"ldap_admin_secret","attribute":"sAMAccountName","start_tls":true,"verify_ldap_cert":true}'),
('saml-auth', 'SAML 2.0 Enterprise Identity Federation', 'authentication', 'SP-initiated and IdP-initiated SAML assertions for enterprise single sign-on.', 0, '{"enabled":true,"idp_metadata_url":"https://idp.example.com/app/exk123/sso/saml/metadata","sp_entity_id":"https://api.gateway.example.com","assertion_consumer_url":"/saml/acs","nameid_format":"urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"}'),
('forward-auth', 'Forward Auth Delegated Service', 'authentication', 'Delegates request authentication decisions to an external HTTP authentication microservice.', 0, '{"enabled":true,"auth_url":"http://127.0.0.1:9000/api/v1/verify","request_method":"GET","request_headers":["Authorization","Cookie","X-Forwarded-For"],"response_headers_to_forward":["X-User-Id","X-User-Email","X-User-Roles"],"timeout_ms":2000}'),
('session-auth', 'Server-Side Session State & Cookie Auth', 'authentication', 'Cryptographic session cookie parsing backed by high-speed Redis session store.', 0, '{"enabled":true,"cookie_name":"aurora_session","redis_url":"redis://127.0.0.1:6379/1","ttl_secs":86400,"sliding_expiration":true,"secure_cookie":true,"same_site":"Lax"}'),
('multi-auth', 'Multi-Factor & Chained Auth Strategy', 'authentication', 'Orchestrates sequential or fallback authentication policies with MFA step-up verification.', 0, '{"enabled":true,"mode":"any","strategies":["jwt-auth","key-auth"],"error_response_status":401}'),

-- 3. Authorization & Security (12)
('acl', 'Access Control List (ACL) Engine', 'authorization_security', 'Route and method-level access control permissions by consumer identity and group membership.', 0, '{"enabled":true,"whitelist":["developers","admins","internal-services"],"blacklist":["banned-users","suspended-accounts"],"hide_consumer_header":true}'),
('rbac', 'Role-Based Access Control (RBAC)', 'authorization_security', 'Fine-grained hierarchical role assignment and permission scoping for API endpoints.', 0, '{"enabled":true,"default_role":"guest","roles":{"admin":["read:*","write:*","delete:*"],"member":["read:public","write:comments"],"guest":["read:public"]},"role_claim_path":"roles"}'),
('opa-authz', 'Open Policy Agent (OPA) Evaluation', 'authorization_security', 'Decoupled authorization decision engine querying OPA servers or embedded Rego policies.', 0, '{"enabled":true,"opa_url":"http://127.0.0.1:8181/v1/data/http/authz","policy_path":"http.authz.allow","include_request_body":false,"timeout_ms":500,"allow_status_code":200,"deny_status_code":403}'),
('ip-restriction', 'IP CIDR Whitelist & Blacklist', 'authorization_security', 'High-speed radix tree IP filtering allowing or denying individual IPs and CIDR subnets.', 0, '{"enabled":true,"whitelist":["10.0.0.0/8","192.168.1.0/24"],"blacklist":["0.0.0.0/8","100.64.0.0/10"],"status_code":403,"message":"Access restricted by client IP policy"}'),
('geo-restriction', 'GeoIP Geographic Fencing', 'authorization_security', 'Country, city, and ASN-based geofencing using MaxMind GeoIP2 country database.', 0, '{"enabled":true,"database_path":"/var/lib/aurora/GeoLite2-City.mmdb","block_countries":["KP","IR"],"allow_countries":["VN","US","SG","JP"],"block_action":"deny","status_code":403}'),
('user-agent-restriction', 'User-Agent Filtering & Scraper Block', 'authorization_security', 'Filters or blocks requests by User-Agent header matching known bad signatures or missing values.', 0, '{"enabled":true,"block_empty":true,"blocked_patterns":["*sqlmap*","*nikto*","*curl*","*wget*","*python*"],"whitelist_patterns":["*Googlebot*","*AuroraHealthCheck*"],"status_code":403}'),
('referer-restriction', 'Referer Validation & Anti-Hotlinking', 'authorization_security', 'Verifies HTTP Referer headers to prevent image hotlinking and unauthorized iframe embeds.', 0, '{"enabled":true,"allow_empty":true,"allowed_domains":["*.example.com","example.com","partner.io"],"blocked_domains":["*.bad-hotlinking-site.com"],"block_action":"forbidden"}'),
('cors', 'Cross-Origin Resource Sharing (CORS)', 'authorization_security', 'Configures CORS headers, allowed origins, methods, credentials, and handles preflight OPTIONS.', 0, '{"enabled":true,"allow_origins":["https://example.com","https://app.example.com"],"allow_methods":["GET","POST","PUT","DELETE","PATCH","OPTIONS"],"allow_headers":["Authorization","Content-Type","X-API-Key","X-Request-ID"],"expose_headers":["X-Total-Count","Content-Disposition"],"allow_credentials":true,"max_age":86400}'),
('csrf-protection', 'Cross-Site Request Forgery (CSRF) Guard', 'authorization_security', 'Enforces Double Submit Cookie patterns and custom verification tokens on mutating HTTP methods.', 0, '{"enabled":true,"cookie_name":"aurora_csrf","header_name":"X-CSRF-Token","token_ttl_secs":7200,"safe_methods":["GET","HEAD","OPTIONS"],"same_site":"Strict","secure":true}'),
('api-schema-validator', 'OpenAPI & JSON Schema Validator', 'authorization_security', 'Validates incoming request headers, query params, and JSON bodies against OpenAPI 3.0 schemas.', 0, '{"enabled":true,"schema_url":"https://api.example.com/openapi.json","validate_request_body":true,"validate_query_parameters":true,"validate_responses":false,"rejection_status":400}'),
('request-signature', 'Cryptographic Request Signature (SigV4)', 'authorization_security', 'AWS SigV4 and custom HMAC request signing to verify payload integrity and prevent tampering.', 0, '{"enabled":true,"service_name":"execute-api","region":"us-east-1","signature_version":"v4","key_id":"AKIAIOSFODNN7EXAMPLE","secret_key":"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY","clock_tolerance_secs":300}'),
('consumer-restriction', 'Consumer Route & Tier Gating', 'authorization_security', 'Restricts specific consumers to authorized routing tiers, environments, or API subscription plans.', 0, '{"enabled":true,"allowed_consumers":["mobile-app","web-dashboard","enterprise-partner"],"tier_requirements":{"/api/v1/pro/*":["pro","enterprise"],"/api/v1/enterprise/*":["enterprise"]}}'),

-- 4. Traffic Control (14)
('rate-limit', 'Standard Token Bucket Rate Limiter', 'traffic_control', 'Enforces per-second or per-minute request rate limits with configurable burst allowance.', 0, '{"enabled":true,"rate":100,"burst":200,"period_secs":1,"limit_by":"ip","rejected_code":429,"rejected_message":"Too Many Requests"}'),
('rate-limit-local', 'Ultra-Fast Local Worker Rate Limiter', 'traffic_control', 'Lock-free worker-local memory rate limiting delivering sub-microsecond latency checks.', 0, '{"enabled":true,"capacity":1000,"refill_rate":100,"key":"remote_addr","rejected_code":429}'),
('rate-limit-distributed', 'Cluster-Wide Distributed Rate Limiter', 'traffic_control', 'Redis-backed synchronized sliding window rate limiting across all edge nodes.', 0, '{"enabled":true,"redis_url":"redis://127.0.0.1:6379/0","limit":1000,"window_secs":60,"key_type":"ip","sync_interval_ms":100,"rejected_code":429}'),
('connection-limit', 'Concurrent Connection Concurrency Limiter', 'traffic_control', 'Limits simultaneous active TCP connections per client IP to mitigate slowloris attacks.', 0, '{"enabled":true,"max_connections_per_ip":50,"burst":10,"rejected_code":503}'),
('bandwidth-limit', 'Bandwidth Shaping & Download Throttling', 'traffic_control', 'Throttles maximum byte transfer rates per second for downloads and large uploads.', 0, '{"enabled":true,"rate_kb_per_sec":1024,"burst_kb":2048,"limit_by":"ip"}'),
('request-size-limit', 'HTTP Payload & Body Size Limiter', 'traffic_control', 'Drops oversized payloads before proxy buffering to prevent memory exhaustion and DoS.', 0, '{"enabled":true,"max_body_bytes":10485760,"response_status":413,"response_message":"Payload Too Large"}'),
('traffic-split', 'Multi-Upstream Traffic Splitter', 'traffic_control', 'Splits live production traffic across multiple backend clusters by configurable percentages.', 0, '{"enabled":true,"splits":[{"upstream":"backend_v1","weight":90},{"upstream":"backend_v2","weight":10}]}'),
('canary-release', 'Canary Rollout & Cohort Shifting', 'traffic_control', 'Routes selected percentage or header/cookie matching users to canary backend instances.', 0, '{"enabled":true,"canary_upstream":"app_canary","weight_percentage":10,"cookie_override":"canary_user","header_override":"X-Canary","header_values":["always","beta"]}'),
('blue-green', 'Blue-Green Instant Deployment Switch', 'traffic_control', 'Zero-downtime routing switch between blue and green production upstream environments.', 0, '{"enabled":true,"active_slot":"blue","blue_upstream":"app_blue","green_upstream":"app_green","switch_header":"X-Deploy-Slot"}'),
('request-mirror', 'Asynchronous Request Mirroring', 'traffic_control', 'Mirrors real client traffic asynchronously to shadow staging backends without affecting client latency.', 0, '{"enabled":true,"mirror_upstream":"shadow_backend","sample_percentage":100,"ignore_mirror_errors":true}'),
('traffic-shadow', 'Dark Traffic Shadow & Replay Engine', 'traffic_control', 'Replays recorded or live traffic against new upstream versions to validate performance under load.', 0, '{"enabled":true,"replay_upstream":"testing_backend","ignore_responses":true,"sample_rate":0.1}'),
('priority-routing', 'VIP Traffic Prioritization & Queuing', 'traffic_control', 'Prioritizes premium enterprise traffic during peak traffic spikes while queuing bulk requests.', 0, '{"enabled":true,"header_name":"X-Customer-Tier","high_priority_values":["enterprise","vip"],"low_priority_queue_capacity":500,"timeout_ms":3000}'),
('maintenance-mode', 'Graceful Maintenance Mode & Bypass', 'traffic_control', 'Instantly serves custom maintenance pages with secure bypass headers or IP whitelist for operators.', 0, '{"enabled":false,"status_code":503,"bypass_header":"X-Maintenance-Bypass","retry_after_secs":300,"message":"Service undergoing planned maintenance. Please retry in a few moments."}'),
('request-termination', 'Early Request Termination & Mock', 'traffic_control', 'Short-circuits matching routes immediately, returning custom HTTP status, headers, and payload.', 0, '{"enabled":true,"status_code":200,"body":"{\"status\":\"mocked\",\"message\":\"Early terminated by gateway policy\"}","headers":{"Content-Type":"application/json","X-Mock-Source":"Aurora-Gateway"}}'),

-- 5. Request Transformation (10)
('request-header-transform', 'Request Header Mutation', 'request_transformation', 'Appends, modifies, or removes incoming HTTP headers before upstream forwarding.', 0, '{"enabled":true,"add_headers":{"X-Forwarded-By":"Aurora-API-Gateway","X-Gateway-Env":"production"},"remove_headers":["X-Internal-Token","X-Powered-By"]}'),
('request-query-transform', 'URL Query Parameter Transformer', 'request_transformation', 'Adds, strips, or renames URL query parameters to normalize upstream requests.', 0, '{"enabled":true,"add_params":{"ref":"aurora_gateway","version":"v1"},"remove_params":["debug","internal_token","trace_bypass"]}'),
('request-body-transform', 'Request Body Template Transformation', 'request_transformation', 'Modifies JSON request body structures and adds default payload attributes.', 0, '{"enabled":true,"content_type":"application/json","add_fields":{"injected_by":"gateway","region":"ap-southeast-1"},"remove_fields":["deprecated_param","internal_secret"]}'),
('uri-rewrite', 'URI Path Normalization & Regex Rewrite', 'request_transformation', 'Powerful regular expression path rewriting, stripping prefixes and restructuring routes.', 0, '{"enabled":true,"rules":[{"pattern":"^/api/v1/(.*)","replacement":"/v2/$1"}]}'),
('host-rewrite', 'Host Header Rewrite & SNI Override', 'request_transformation', 'Dynamically overrides the HTTP Host header and TLS SNI for upstream virtual hosts.', 0, '{"enabled":true,"override_host":"internal.origin.local","override_sni":true,"preserve_original_host_header":"X-Forwarded-Host"}'),
('method-rewrite', 'HTTP Method Override', 'request_transformation', 'Maps or rewrites HTTP verbs (e.g. POST to PUT or tunneling via X-HTTP-Method-Override).', 0, '{"enabled":true,"allow_header_override":true,"override_header_name":"X-HTTP-Method-Override","map":{"PATCH":"POST"}}'),
('json-transform', 'Advanced JSON Structure Mutator', 'request_transformation', 'JSLT and jq-like structural transformation and field mapping for JSON payloads.', 0, '{"enabled":true,"expression":".data | { id: .user_id, name: .display_name, email: .email_address }","fail_on_empty":false}'),
('xml-json-transform', 'Bidirectional XML / JSON Converter', 'request_transformation', 'Converts incoming legacy XML payloads to JSON and JSON responses back to XML.', 0, '{"enabled":true,"direction":"xml_to_json","root_element":"request","strip_namespaces":true}'),
('grpc-transcode', 'HTTP/JSON to gRPC Transcoder', 'request_transformation', 'Automatically transcodes incoming RESTful HTTP/JSON requests into gRPC Protobuf calls.', 0, '{"enabled":true,"proto_descriptor":"/var/lib/aurora/protos/services.desc","services":["user.v1.UserService","order.v1.OrderService"],"print_options":{"add_whitespace":true,"always_print_primitive_fields":true}}'),
('graphql-rest-transform', 'GraphQL Query to REST Adapter', 'request_transformation', 'Translates REST API endpoints into corresponding upstream GraphQL queries.', 0, '{"enabled":true,"graphql_endpoint":"http://127.0.0.1:4000/graphql","query_template":"query GetUser($id: ID!) { user(id: $id) { id name email } }","variables_mapping":{"id":"params.id"}}'),

-- 6. Response Transformation (8)
('response-header-transform', 'Security Headers & Response Mutator', 'response_transformation', 'Injects HSTS, CSP, X-Frame-Options headers and removes upstream identifying signatures.', 0, '{"enabled":true,"add_headers":{"X-Frame-Options":"DENY","Strict-Transport-Security":"max-age=31536000; includeSubDomains","X-Content-Type-Options":"nosniff","Referrer-Policy":"strict-origin-when-cross-origin"},"remove_headers":["Server","X-Powered-By","X-AspNet-Version"]}'),
('response-body-transform', 'Response Body String Replacer', 'response_transformation', 'Performs real-time string replacement and dynamic script injection in downstream responses.', 0, '{"enabled":true,"replacements":[{"find":"http://api.internal.local","replace":"https://api.example.com"}]}'),
('response-rewrite', 'Status Code & Response Body Overrider', 'response_transformation', 'Rewrites upstream response status codes and body contents conditionally.', 0, '{"enabled":true,"status_code_map":{"502":503},"override_body_on_status":{"503":"{\"code\":\"SERVICE_UNAVAILABLE\",\"message\":\"The upstream server is temporarily restarting.\"}"}}'),
('response-mask', 'PII Redaction & Credit Card Masking', 'response_transformation', 'Scans and masks credit card numbers, passwords, and sensitive PII from outbound responses.', 0, '{"enabled":true,"mask_credit_cards":true,"mask_emails":true,"mask_phone_numbers":true,"replacement":"[CONFIDENTIAL]"}'),
('json-filter', 'JSON Response Field Filter', 'response_transformation', 'Filters out restricted JSON response fields based on client scope or query parameters.', 0, '{"enabled":true,"excluded_fields":["internal_notes","hashed_password","salary","ssn"],"allowed_scopes":{"admin":["*"],"user":["public_*"]}}'),
('compression-gzip', 'Dynamic Gzip RFC 1952 Compression', 'response_transformation', 'Compresses text, JSON, and web assets using Gzip to optimize network egress.', 0, '{"enabled":true,"level":6,"min_length":1024,"types":["text/html","application/json","application/javascript","text/css","application/xml"]}'),
('compression-brotli', 'High-Ratio Brotli RFC 7932 Compression', 'response_transformation', 'Superior compression ratio Brotli encoding for web assets and API payloads.', 0, '{"enabled":true,"quality":6,"min_length":1024,"types":["text/html","application/json","application/javascript","text/css","application/xml"]}'),
('error-transform', 'RFC 7807 Problem Details Error Formatter', 'response_transformation', 'Normalizes inconsistent upstream 4xx/5xx errors into standardized RFC 7807 Problem Details.', 0, '{"enabled":true,"type_uri_base":"https://api.example.com/errors/","include_debug_info":false,"rfc7807_standard":true}'),

-- 7. Observability (12)
('metrics', 'Prometheus & OTLP Telemetry (Core)', 'observability', 'Exposes Prometheus pull metrics endpoint on port 9145 with NGINX status scraping and OTLP push.', 1, '{"enabled":true,"port":9145,"stub_status_url":"http://127.0.0.1:80/stub_status","prometheus":{"enabled":true,"path":"/metrics"},"otlp":{"enabled":false,"endpoint":"http://127.0.0.1:4317","interval_secs":15}}'),
('prometheus', 'Prometheus Metrics & Exporter', 'observability', 'Exposes Prometheus pull metrics endpoint on port 9145 with NGINX status scraping and OTLP push.', 1, '{"enabled":true,"port":9145,"stub_status_url":"http://127.0.0.1:80/stub_status","prometheus":{"enabled":true,"path":"/metrics"},"otlp":{"enabled":false,"endpoint":"","interval_secs":15}}'),
('opentelemetry', 'OpenTelemetry Distributed Tracing', 'observability', 'W3C TraceContext propagation and OTel exporter to Jaeger, Tempo, and Honeycomb.', 0, '{"enabled":true,"endpoint":"http://127.0.0.1:4317","protocol":"grpc","service_name":"aurora-gateway","sampling_rate":0.05,"propagation_format":"w3c"}'),
('zipkin', 'Zipkin B3 Distributed Tracing', 'observability', 'Injects B3 propagation headers and exports trace spans to Zipkin collector.', 0, '{"enabled":true,"endpoint":"http://127.0.0.1:9411/api/v2/spans","sample_rate":0.1,"b3_header_propagation":true}'),
('datadog', 'Datadog APM & StatsD Exporter', 'observability', 'Emits low-latency DogStatsD metrics and tracing envelopes to Datadog agent daemon.', 0, '{"enabled":true,"statsd_host":"127.0.0.1","statsd_port":8125,"sample_rate":1,"tags":["env:production","service:aurora-gateway","cluster:primary"]}'),
('access-log', 'Zero-Copy Structured JSON Access Log', 'observability', 'High-throughput structured access logging with custom fields and zero-copy ring buffers.', 0, '{"enabled":true,"format":"json","output":"/var/log/aurora/access.log","buffer_size":1024,"flush_interval_ms":500,"include_headers":["Host","User-Agent","X-Request-ID"]}'),
('http-logger', 'HTTP REST Log Emitter', 'observability', 'Streams request and response log envelopes over HTTP POST to centralized logging collectors.', 0, '{"enabled":true,"endpoint":"http://127.0.0.1:8088/logs","method":"POST","batch_size":100,"flush_interval_secs":5,"timeout_ms":3000}'),
('syslog-logger', 'RFC 5424 Syslog Log Streamer', 'observability', 'Emits RFC 5424 compliant log messages over UDP, TCP, or TLS to Syslog collectors.', 0, '{"enabled":true,"host":"127.0.0.1","port":514,"facility":"local0","protocol":"udp","tag":"aurora-gateway"}'),
('kafka-logger', 'Apache Kafka Access Event Producer', 'observability', 'High-throughput real-time streaming of access events directly to Kafka topics.', 0, '{"enabled":true,"brokers":["127.0.0.1:9092"],"topic":"aurora-access-logs","compression":"gzip","producer_acks":"all"}'),
('loki-logger', 'Grafana Loki Log Exporter', 'observability', 'Pushes structured stream logs directly to Grafana Loki HTTP push API.', 0, '{"enabled":true,"endpoint":"http://127.0.0.1:3100/loki/api/v1/push","tenant_id":"tenant_prod","labels":{"job":"aurora-api-gateway","env":"production"}}'),
('elasticsearch-logger', 'Elasticsearch & OpenSearch Bulk Indexer', 'observability', 'Direct bulk indexing of HTTP request records into Elasticsearch or OpenSearch clusters.', 0, '{"enabled":true,"endpoint":"http://127.0.0.1:9200","index":"aurora-logs-%Y.%m.%d","batch_size":200,"auth":{"username":"elastic","password":"changeme"}}'),
('request-id', 'Unique X-Request-ID Injector', 'observability', 'Generates and propagates UUIDv4 or Snowflake unique trace IDs across upstream hops.', 0, '{"enabled":true,"header_name":"X-Request-ID","generate_if_missing":true,"format":"uuid4","preserve_incoming":true}'),
('audit-log', 'Tamper-Proof Admin Audit Trail', 'observability', 'Logs all configuration mutations and administrative actions into an immutable audit stream.', 1, '{"enabled":true,"output":"/var/log/aurora/audit.log","hash_chain":true,"log_mutations_only":true}'),

-- 8. Resilience & Upstream (10)
('circuit-breaker', 'Automated Upstream Circuit Breaker', 'resilience_upstream', 'Trips failing upstream endpoints and isolates unhealthy nodes during cascading failures.', 0, '{"enabled":true,"error_threshold_percentage":50,"minimum_requests":20,"recovery_timeout_secs":30,"half_open_success_threshold":5}'),
('retry-policy', 'Exponential Backoff Retry Engine', 'resilience_upstream', 'Automatically retries idempotent requests on upstream 502, 503, and 504 network errors.', 0, '{"enabled":true,"retries":3,"backoff_base_ms":100,"max_backoff_ms":1000,"retry_on":["http_502","http_503","http_504","connect_failure"]}'),
('timeout-policy', 'Strict Connection & Read Timeouts', 'resilience_upstream', 'Enforces connect, read, and write timeout limits to eliminate resource leakage.', 0, '{"enabled":true,"connect_timeout_ms":2000,"read_timeout_ms":10000,"write_timeout_ms":10000}'),
('outlier-detection', 'Consecutive Error Outlier Detection', 'resilience_upstream', 'Identifies and ejects anomalous high-error upstream servers from active load balancing.', 0, '{"enabled":true,"consecutive_5xx":5,"ejection_duration_secs":30,"max_ejection_percent":50,"enforce_interval_secs":10}'),
('active-health-check', 'Synthetic Probe Active Health Checking', 'resilience_upstream', 'Periodically sends synthetic HTTP GET or gRPC health checks to verify upstream health.', 0, '{"enabled":true,"path":"/healthz","interval_secs":10,"timeout_secs":2,"healthy_threshold":2,"unhealthy_threshold":3,"expected_statuses":[200,204]}'),
('passive-health-check', 'Live Traffic Passive Health Checking', 'resilience_upstream', 'Monitors live request failures and dynamically marks unhealthy origins as down.', 0, '{"enabled":true,"max_fails":3,"fail_timeout_secs":10,"unhealthy_statuses":[500,502,503,504]}'),
('fallback-upstream', 'Disaster Recovery Fallback Origin', 'resilience_upstream', 'Automatically redirects traffic to a designated fallback backup origin if main cluster fails.', 0, '{"enabled":true,"primary_upstream":"backend_primary","fallback_upstream":"backend_dr","trigger_on_status":[500,502,503,504]}'),
('hedged-request', 'Speculative Hedged Requests', 'resilience_upstream', 'Sends speculative duplicate requests to cut p99 tail latency in critical microservices.', 0, '{"enabled":true,"hedged_delay_ms":150,"max_hedged_attempts":2}'),
('upstream-affinity', 'Session Affinity & Sticky Cookie', 'resilience_upstream', 'Pins client sessions to specific upstream servers using cookies or consistent IP hashing.', 0, '{"enabled":true,"cookie_name":"AURORA_STICKY","ttl_secs":3600,"hash_strategy":"ip_hash","failover":"next_node"}'),
('adaptive-concurrency', 'Gradient Adaptive Concurrency Control', 'resilience_upstream', 'Dynamically adjusts maximum concurrent requests based on measured latency gradients.', 0, '{"enabled":true,"min_concurrency":10,"max_concurrency":1000,"target_rtt_ms":50,"gradient_smoothing":0.2}'),

-- 9. Cache & Content (8)
('proxy-cache', 'Edge Memory & Disk HTTP Proxy Cache', 'cache_content', 'Caches GET/HEAD responses with RFC-compliant Cache-Control and stale-while-revalidate.', 0, '{"enabled":true,"cache_size_mb":512,"default_ttl_secs":60,"stale_while_revalidate":true,"methods":["GET","HEAD"],"cache_key":"$scheme$request_method$host$request_uri"}'),
('redis-cache', 'Distributed Redis Microservice Cache', 'cache_content', 'Shared distributed caching across all WAF nodes using Redis key-value store.', 0, '{"enabled":true,"redis_url":"redis://127.0.0.1:6379/2","default_ttl_secs":300,"key_prefix":"aurora:cache:","compress_payloads":true}'),
('cache-purge', 'Instant Cache Invalidation API', 'cache_content', 'Provides instant cache eviction by URL or wildcard tag via HTTP PURGE requests.', 0, '{"enabled":true,"allowed_ips":["127.0.0.1","10.0.0.0/8"],"purge_key_header":"X-Purge-Key","purge_method":"PURGE"}'),
('etag', 'Dynamic Strong & Weak ETag Generator', 'cache_content', 'Computes SHA-256 ETags and handles 304 Not Modified conditional validation.', 0, '{"enabled":true,"weak":true,"algorithm":"sha256"}'),
('conditional-request', 'Conditional Request Evaluator', 'cache_content', 'Validates If-Match, If-None-Match, If-Modified-Since headers to optimize network transit.', 0, '{"enabled":true,"evaluate_if_match":true,"evaluate_if_none_match":true,"evaluate_if_modified_since":true}'),
('static-response', 'Static File & Mock JSON Server', 'cache_content', 'Directly serves static HTML, CSS, or mock JSON responses without contacting upstreams.', 0, '{"enabled":true,"root_dir":"/var/www/static","autoindex":false,"index_files":["index.html","index.htm"]}'),
('mock-response', 'Parameter-Aware Mock Response Engine', 'cache_content', 'Returns dynamic mock responses based on request path and parameters for API testing.', 0, '{"enabled":true,"routes":{"/api/v1/mock/ping":{"status":200,"body":"{\"status\":\"ok\",\"service\":\"mock\"}"}}}'),
('response-buffering', 'Smart Response Buffering & Streaming', 'cache_content', 'Configures memory buffer thresholds versus unbuffered real-time SSE streaming.', 0, '{"enabled":true,"buffer_size_kb":64,"disable_for_sse":true,"disable_for_grpc":true}'),

-- 10. Integration & Runtime (8)
('aws-lambda', 'AWS Lambda Serverless Invoker', 'integration_runtime', 'Directly invokes AWS Lambda functions using SigV4 credentials as upstream endpoints.', 0, '{"enabled":true,"region":"us-east-1","function_name":"process-api-request","qualifier":"$LATEST","invocation_type":"RequestResponse","timeout_ms":3000}'),
('azure-functions', 'Azure Functions Serverless Gateway', 'integration_runtime', 'Triggers Azure Serverless Functions and manages authentication headers.', 0, '{"enabled":true,"app_name":"my-azure-function-app","function_name":"handler","auth_code":"secret_azure_function_host_key"}'),
('webhook', 'Event-Driven Webhook Dispatcher', 'integration_runtime', 'Fires asynchronous outbound HTTP webhooks on security alerts and system events.', 0, '{"enabled":true,"url":"https://api.example.com/webhooks/security-alerts","events":["attack_blocked","rate_limit_exceeded","cert_expiring"],"secret":"webhook_signature_secret_key"}'),
('serverless-pre-function', 'Pre-Request Serverless Scripting', 'integration_runtime', 'Executes embedded custom Lua or JavaScript code in the pre-routing request lifecycle.', 0, '{"enabled":true,"runtime":"lua","script":"-- Execute before request routing\nlocal headers = ngx.req.get_headers()\nif not headers[\"X-Custom-Auth\"] then\n  ngx.exit(401)\nend"}'),
('serverless-post-function', 'Post-Request Serverless Scripting', 'integration_runtime', 'Executes embedded custom Lua or JavaScript logic after receiving upstream responses.', 0, '{"enabled":true,"runtime":"lua","script":"-- Execute after receiving upstream response\nngx.header[\"X-Processed-Time\"] = ngx.now()"}'),
('external-plugin', 'External gRPC / IPC Plugin Runtime', 'integration_runtime', 'Extends data plane logic by communicating with external process plugins over Unix sockets.', 0, '{"enabled":true,"socket_path":"/var/run/aurora/plugin.sock","timeout_ms":50,"fail_open":false}'),
('kafka-proxy', 'HTTP to Kafka REST Gateway', 'integration_runtime', 'Ingests REST HTTP POST payloads and publishes them directly into Kafka topics.', 0, '{"enabled":true,"bootstrap_servers":"127.0.0.1:9092","default_topic":"api-events","key_header":"X-Partition-Key"}'),
('mqtt-proxy', 'WebSocket to MQTT IoT Bridge', 'integration_runtime', 'Bridges client WebSocket and HTTP connections to an MQTT message broker for IoT devices.', 0, '{"enabled":true,"broker_url":"tcp://127.0.0.1:1883","client_id":"aurora-gateway-edge","topic_prefix":"telemetry/"}'),

-- 11. AI Gateway (6)
('ai-proxy', 'Unified LLM Provider Proxy', 'ai_gateway', 'Unified API proxy for OpenAI, Anthropic Claude, AWS Bedrock, Google Vertex, and Ollama.', 0, '{"enabled":true,"default_provider":"openai","providers":{"openai":{"base_url":"https://api.openai.com/v1","model":"gpt-4o","api_key":"sk-proj-sample_openai_key_placeholder","timeout_ms":30000},"anthropic":{"base_url":"https://api.anthropic.com/v1","model":"claude-3-5-sonnet-20241022","api_key":"sk-ant-sample_anthropic_key_placeholder","timeout_ms":30000}}}'),
('ai-multi-provider', 'Multi-Provider AI Load Balancer', 'ai_gateway', 'Intelligent load balancing and auto-failover across multiple LLM providers and API keys.', 0, '{"enabled":true,"failover":true,"providers":["openai","anthropic","bedrock"],"retry_count":2,"timeout_ms":30000}'),
('ai-token-rate-limit', 'Token Consumption Rate Limiter', 'ai_gateway', 'Enforces rate limiting based on prompt tokens, completion tokens, and dollar costs.', 0, '{"enabled":true,"tokens_per_minute":60000,"requests_per_minute":500,"cost_limit_usd_per_day":50,"limit_by":"consumer_id"}'),
('ai-prompt-guard', 'Prompt Injection & Jailbreak Defense', 'ai_gateway', 'Real-time heuristic and neural screening blocking adversarial prompt injections.', 0, '{"enabled":true,"detect_jailbreak":true,"detect_pii":true,"detect_prompt_injection":true,"action":"block","rejected_response":"Prompt rejected: adversarial content or policy violation detected"}'),
('ai-semantic-cache', 'Vector Similarity Semantic Cache', 'ai_gateway', 'Caches LLM completions using vector embeddings to eliminate redundant AI generation costs.', 0, '{"enabled":true,"similarity_threshold":0.92,"embedding_model":"text-embedding-3-small","embedding_provider":"openai","ttl_secs":86400,"max_cached_entries":10000}'),
('ai-content-moderation', 'Real-Time AI Content Moderation', 'ai_gateway', 'Detects and redacts sensitive PII, hate speech, and toxic inputs before sending to LLMs.', 0, '{"enabled":true,"block_hate":true,"block_violence":true,"block_sexual":true,"mask_pii":true,"rejection_status":400}');



