syntax = "proto3";

package aurora.sync.v1;

option go_package = "aurora-waf.local/control-plane/internal/transport/grpc/pb;pb";

service DomainRoutingSyncService {
  rpc GetDomainRoutingBundle (GetDomainRoutingBundleRequest) returns (DomainRoutingBundleResponse);
}

message GetDomainRoutingBundleRequest {
  string node_id = 1;
}

message CertificateAsset {
  string name = 1;
  string content = 2;
}

message DomainRoutingBundleResponse {
  string config = 1;
  repeated CertificateAsset files = 2;
  string digest = 3;
}
