// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: sync/v1/access.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessRequest) Reset() {
	*x = GetAccessRequest{}
	mi := &file_sync_v1_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessRequest) ProtoMessage() {}

func (x *GetAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessRequest.ProtoReflect.Descriptor instead.
func (*GetAccessRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_access_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccessRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type AccessSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReleaseId     int64                  `protobuf:"varint,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessSyncResponse) Reset() {
	*x = AccessSyncResponse{}
	mi := &file_sync_v1_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessSyncResponse) ProtoMessage() {}

func (x *AccessSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessSyncResponse.ProtoReflect.Descriptor instead.
func (*AccessSyncResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_access_proto_rawDescGZIP(), []int{1}
}

func (x *AccessSyncResponse) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *AccessSyncResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *AccessSyncResponse) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type ReportAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ReleaseId     int64                  `protobuf:"varint,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAccessRequest) Reset() {
	*x = ReportAccessRequest{}
	mi := &file_sync_v1_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAccessRequest) ProtoMessage() {}

func (x *ReportAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAccessRequest.ProtoReflect.Descriptor instead.
func (*ReportAccessRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_access_proto_rawDescGZIP(), []int{2}
}

func (x *ReportAccessRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportAccessRequest) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *ReportAccessRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ReportAccessRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAccessResponse) Reset() {
	*x = ReportAccessResponse{}
	mi := &file_sync_v1_access_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAccessResponse) ProtoMessage() {}

func (x *ReportAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_access_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAccessResponse.ProtoReflect.Descriptor instead.
func (*ReportAccessResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_access_proto_rawDescGZIP(), []int{3}
}

func (x *ReportAccessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_sync_v1_access_proto protoreflect.FileDescriptor

const file_sync_v1_access_proto_rawDesc = "" +
	"\n" +
	"\x14sync/v1/access.proto\x12\x0eaurora.sync.v1\"+\n" +
	"\x10GetAccessRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"n\n" +
	"\x12AccessSyncResponse\x12\x1d\n" +
	"\n" +
	"release_id\x18\x01 \x01(\x03R\treleaseId\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\"}\n" +
	"\x13ReportAccessRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\x03R\treleaseId\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"0\n" +
	"\x14ReportAccessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc1\x01\n" +
	"\x11AccessSyncService\x12Q\n" +
	"\tGetAccess\x12 .aurora.sync.v1.GetAccessRequest\x1a\".aurora.sync.v1.AccessSyncResponse\x12Y\n" +
	"\fReportAccess\x12#.aurora.sync.v1.ReportAccessRequest\x1a$.aurora.sync.v1.ReportAccessResponseB>Z<aurora-waf.local/control-plane/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_sync_v1_access_proto_rawDescOnce sync.Once
	file_sync_v1_access_proto_rawDescData []byte
)

func file_sync_v1_access_proto_rawDescGZIP() []byte {
	file_sync_v1_access_proto_rawDescOnce.Do(func() {
		file_sync_v1_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_v1_access_proto_rawDesc), len(file_sync_v1_access_proto_rawDesc)))
	})
	return file_sync_v1_access_proto_rawDescData
}

var file_sync_v1_access_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sync_v1_access_proto_goTypes = []any{
	(*GetAccessRequest)(nil),     // 0: aurora.sync.v1.GetAccessRequest
	(*AccessSyncResponse)(nil),   // 1: aurora.sync.v1.AccessSyncResponse
	(*ReportAccessRequest)(nil),  // 2: aurora.sync.v1.ReportAccessRequest
	(*ReportAccessResponse)(nil), // 3: aurora.sync.v1.ReportAccessResponse
}
var file_sync_v1_access_proto_depIdxs = []int32{
	0, // 0: aurora.sync.v1.AccessSyncService.GetAccess:input_type -> aurora.sync.v1.GetAccessRequest
	2, // 1: aurora.sync.v1.AccessSyncService.ReportAccess:input_type -> aurora.sync.v1.ReportAccessRequest
	1, // 2: aurora.sync.v1.AccessSyncService.GetAccess:output_type -> aurora.sync.v1.AccessSyncResponse
	3, // 3: aurora.sync.v1.AccessSyncService.ReportAccess:output_type -> aurora.sync.v1.ReportAccessResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sync_v1_access_proto_init() }
func file_sync_v1_access_proto_init() {
	if File_sync_v1_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_v1_access_proto_rawDesc), len(file_sync_v1_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_v1_access_proto_goTypes,
		DependencyIndexes: file_sync_v1_access_proto_depIdxs,
		MessageInfos:      file_sync_v1_access_proto_msgTypes,
	}.Build()
	File_sync_v1_access_proto = out.File
	file_sync_v1_access_proto_goTypes = nil
	file_sync_v1_access_proto_depIdxs = nil
}
