// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: sync/v1/access.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessSyncService_GetAccess_FullMethodName    = "/aurora.sync.v1.AccessSyncService/GetAccess"
	AccessSyncService_ReportAccess_FullMethodName = "/aurora.sync.v1.AccessSyncService/ReportAccess"
)

// AccessSyncServiceClient is the client API for AccessSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessSyncServiceClient interface {
	GetAccess(ctx context.Context, in *GetAccessRequest, opts ...grpc.CallOption) (*AccessSyncResponse, error)
	ReportAccess(ctx context.Context, in *ReportAccessRequest, opts ...grpc.CallOption) (*ReportAccessResponse, error)
}

type accessSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessSyncServiceClient(cc grpc.ClientConnInterface) AccessSyncServiceClient {
	return &accessSyncServiceClient{cc}
}

func (c *accessSyncServiceClient) GetAccess(ctx context.Context, in *GetAccessRequest, opts ...grpc.CallOption) (*AccessSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessSyncResponse)
	err := c.cc.Invoke(ctx, AccessSyncService_GetAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessSyncServiceClient) ReportAccess(ctx context.Context, in *ReportAccessRequest, opts ...grpc.CallOption) (*ReportAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAccessResponse)
	err := c.cc.Invoke(ctx, AccessSyncService_ReportAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessSyncServiceServer is the server API for AccessSyncService service.
// All implementations must embed UnimplementedAccessSyncServiceServer
// for forward compatibility.
type AccessSyncServiceServer interface {
	GetAccess(context.Context, *GetAccessRequest) (*AccessSyncResponse, error)
	ReportAccess(context.Context, *ReportAccessRequest) (*ReportAccessResponse, error)
	mustEmbedUnimplementedAccessSyncServiceServer()
}

// UnimplementedAccessSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessSyncServiceServer struct{}

func (UnimplementedAccessSyncServiceServer) GetAccess(context.Context, *GetAccessRequest) (*AccessSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccess not implemented")
}
func (UnimplementedAccessSyncServiceServer) ReportAccess(context.Context, *ReportAccessRequest) (*ReportAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAccess not implemented")
}
func (UnimplementedAccessSyncServiceServer) mustEmbedUnimplementedAccessSyncServiceServer() {}
func (UnimplementedAccessSyncServiceServer) testEmbeddedByValue()                           {}

// UnsafeAccessSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessSyncServiceServer will
// result in compilation errors.
type UnsafeAccessSyncServiceServer interface {
	mustEmbedUnimplementedAccessSyncServiceServer()
}

func RegisterAccessSyncServiceServer(s grpc.ServiceRegistrar, srv AccessSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedAccessSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessSyncService_ServiceDesc, srv)
}

func _AccessSyncService_GetAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessSyncServiceServer).GetAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessSyncService_GetAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessSyncServiceServer).GetAccess(ctx, req.(*GetAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessSyncService_ReportAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessSyncServiceServer).ReportAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessSyncService_ReportAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessSyncServiceServer).ReportAccess(ctx, req.(*ReportAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessSyncService_ServiceDesc is the grpc.ServiceDesc for AccessSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurora.sync.v1.AccessSyncService",
	HandlerType: (*AccessSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccess",
			Handler:    _AccessSyncService_GetAccess_Handler,
		},
		{
			MethodName: "ReportAccess",
			Handler:    _AccessSyncService_ReportAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync/v1/access.proto",
}
