// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: sync/v1/heartbeat.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNKNOWN  HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING  HealthStatus = 1 // NGINX is alive and serving traffic
	HealthStatus_HEALTH_STATUS_DEGRADED HealthStatus = 2 // NGINX reload failed or partially degraded
	HealthStatus_HEALTH_STATUS_DOWN     HealthStatus = 3 // NGINX process not running
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNKNOWN",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_DOWN",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNKNOWN":  0,
		"HEALTH_STATUS_SERVING":  1,
		"HEALTH_STATUS_DEGRADED": 2,
		"HEALTH_STATUS_DOWN":     3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sync_v1_heartbeat_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_sync_v1_heartbeat_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_sync_v1_heartbeat_proto_rawDescGZIP(), []int{0}
}

type NginxMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	MasterPid        int64                  `protobuf:"varint,2,opt,name=master_pid,json=masterPid,proto3" json:"master_pid,omitempty"`
	WorkerCount      int32                  `protobuf:"varint,3,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"`
	ActiveReleaseId  int64                  `protobuf:"varint,4,opt,name=active_release_id,json=activeReleaseId,proto3" json:"active_release_id,omitempty"`
	RuntimeStartedAt int64                  `protobuf:"varint,5,opt,name=runtime_started_at,json=runtimeStartedAt,proto3" json:"runtime_started_at,omitempty"`
	Hostname         string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Role             string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	WorkerIdentity   string                 `protobuf:"bytes,8,opt,name=worker_identity,json=workerIdentity,proto3" json:"worker_identity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NginxMetadata) Reset() {
	*x = NginxMetadata{}
	mi := &file_sync_v1_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NginxMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NginxMetadata) ProtoMessage() {}

func (x *NginxMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NginxMetadata.ProtoReflect.Descriptor instead.
func (*NginxMetadata) Descriptor() ([]byte, []int) {
	return file_sync_v1_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *NginxMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NginxMetadata) GetMasterPid() int64 {
	if x != nil {
		return x.MasterPid
	}
	return 0
}

func (x *NginxMetadata) GetWorkerCount() int32 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

func (x *NginxMetadata) GetActiveReleaseId() int64 {
	if x != nil {
		return x.ActiveReleaseId
	}
	return 0
}

func (x *NginxMetadata) GetRuntimeStartedAt() int64 {
	if x != nil {
		return x.RuntimeStartedAt
	}
	return 0
}

func (x *NginxMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NginxMetadata) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NginxMetadata) GetWorkerIdentity() string {
	if x != nil {
		return x.WorkerIdentity
	}
	return ""
}

type HeartbeatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp       int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status          HealthStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=aurora.sync.v1.HealthStatus" json:"status,omitempty"`
	ActiveReleaseId int64                  `protobuf:"varint,4,opt,name=active_release_id,json=activeReleaseId,proto3" json:"active_release_id,omitempty"`
	MetadataDigest  string                 `protobuf:"bytes,5,opt,name=metadata_digest,json=metadataDigest,proto3" json:"metadata_digest,omitempty"` // Short hash for RAM diffing
	Metadata        *NginxMetadata         `protobuf:"bytes,6,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`                             // Only sent on boot or when digest changes
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_sync_v1_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *HeartbeatRequest) GetActiveReleaseId() int64 {
	if x != nil {
		return x.ActiveReleaseId
	}
	return 0
}

func (x *HeartbeatRequest) GetMetadataDigest() string {
	if x != nil {
		return x.MetadataDigest
	}
	return ""
}

func (x *HeartbeatRequest) GetMetadata() *NginxMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HeartbeatResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Action               string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "none", "reload", "restart", "resync_metadata"
	DesiredReleaseId     int64                  `protobuf:"varint,2,opt,name=desired_release_id,json=desiredReleaseId,proto3" json:"desired_release_id,omitempty"`
	MetadataAcknowledged bool                   `protobuf:"varint,3,opt,name=metadata_acknowledged,json=metadataAcknowledged,proto3" json:"metadata_acknowledged,omitempty"` // Confirms Controller received & cached metadata
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_sync_v1_heartbeat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_heartbeat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_heartbeat_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *HeartbeatResponse) GetDesiredReleaseId() int64 {
	if x != nil {
		return x.DesiredReleaseId
	}
	return 0
}

func (x *HeartbeatResponse) GetMetadataAcknowledged() bool {
	if x != nil {
		return x.MetadataAcknowledged
	}
	return false
}

var File_sync_v1_heartbeat_proto protoreflect.FileDescriptor

const file_sync_v1_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x17sync/v1/heartbeat.proto\x12\x0eaurora.sync.v1\"\x9e\x02\n" +
	"\rNginxMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"master_pid\x18\x02 \x01(\x03R\tmasterPid\x12!\n" +
	"\fworker_count\x18\x03 \x01(\x05R\vworkerCount\x12*\n" +
	"\x11active_release_id\x18\x04 \x01(\x03R\x0factiveReleaseId\x12,\n" +
	"\x12runtime_started_at\x18\x05 \x01(\x03R\x10runtimeStartedAt\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12'\n" +
	"\x0fworker_identity\x18\b \x01(\tR\x0eworkerIdentity\"\xa1\x02\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.aurora.sync.v1.HealthStatusR\x06status\x12*\n" +
	"\x11active_release_id\x18\x04 \x01(\x03R\x0factiveReleaseId\x12'\n" +
	"\x0fmetadata_digest\x18\x05 \x01(\tR\x0emetadataDigest\x12>\n" +
	"\bmetadata\x18\x06 \x01(\v2\x1d.aurora.sync.v1.NginxMetadataH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"\x8e\x01\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12,\n" +
	"\x12desired_release_id\x18\x02 \x01(\x03R\x10desiredReleaseId\x123\n" +
	"\x15metadata_acknowledged\x18\x03 \x01(\bR\x14metadataAcknowledged*x\n" +
	"\fHealthStatus\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x16\n" +
	"\x12HEALTH_STATUS_DOWN\x10\x032h\n" +
	"\x10HeartbeatService\x12T\n" +
	"\rSendHeartbeat\x12 .aurora.sync.v1.HeartbeatRequest\x1a!.aurora.sync.v1.HeartbeatResponseB>Z<aurora-waf.local/control-plane/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_sync_v1_heartbeat_proto_rawDescOnce sync.Once
	file_sync_v1_heartbeat_proto_rawDescData []byte
)

func file_sync_v1_heartbeat_proto_rawDescGZIP() []byte {
	file_sync_v1_heartbeat_proto_rawDescOnce.Do(func() {
		file_sync_v1_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_v1_heartbeat_proto_rawDesc), len(file_sync_v1_heartbeat_proto_rawDesc)))
	})
	return file_sync_v1_heartbeat_proto_rawDescData
}

var file_sync_v1_heartbeat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sync_v1_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sync_v1_heartbeat_proto_goTypes = []any{
	(HealthStatus)(0),         // 0: aurora.sync.v1.HealthStatus
	(*NginxMetadata)(nil),     // 1: aurora.sync.v1.NginxMetadata
	(*HeartbeatRequest)(nil),  // 2: aurora.sync.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: aurora.sync.v1.HeartbeatResponse
}
var file_sync_v1_heartbeat_proto_depIdxs = []int32{
	0, // 0: aurora.sync.v1.HeartbeatRequest.status:type_name -> aurora.sync.v1.HealthStatus
	1, // 1: aurora.sync.v1.HeartbeatRequest.metadata:type_name -> aurora.sync.v1.NginxMetadata
	2, // 2: aurora.sync.v1.HeartbeatService.SendHeartbeat:input_type -> aurora.sync.v1.HeartbeatRequest
	3, // 3: aurora.sync.v1.HeartbeatService.SendHeartbeat:output_type -> aurora.sync.v1.HeartbeatResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sync_v1_heartbeat_proto_init() }
func file_sync_v1_heartbeat_proto_init() {
	if File_sync_v1_heartbeat_proto != nil {
		return
	}
	file_sync_v1_heartbeat_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_v1_heartbeat_proto_rawDesc), len(file_sync_v1_heartbeat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_v1_heartbeat_proto_goTypes,
		DependencyIndexes: file_sync_v1_heartbeat_proto_depIdxs,
		EnumInfos:         file_sync_v1_heartbeat_proto_enumTypes,
		MessageInfos:      file_sync_v1_heartbeat_proto_msgTypes,
	}.Build()
	File_sync_v1_heartbeat_proto = out.File
	file_sync_v1_heartbeat_proto_goTypes = nil
	file_sync_v1_heartbeat_proto_depIdxs = nil
}
