// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: sync/v1/modules.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModuleSyncService_PollModuleJob_FullMethodName      = "/aurora.sync.v1.ModuleSyncService/PollModuleJob"
	ModuleSyncService_AppendModuleJobLog_FullMethodName = "/aurora.sync.v1.ModuleSyncService/AppendModuleJobLog"
	ModuleSyncService_ReportModules_FullMethodName      = "/aurora.sync.v1.ModuleSyncService/ReportModules"
)

// ModuleSyncServiceClient is the client API for ModuleSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModuleSyncServiceClient interface {
	PollModuleJob(ctx context.Context, in *PollModuleJobRequest, opts ...grpc.CallOption) (*PollModuleJobResponse, error)
	AppendModuleJobLog(ctx context.Context, in *AppendModuleJobLogRequest, opts ...grpc.CallOption) (*AppendModuleJobLogResponse, error)
	ReportModules(ctx context.Context, in *ModuleReportRequest, opts ...grpc.CallOption) (*ModuleReportResponse, error)
}

type moduleSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModuleSyncServiceClient(cc grpc.ClientConnInterface) ModuleSyncServiceClient {
	return &moduleSyncServiceClient{cc}
}

func (c *moduleSyncServiceClient) PollModuleJob(ctx context.Context, in *PollModuleJobRequest, opts ...grpc.CallOption) (*PollModuleJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollModuleJobResponse)
	err := c.cc.Invoke(ctx, ModuleSyncService_PollModuleJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleSyncServiceClient) AppendModuleJobLog(ctx context.Context, in *AppendModuleJobLogRequest, opts ...grpc.CallOption) (*AppendModuleJobLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendModuleJobLogResponse)
	err := c.cc.Invoke(ctx, ModuleSyncService_AppendModuleJobLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleSyncServiceClient) ReportModules(ctx context.Context, in *ModuleReportRequest, opts ...grpc.CallOption) (*ModuleReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModuleReportResponse)
	err := c.cc.Invoke(ctx, ModuleSyncService_ReportModules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleSyncServiceServer is the server API for ModuleSyncService service.
// All implementations must embed UnimplementedModuleSyncServiceServer
// for forward compatibility.
type ModuleSyncServiceServer interface {
	PollModuleJob(context.Context, *PollModuleJobRequest) (*PollModuleJobResponse, error)
	AppendModuleJobLog(context.Context, *AppendModuleJobLogRequest) (*AppendModuleJobLogResponse, error)
	ReportModules(context.Context, *ModuleReportRequest) (*ModuleReportResponse, error)
	mustEmbedUnimplementedModuleSyncServiceServer()
}

// UnimplementedModuleSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModuleSyncServiceServer struct{}

func (UnimplementedModuleSyncServiceServer) PollModuleJob(context.Context, *PollModuleJobRequest) (*PollModuleJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollModuleJob not implemented")
}
func (UnimplementedModuleSyncServiceServer) AppendModuleJobLog(context.Context, *AppendModuleJobLogRequest) (*AppendModuleJobLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendModuleJobLog not implemented")
}
func (UnimplementedModuleSyncServiceServer) ReportModules(context.Context, *ModuleReportRequest) (*ModuleReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportModules not implemented")
}
func (UnimplementedModuleSyncServiceServer) mustEmbedUnimplementedModuleSyncServiceServer() {}
func (UnimplementedModuleSyncServiceServer) testEmbeddedByValue()                           {}

// UnsafeModuleSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModuleSyncServiceServer will
// result in compilation errors.
type UnsafeModuleSyncServiceServer interface {
	mustEmbedUnimplementedModuleSyncServiceServer()
}

func RegisterModuleSyncServiceServer(s grpc.ServiceRegistrar, srv ModuleSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedModuleSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModuleSyncService_ServiceDesc, srv)
}

func _ModuleSyncService_PollModuleJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollModuleJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleSyncServiceServer).PollModuleJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleSyncService_PollModuleJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleSyncServiceServer).PollModuleJob(ctx, req.(*PollModuleJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleSyncService_AppendModuleJobLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendModuleJobLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleSyncServiceServer).AppendModuleJobLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleSyncService_AppendModuleJobLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleSyncServiceServer).AppendModuleJobLog(ctx, req.(*AppendModuleJobLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleSyncService_ReportModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleSyncServiceServer).ReportModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleSyncService_ReportModules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleSyncServiceServer).ReportModules(ctx, req.(*ModuleReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModuleSyncService_ServiceDesc is the grpc.ServiceDesc for ModuleSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModuleSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurora.sync.v1.ModuleSyncService",
	HandlerType: (*ModuleSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PollModuleJob",
			Handler:    _ModuleSyncService_PollModuleJob_Handler,
		},
		{
			MethodName: "AppendModuleJobLog",
			Handler:    _ModuleSyncService_AppendModuleJobLog_Handler,
		},
		{
			MethodName: "ReportModules",
			Handler:    _ModuleSyncService_ReportModules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync/v1/modules.proto",
}
