// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: sync/v1/modules.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollModuleJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollModuleJobRequest) Reset() {
	*x = PollModuleJobRequest{}
	mi := &file_sync_v1_modules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollModuleJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollModuleJobRequest) ProtoMessage() {}

func (x *PollModuleJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_modules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollModuleJobRequest.ProtoReflect.Descriptor instead.
func (*PollModuleJobRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_modules_proto_rawDescGZIP(), []int{0}
}

func (x *PollModuleJobRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PollModuleJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollModuleJobResponse) Reset() {
	*x = PollModuleJobResponse{}
	mi := &file_sync_v1_modules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollModuleJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollModuleJobResponse) ProtoMessage() {}

func (x *PollModuleJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_modules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollModuleJobResponse.ProtoReflect.Descriptor instead.
func (*PollModuleJobResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_modules_proto_rawDescGZIP(), []int{1}
}

func (x *PollModuleJobResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PollModuleJobResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type AppendModuleJobLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	JobId         int64                  `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Progress      int32                  `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	LogChunk      string                 `protobuf:"bytes,6,opt,name=log_chunk,json=logChunk,proto3" json:"log_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendModuleJobLogRequest) Reset() {
	*x = AppendModuleJobLogRequest{}
	mi := &file_sync_v1_modules_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendModuleJobLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendModuleJobLogRequest) ProtoMessage() {}

func (x *AppendModuleJobLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_modules_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendModuleJobLogRequest.ProtoReflect.Descriptor instead.
func (*AppendModuleJobLogRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_modules_proto_rawDescGZIP(), []int{2}
}

func (x *AppendModuleJobLogRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AppendModuleJobLogRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *AppendModuleJobLogRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *AppendModuleJobLogRequest) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *AppendModuleJobLogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppendModuleJobLogRequest) GetLogChunk() string {
	if x != nil {
		return x.LogChunk
	}
	return ""
}

type AppendModuleJobLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendModuleJobLogResponse) Reset() {
	*x = AppendModuleJobLogResponse{}
	mi := &file_sync_v1_modules_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendModuleJobLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendModuleJobLogResponse) ProtoMessage() {}

func (x *AppendModuleJobLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_modules_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendModuleJobLogResponse.ProtoReflect.Descriptor instead.
func (*AppendModuleJobLogResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_modules_proto_rawDescGZIP(), []int{3}
}

func (x *AppendModuleJobLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ModuleReportItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Loaded        bool                   `protobuf:"varint,3,opt,name=loaded,proto3" json:"loaded,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleReportItem) Reset() {
	*x = ModuleReportItem{}
	mi := &file_sync_v1_modules_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleReportItem) ProtoMessage() {}

func (x *ModuleReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_modules_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleReportItem.ProtoReflect.Descriptor instead.
func (*ModuleReportItem) Descriptor() ([]byte, []int) {
	return file_sync_v1_modules_proto_rawDescGZIP(), []int{4}
}

func (x *ModuleReportItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleReportItem) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ModuleReportItem) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *ModuleReportItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ModuleReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CheckedAt     int64                  `protobuf:"varint,2,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	NginxVersion  string                 `protobuf:"bytes,3,opt,name=nginx_version,json=nginxVersion,proto3" json:"nginx_version,omitempty"`
	Architecture  string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Installable   bool                   `protobuf:"varint,5,opt,name=installable,proto3" json:"installable,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	JobId         int64                  `protobuf:"varint,7,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobState      string                 `protobuf:"bytes,8,opt,name=job_state,json=jobState,proto3" json:"job_state,omitempty"`
	JobMessage    string                 `protobuf:"bytes,9,opt,name=job_message,json=jobMessage,proto3" json:"job_message,omitempty"`
	JobLogs       string                 `protobuf:"bytes,10,opt,name=job_logs,json=jobLogs,proto3" json:"job_logs,omitempty"`
	Modules       []*ModuleReportItem    `protobuf:"bytes,11,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleReportRequest) Reset() {
	*x = ModuleReportRequest{}
	mi := &file_sync_v1_modules_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleReportRequest) ProtoMessage() {}

func (x *ModuleReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_modules_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleReportRequest.ProtoReflect.Descriptor instead.
func (*ModuleReportRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_modules_proto_rawDescGZIP(), []int{5}
}

func (x *ModuleReportRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ModuleReportRequest) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

func (x *ModuleReportRequest) GetNginxVersion() string {
	if x != nil {
		return x.NginxVersion
	}
	return ""
}

func (x *ModuleReportRequest) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *ModuleReportRequest) GetInstallable() bool {
	if x != nil {
		return x.Installable
	}
	return false
}

func (x *ModuleReportRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ModuleReportRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *ModuleReportRequest) GetJobState() string {
	if x != nil {
		return x.JobState
	}
	return ""
}

func (x *ModuleReportRequest) GetJobMessage() string {
	if x != nil {
		return x.JobMessage
	}
	return ""
}

func (x *ModuleReportRequest) GetJobLogs() string {
	if x != nil {
		return x.JobLogs
	}
	return ""
}

func (x *ModuleReportRequest) GetModules() []*ModuleReportItem {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ModuleReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleReportResponse) Reset() {
	*x = ModuleReportResponse{}
	mi := &file_sync_v1_modules_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleReportResponse) ProtoMessage() {}

func (x *ModuleReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_modules_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleReportResponse.ProtoReflect.Descriptor instead.
func (*ModuleReportResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_modules_proto_rawDescGZIP(), []int{6}
}

func (x *ModuleReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_sync_v1_modules_proto protoreflect.FileDescriptor

const file_sync_v1_modules_proto_rawDesc = "" +
	"\n" +
	"\x15sync/v1/modules.proto\x12\x0eaurora.sync.v1\"/\n" +
	"\x14PollModuleJobRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"?\n" +
	"\x15PollModuleJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xb4\x01\n" +
	"\x19AppendModuleJobLogRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x03R\x05jobId\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x05R\bprogress\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1b\n" +
	"\tlog_chunk\x18\x06 \x01(\tR\blogChunk\"6\n" +
	"\x1aAppendModuleJobLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"t\n" +
	"\x10ModuleReportItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12\x16\n" +
	"\x06loaded\x18\x03 \x01(\bR\x06loaded\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\xfa\x02\n" +
	"\x13ModuleReportRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x02 \x01(\x03R\tcheckedAt\x12#\n" +
	"\rnginx_version\x18\x03 \x01(\tR\fnginxVersion\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\x12 \n" +
	"\vinstallable\x18\x05 \x01(\bR\vinstallable\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x15\n" +
	"\x06job_id\x18\a \x01(\x03R\x05jobId\x12\x1b\n" +
	"\tjob_state\x18\b \x01(\tR\bjobState\x12\x1f\n" +
	"\vjob_message\x18\t \x01(\tR\n" +
	"jobMessage\x12\x19\n" +
	"\bjob_logs\x18\n" +
	" \x01(\tR\ajobLogs\x12:\n" +
	"\amodules\x18\v \x03(\v2 .aurora.sync.v1.ModuleReportItemR\amodules\"0\n" +
	"\x14ModuleReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xba\x02\n" +
	"\x11ModuleSyncService\x12\\\n" +
	"\rPollModuleJob\x12$.aurora.sync.v1.PollModuleJobRequest\x1a%.aurora.sync.v1.PollModuleJobResponse\x12k\n" +
	"\x12AppendModuleJobLog\x12).aurora.sync.v1.AppendModuleJobLogRequest\x1a*.aurora.sync.v1.AppendModuleJobLogResponse\x12Z\n" +
	"\rReportModules\x12#.aurora.sync.v1.ModuleReportRequest\x1a$.aurora.sync.v1.ModuleReportResponseB>Z<aurora-waf.local/control-plane/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_sync_v1_modules_proto_rawDescOnce sync.Once
	file_sync_v1_modules_proto_rawDescData []byte
)

func file_sync_v1_modules_proto_rawDescGZIP() []byte {
	file_sync_v1_modules_proto_rawDescOnce.Do(func() {
		file_sync_v1_modules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_v1_modules_proto_rawDesc), len(file_sync_v1_modules_proto_rawDesc)))
	})
	return file_sync_v1_modules_proto_rawDescData
}

var file_sync_v1_modules_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sync_v1_modules_proto_goTypes = []any{
	(*PollModuleJobRequest)(nil),       // 0: aurora.sync.v1.PollModuleJobRequest
	(*PollModuleJobResponse)(nil),      // 1: aurora.sync.v1.PollModuleJobResponse
	(*AppendModuleJobLogRequest)(nil),  // 2: aurora.sync.v1.AppendModuleJobLogRequest
	(*AppendModuleJobLogResponse)(nil), // 3: aurora.sync.v1.AppendModuleJobLogResponse
	(*ModuleReportItem)(nil),           // 4: aurora.sync.v1.ModuleReportItem
	(*ModuleReportRequest)(nil),        // 5: aurora.sync.v1.ModuleReportRequest
	(*ModuleReportResponse)(nil),       // 6: aurora.sync.v1.ModuleReportResponse
}
var file_sync_v1_modules_proto_depIdxs = []int32{
	4, // 0: aurora.sync.v1.ModuleReportRequest.modules:type_name -> aurora.sync.v1.ModuleReportItem
	0, // 1: aurora.sync.v1.ModuleSyncService.PollModuleJob:input_type -> aurora.sync.v1.PollModuleJobRequest
	2, // 2: aurora.sync.v1.ModuleSyncService.AppendModuleJobLog:input_type -> aurora.sync.v1.AppendModuleJobLogRequest
	5, // 3: aurora.sync.v1.ModuleSyncService.ReportModules:input_type -> aurora.sync.v1.ModuleReportRequest
	1, // 4: aurora.sync.v1.ModuleSyncService.PollModuleJob:output_type -> aurora.sync.v1.PollModuleJobResponse
	3, // 5: aurora.sync.v1.ModuleSyncService.AppendModuleJobLog:output_type -> aurora.sync.v1.AppendModuleJobLogResponse
	6, // 6: aurora.sync.v1.ModuleSyncService.ReportModules:output_type -> aurora.sync.v1.ModuleReportResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sync_v1_modules_proto_init() }
func file_sync_v1_modules_proto_init() {
	if File_sync_v1_modules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_v1_modules_proto_rawDesc), len(file_sync_v1_modules_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_v1_modules_proto_goTypes,
		DependencyIndexes: file_sync_v1_modules_proto_depIdxs,
		MessageInfos:      file_sync_v1_modules_proto_msgTypes,
	}.Build()
	File_sync_v1_modules_proto = out.File
	file_sync_v1_modules_proto_goTypes = nil
	file_sync_v1_modules_proto_depIdxs = nil
}
