// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: sync/v1/policy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_sync_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *GetPolicyRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PolicySyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReleaseId     int64                  `protobuf:"varint,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySyncResponse) Reset() {
	*x = PolicySyncResponse{}
	mi := &file_sync_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySyncResponse) ProtoMessage() {}

func (x *PolicySyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySyncResponse.ProtoReflect.Descriptor instead.
func (*PolicySyncResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *PolicySyncResponse) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *PolicySyncResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PolicySyncResponse) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type ReportPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ReleaseId     int64                  `protobuf:"varint,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPolicyRequest) Reset() {
	*x = ReportPolicyRequest{}
	mi := &file_sync_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPolicyRequest) ProtoMessage() {}

func (x *ReportPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPolicyRequest.ProtoReflect.Descriptor instead.
func (*ReportPolicyRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *ReportPolicyRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportPolicyRequest) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *ReportPolicyRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ReportPolicyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPolicyResponse) Reset() {
	*x = ReportPolicyResponse{}
	mi := &file_sync_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPolicyResponse) ProtoMessage() {}

func (x *ReportPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPolicyResponse.ProtoReflect.Descriptor instead.
func (*ReportPolicyResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *ReportPolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_sync_v1_policy_proto protoreflect.FileDescriptor

const file_sync_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x14sync/v1/policy.proto\x12\x0eaurora.sync.v1\"+\n" +
	"\x10GetPolicyRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"n\n" +
	"\x12PolicySyncResponse\x12\x1d\n" +
	"\n" +
	"release_id\x18\x01 \x01(\x03R\treleaseId\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\tR\vpayloadJson\"}\n" +
	"\x13ReportPolicyRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\x03R\treleaseId\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"0\n" +
	"\x14ReportPolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc1\x01\n" +
	"\x11PolicySyncService\x12Q\n" +
	"\tGetPolicy\x12 .aurora.sync.v1.GetPolicyRequest\x1a\".aurora.sync.v1.PolicySyncResponse\x12Y\n" +
	"\fReportPolicy\x12#.aurora.sync.v1.ReportPolicyRequest\x1a$.aurora.sync.v1.ReportPolicyResponseB>Z<aurora-waf.local/control-plane/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_sync_v1_policy_proto_rawDescOnce sync.Once
	file_sync_v1_policy_proto_rawDescData []byte
)

func file_sync_v1_policy_proto_rawDescGZIP() []byte {
	file_sync_v1_policy_proto_rawDescOnce.Do(func() {
		file_sync_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_v1_policy_proto_rawDesc), len(file_sync_v1_policy_proto_rawDesc)))
	})
	return file_sync_v1_policy_proto_rawDescData
}

var file_sync_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sync_v1_policy_proto_goTypes = []any{
	(*GetPolicyRequest)(nil),     // 0: aurora.sync.v1.GetPolicyRequest
	(*PolicySyncResponse)(nil),   // 1: aurora.sync.v1.PolicySyncResponse
	(*ReportPolicyRequest)(nil),  // 2: aurora.sync.v1.ReportPolicyRequest
	(*ReportPolicyResponse)(nil), // 3: aurora.sync.v1.ReportPolicyResponse
}
var file_sync_v1_policy_proto_depIdxs = []int32{
	0, // 0: aurora.sync.v1.PolicySyncService.GetPolicy:input_type -> aurora.sync.v1.GetPolicyRequest
	2, // 1: aurora.sync.v1.PolicySyncService.ReportPolicy:input_type -> aurora.sync.v1.ReportPolicyRequest
	1, // 2: aurora.sync.v1.PolicySyncService.GetPolicy:output_type -> aurora.sync.v1.PolicySyncResponse
	3, // 3: aurora.sync.v1.PolicySyncService.ReportPolicy:output_type -> aurora.sync.v1.ReportPolicyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sync_v1_policy_proto_init() }
func file_sync_v1_policy_proto_init() {
	if File_sync_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_v1_policy_proto_rawDesc), len(file_sync_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_v1_policy_proto_goTypes,
		DependencyIndexes: file_sync_v1_policy_proto_depIdxs,
		MessageInfos:      file_sync_v1_policy_proto_msgTypes,
	}.Build()
	File_sync_v1_policy_proto = out.File
	file_sync_v1_policy_proto_goTypes = nil
	file_sync_v1_policy_proto_depIdxs = nil
}
