// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: sync/v1/policy.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicySyncService_GetPolicy_FullMethodName    = "/aurora.sync.v1.PolicySyncService/GetPolicy"
	PolicySyncService_ReportPolicy_FullMethodName = "/aurora.sync.v1.PolicySyncService/ReportPolicy"
)

// PolicySyncServiceClient is the client API for PolicySyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicySyncServiceClient interface {
	GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*PolicySyncResponse, error)
	ReportPolicy(ctx context.Context, in *ReportPolicyRequest, opts ...grpc.CallOption) (*ReportPolicyResponse, error)
}

type policySyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicySyncServiceClient(cc grpc.ClientConnInterface) PolicySyncServiceClient {
	return &policySyncServiceClient{cc}
}

func (c *policySyncServiceClient) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*PolicySyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicySyncResponse)
	err := c.cc.Invoke(ctx, PolicySyncService_GetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policySyncServiceClient) ReportPolicy(ctx context.Context, in *ReportPolicyRequest, opts ...grpc.CallOption) (*ReportPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportPolicyResponse)
	err := c.cc.Invoke(ctx, PolicySyncService_ReportPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicySyncServiceServer is the server API for PolicySyncService service.
// All implementations must embed UnimplementedPolicySyncServiceServer
// for forward compatibility.
type PolicySyncServiceServer interface {
	GetPolicy(context.Context, *GetPolicyRequest) (*PolicySyncResponse, error)
	ReportPolicy(context.Context, *ReportPolicyRequest) (*ReportPolicyResponse, error)
	mustEmbedUnimplementedPolicySyncServiceServer()
}

// UnimplementedPolicySyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicySyncServiceServer struct{}

func (UnimplementedPolicySyncServiceServer) GetPolicy(context.Context, *GetPolicyRequest) (*PolicySyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedPolicySyncServiceServer) ReportPolicy(context.Context, *ReportPolicyRequest) (*ReportPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportPolicy not implemented")
}
func (UnimplementedPolicySyncServiceServer) mustEmbedUnimplementedPolicySyncServiceServer() {}
func (UnimplementedPolicySyncServiceServer) testEmbeddedByValue()                           {}

// UnsafePolicySyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicySyncServiceServer will
// result in compilation errors.
type UnsafePolicySyncServiceServer interface {
	mustEmbedUnimplementedPolicySyncServiceServer()
}

func RegisterPolicySyncServiceServer(s grpc.ServiceRegistrar, srv PolicySyncServiceServer) {
	// If the following call panics, it indicates UnimplementedPolicySyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicySyncService_ServiceDesc, srv)
}

func _PolicySyncService_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicySyncServiceServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicySyncService_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicySyncServiceServer).GetPolicy(ctx, req.(*GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicySyncService_ReportPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicySyncServiceServer).ReportPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicySyncService_ReportPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicySyncServiceServer).ReportPolicy(ctx, req.(*ReportPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicySyncService_ServiceDesc is the grpc.ServiceDesc for PolicySyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicySyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurora.sync.v1.PolicySyncService",
	HandlerType: (*PolicySyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPolicy",
			Handler:    _PolicySyncService_GetPolicy_Handler,
		},
		{
			MethodName: "ReportPolicy",
			Handler:    _PolicySyncService_ReportPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync/v1/policy.proto",
}
