// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: sync/v1/routing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDomainRoutingBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainRoutingBundleRequest) Reset() {
	*x = GetDomainRoutingBundleRequest{}
	mi := &file_sync_v1_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainRoutingBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainRoutingBundleRequest) ProtoMessage() {}

func (x *GetDomainRoutingBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainRoutingBundleRequest.ProtoReflect.Descriptor instead.
func (*GetDomainRoutingBundleRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_routing_proto_rawDescGZIP(), []int{0}
}

func (x *GetDomainRoutingBundleRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type CertificateAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateAsset) Reset() {
	*x = CertificateAsset{}
	mi := &file_sync_v1_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateAsset) ProtoMessage() {}

func (x *CertificateAsset) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateAsset.ProtoReflect.Descriptor instead.
func (*CertificateAsset) Descriptor() ([]byte, []int) {
	return file_sync_v1_routing_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CertificateAsset) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DomainRoutingBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Files         []*CertificateAsset    `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Digest        string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainRoutingBundleResponse) Reset() {
	*x = DomainRoutingBundleResponse{}
	mi := &file_sync_v1_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainRoutingBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainRoutingBundleResponse) ProtoMessage() {}

func (x *DomainRoutingBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainRoutingBundleResponse.ProtoReflect.Descriptor instead.
func (*DomainRoutingBundleResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_routing_proto_rawDescGZIP(), []int{2}
}

func (x *DomainRoutingBundleResponse) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *DomainRoutingBundleResponse) GetFiles() []*CertificateAsset {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DomainRoutingBundleResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

var File_sync_v1_routing_proto protoreflect.FileDescriptor

const file_sync_v1_routing_proto_rawDesc = "" +
	"\n" +
	"\x15sync/v1/routing.proto\x12\x0eaurora.sync.v1\"8\n" +
	"\x1dGetDomainRoutingBundleRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"@\n" +
	"\x10CertificateAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x85\x01\n" +
	"\x1bDomainRoutingBundleResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x126\n" +
	"\x05files\x18\x02 \x03(\v2 .aurora.sync.v1.CertificateAssetR\x05files\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest2\x90\x01\n" +
	"\x18DomainRoutingSyncService\x12t\n" +
	"\x16GetDomainRoutingBundle\x12-.aurora.sync.v1.GetDomainRoutingBundleRequest\x1a+.aurora.sync.v1.DomainRoutingBundleResponseB>Z<aurora-waf.local/control-plane/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_sync_v1_routing_proto_rawDescOnce sync.Once
	file_sync_v1_routing_proto_rawDescData []byte
)

func file_sync_v1_routing_proto_rawDescGZIP() []byte {
	file_sync_v1_routing_proto_rawDescOnce.Do(func() {
		file_sync_v1_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_v1_routing_proto_rawDesc), len(file_sync_v1_routing_proto_rawDesc)))
	})
	return file_sync_v1_routing_proto_rawDescData
}

var file_sync_v1_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sync_v1_routing_proto_goTypes = []any{
	(*GetDomainRoutingBundleRequest)(nil), // 0: aurora.sync.v1.GetDomainRoutingBundleRequest
	(*CertificateAsset)(nil),              // 1: aurora.sync.v1.CertificateAsset
	(*DomainRoutingBundleResponse)(nil),   // 2: aurora.sync.v1.DomainRoutingBundleResponse
}
var file_sync_v1_routing_proto_depIdxs = []int32{
	1, // 0: aurora.sync.v1.DomainRoutingBundleResponse.files:type_name -> aurora.sync.v1.CertificateAsset
	0, // 1: aurora.sync.v1.DomainRoutingSyncService.GetDomainRoutingBundle:input_type -> aurora.sync.v1.GetDomainRoutingBundleRequest
	2, // 2: aurora.sync.v1.DomainRoutingSyncService.GetDomainRoutingBundle:output_type -> aurora.sync.v1.DomainRoutingBundleResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sync_v1_routing_proto_init() }
func file_sync_v1_routing_proto_init() {
	if File_sync_v1_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_v1_routing_proto_rawDesc), len(file_sync_v1_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_v1_routing_proto_goTypes,
		DependencyIndexes: file_sync_v1_routing_proto_depIdxs,
		MessageInfos:      file_sync_v1_routing_proto_msgTypes,
	}.Build()
	File_sync_v1_routing_proto = out.File
	file_sync_v1_routing_proto_goTypes = nil
	file_sync_v1_routing_proto_depIdxs = nil
}
