// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: sync/v1/routing.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DomainRoutingSyncService_GetDomainRoutingBundle_FullMethodName = "/aurora.sync.v1.DomainRoutingSyncService/GetDomainRoutingBundle"
)

// DomainRoutingSyncServiceClient is the client API for DomainRoutingSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DomainRoutingSyncServiceClient interface {
	GetDomainRoutingBundle(ctx context.Context, in *GetDomainRoutingBundleRequest, opts ...grpc.CallOption) (*DomainRoutingBundleResponse, error)
}

type domainRoutingSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDomainRoutingSyncServiceClient(cc grpc.ClientConnInterface) DomainRoutingSyncServiceClient {
	return &domainRoutingSyncServiceClient{cc}
}

func (c *domainRoutingSyncServiceClient) GetDomainRoutingBundle(ctx context.Context, in *GetDomainRoutingBundleRequest, opts ...grpc.CallOption) (*DomainRoutingBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainRoutingBundleResponse)
	err := c.cc.Invoke(ctx, DomainRoutingSyncService_GetDomainRoutingBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DomainRoutingSyncServiceServer is the server API for DomainRoutingSyncService service.
// All implementations must embed UnimplementedDomainRoutingSyncServiceServer
// for forward compatibility.
type DomainRoutingSyncServiceServer interface {
	GetDomainRoutingBundle(context.Context, *GetDomainRoutingBundleRequest) (*DomainRoutingBundleResponse, error)
	mustEmbedUnimplementedDomainRoutingSyncServiceServer()
}

// UnimplementedDomainRoutingSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDomainRoutingSyncServiceServer struct{}

func (UnimplementedDomainRoutingSyncServiceServer) GetDomainRoutingBundle(context.Context, *GetDomainRoutingBundleRequest) (*DomainRoutingBundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDomainRoutingBundle not implemented")
}
func (UnimplementedDomainRoutingSyncServiceServer) mustEmbedUnimplementedDomainRoutingSyncServiceServer() {
}
func (UnimplementedDomainRoutingSyncServiceServer) testEmbeddedByValue() {}

// UnsafeDomainRoutingSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DomainRoutingSyncServiceServer will
// result in compilation errors.
type UnsafeDomainRoutingSyncServiceServer interface {
	mustEmbedUnimplementedDomainRoutingSyncServiceServer()
}

func RegisterDomainRoutingSyncServiceServer(s grpc.ServiceRegistrar, srv DomainRoutingSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedDomainRoutingSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DomainRoutingSyncService_ServiceDesc, srv)
}

func _DomainRoutingSyncService_GetDomainRoutingBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainRoutingBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DomainRoutingSyncServiceServer).GetDomainRoutingBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DomainRoutingSyncService_GetDomainRoutingBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DomainRoutingSyncServiceServer).GetDomainRoutingBundle(ctx, req.(*GetDomainRoutingBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DomainRoutingSyncService_ServiceDesc is the grpc.ServiceDesc for DomainRoutingSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DomainRoutingSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurora.sync.v1.DomainRoutingSyncService",
	HandlerType: (*DomainRoutingSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDomainRoutingBundle",
			Handler:    _DomainRoutingSyncService_GetDomainRoutingBundle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync/v1/routing.proto",
}
