// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: sync/v1/spec.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpecSyncService_SyncSpec_FullMethodName   = "/aurora.sync.v1.SpecSyncService/SyncSpec"
	SpecSyncService_ReportSpec_FullMethodName = "/aurora.sync.v1.SpecSyncService/ReportSpec"
)

// SpecSyncServiceClient is the client API for SpecSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpecSyncServiceClient interface {
	SyncSpec(ctx context.Context, in *SyncSpecRequest, opts ...grpc.CallOption) (*SyncSpecResponse, error)
	ReportSpec(ctx context.Context, in *ReportSpecRequest, opts ...grpc.CallOption) (*ReportSpecResponse, error)
}

type specSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpecSyncServiceClient(cc grpc.ClientConnInterface) SpecSyncServiceClient {
	return &specSyncServiceClient{cc}
}

func (c *specSyncServiceClient) SyncSpec(ctx context.Context, in *SyncSpecRequest, opts ...grpc.CallOption) (*SyncSpecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncSpecResponse)
	err := c.cc.Invoke(ctx, SpecSyncService_SyncSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specSyncServiceClient) ReportSpec(ctx context.Context, in *ReportSpecRequest, opts ...grpc.CallOption) (*ReportSpecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportSpecResponse)
	err := c.cc.Invoke(ctx, SpecSyncService_ReportSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpecSyncServiceServer is the server API for SpecSyncService service.
// All implementations must embed UnimplementedSpecSyncServiceServer
// for forward compatibility.
type SpecSyncServiceServer interface {
	SyncSpec(context.Context, *SyncSpecRequest) (*SyncSpecResponse, error)
	ReportSpec(context.Context, *ReportSpecRequest) (*ReportSpecResponse, error)
	mustEmbedUnimplementedSpecSyncServiceServer()
}

// UnimplementedSpecSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpecSyncServiceServer struct{}

func (UnimplementedSpecSyncServiceServer) SyncSpec(context.Context, *SyncSpecRequest) (*SyncSpecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncSpec not implemented")
}
func (UnimplementedSpecSyncServiceServer) ReportSpec(context.Context, *ReportSpecRequest) (*ReportSpecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSpec not implemented")
}
func (UnimplementedSpecSyncServiceServer) mustEmbedUnimplementedSpecSyncServiceServer() {}
func (UnimplementedSpecSyncServiceServer) testEmbeddedByValue()                         {}

// UnsafeSpecSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpecSyncServiceServer will
// result in compilation errors.
type UnsafeSpecSyncServiceServer interface {
	mustEmbedUnimplementedSpecSyncServiceServer()
}

func RegisterSpecSyncServiceServer(s grpc.ServiceRegistrar, srv SpecSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedSpecSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpecSyncService_ServiceDesc, srv)
}

func _SpecSyncService_SyncSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecSyncServiceServer).SyncSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecSyncService_SyncSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecSyncServiceServer).SyncSpec(ctx, req.(*SyncSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecSyncService_ReportSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecSyncServiceServer).ReportSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecSyncService_ReportSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecSyncServiceServer).ReportSpec(ctx, req.(*ReportSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpecSyncService_ServiceDesc is the grpc.ServiceDesc for SpecSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpecSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurora.sync.v1.SpecSyncService",
	HandlerType: (*SpecSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncSpec",
			Handler:    _SpecSyncService_SyncSpec_Handler,
		},
		{
			MethodName: "ReportSpec",
			Handler:    _SpecSyncService_ReportSpec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync/v1/spec.proto",
}
