// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: sync/v1/spec.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncSpecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CurrentHash   string                 `protobuf:"bytes,2,opt,name=current_hash,json=currentHash,proto3" json:"current_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSpecRequest) Reset() {
	*x = SyncSpecRequest{}
	mi := &file_sync_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSpecRequest) ProtoMessage() {}

func (x *SyncSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSpecRequest.ProtoReflect.Descriptor instead.
func (*SyncSpecRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *SyncSpecRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SyncSpecRequest) GetCurrentHash() string {
	if x != nil {
		return x.CurrentHash
	}
	return ""
}

type SyncSpecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InSync        bool                   `protobuf:"varint,1,opt,name=in_sync,json=inSync,proto3" json:"in_sync,omitempty"`
	ReleaseId     int64                  `protobuf:"varint,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	SpecYaml      string                 `protobuf:"bytes,4,opt,name=spec_yaml,json=specYaml,proto3" json:"spec_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSpecResponse) Reset() {
	*x = SyncSpecResponse{}
	mi := &file_sync_v1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSpecResponse) ProtoMessage() {}

func (x *SyncSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSpecResponse.ProtoReflect.Descriptor instead.
func (*SyncSpecResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *SyncSpecResponse) GetInSync() bool {
	if x != nil {
		return x.InSync
	}
	return false
}

func (x *SyncSpecResponse) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *SyncSpecResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SyncSpecResponse) GetSpecYaml() string {
	if x != nil {
		return x.SpecYaml
	}
	return ""
}

type ReportSpecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ReleaseId     int64                  `protobuf:"varint,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "in_sync", "out_of_sync"
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSpecRequest) Reset() {
	*x = ReportSpecRequest{}
	mi := &file_sync_v1_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSpecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSpecRequest) ProtoMessage() {}

func (x *ReportSpecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSpecRequest.ProtoReflect.Descriptor instead.
func (*ReportSpecRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *ReportSpecRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportSpecRequest) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *ReportSpecRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ReportSpecRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportSpecRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportSpecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSpecResponse) Reset() {
	*x = ReportSpecResponse{}
	mi := &file_sync_v1_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSpecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSpecResponse) ProtoMessage() {}

func (x *ReportSpecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSpecResponse.ProtoReflect.Descriptor instead.
func (*ReportSpecResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_spec_proto_rawDescGZIP(), []int{3}
}

func (x *ReportSpecResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_sync_v1_spec_proto protoreflect.FileDescriptor

const file_sync_v1_spec_proto_rawDesc = "" +
	"\n" +
	"\x12sync/v1/spec.proto\x12\x0eaurora.sync.v1\"M\n" +
	"\x0fSyncSpecRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fcurrent_hash\x18\x02 \x01(\tR\vcurrentHash\"{\n" +
	"\x10SyncSpecResponse\x12\x17\n" +
	"\ain_sync\x18\x01 \x01(\bR\x06inSync\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\x03R\treleaseId\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x1b\n" +
	"\tspec_yaml\x18\x04 \x01(\tR\bspecYaml\"\x91\x01\n" +
	"\x11ReportSpecRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\x03R\treleaseId\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\".\n" +
	"\x12ReportSpecResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb5\x01\n" +
	"\x0fSpecSyncService\x12M\n" +
	"\bSyncSpec\x12\x1f.aurora.sync.v1.SyncSpecRequest\x1a .aurora.sync.v1.SyncSpecResponse\x12S\n" +
	"\n" +
	"ReportSpec\x12!.aurora.sync.v1.ReportSpecRequest\x1a\".aurora.sync.v1.ReportSpecResponseB>Z<aurora-waf.local/control-plane/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_sync_v1_spec_proto_rawDescOnce sync.Once
	file_sync_v1_spec_proto_rawDescData []byte
)

func file_sync_v1_spec_proto_rawDescGZIP() []byte {
	file_sync_v1_spec_proto_rawDescOnce.Do(func() {
		file_sync_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_v1_spec_proto_rawDesc), len(file_sync_v1_spec_proto_rawDesc)))
	})
	return file_sync_v1_spec_proto_rawDescData
}

var file_sync_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sync_v1_spec_proto_goTypes = []any{
	(*SyncSpecRequest)(nil),    // 0: aurora.sync.v1.SyncSpecRequest
	(*SyncSpecResponse)(nil),   // 1: aurora.sync.v1.SyncSpecResponse
	(*ReportSpecRequest)(nil),  // 2: aurora.sync.v1.ReportSpecRequest
	(*ReportSpecResponse)(nil), // 3: aurora.sync.v1.ReportSpecResponse
}
var file_sync_v1_spec_proto_depIdxs = []int32{
	0, // 0: aurora.sync.v1.SpecSyncService.SyncSpec:input_type -> aurora.sync.v1.SyncSpecRequest
	2, // 1: aurora.sync.v1.SpecSyncService.ReportSpec:input_type -> aurora.sync.v1.ReportSpecRequest
	1, // 2: aurora.sync.v1.SpecSyncService.SyncSpec:output_type -> aurora.sync.v1.SyncSpecResponse
	3, // 3: aurora.sync.v1.SpecSyncService.ReportSpec:output_type -> aurora.sync.v1.ReportSpecResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sync_v1_spec_proto_init() }
func file_sync_v1_spec_proto_init() {
	if File_sync_v1_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_v1_spec_proto_rawDesc), len(file_sync_v1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_v1_spec_proto_goTypes,
		DependencyIndexes: file_sync_v1_spec_proto_depIdxs,
		MessageInfos:      file_sync_v1_spec_proto_msgTypes,
	}.Build()
	File_sync_v1_spec_proto = out.File
	file_sync_v1_spec_proto_goTypes = nil
	file_sync_v1_spec_proto_depIdxs = nil
}
