// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: sync/v1/upstreams.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpstreamSyncService_GetUpstreams_FullMethodName    = "/aurora.sync.v1.UpstreamSyncService/GetUpstreams"
	UpstreamSyncService_ReportUpstreams_FullMethodName = "/aurora.sync.v1.UpstreamSyncService/ReportUpstreams"
)

// UpstreamSyncServiceClient is the client API for UpstreamSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpstreamSyncServiceClient interface {
	GetUpstreams(ctx context.Context, in *GetUpstreamsRequest, opts ...grpc.CallOption) (*UpstreamSyncResponse, error)
	ReportUpstreams(ctx context.Context, in *ReportUpstreamsRequest, opts ...grpc.CallOption) (*ReportUpstreamsResponse, error)
}

type upstreamSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpstreamSyncServiceClient(cc grpc.ClientConnInterface) UpstreamSyncServiceClient {
	return &upstreamSyncServiceClient{cc}
}

func (c *upstreamSyncServiceClient) GetUpstreams(ctx context.Context, in *GetUpstreamsRequest, opts ...grpc.CallOption) (*UpstreamSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpstreamSyncResponse)
	err := c.cc.Invoke(ctx, UpstreamSyncService_GetUpstreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *upstreamSyncServiceClient) ReportUpstreams(ctx context.Context, in *ReportUpstreamsRequest, opts ...grpc.CallOption) (*ReportUpstreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportUpstreamsResponse)
	err := c.cc.Invoke(ctx, UpstreamSyncService_ReportUpstreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpstreamSyncServiceServer is the server API for UpstreamSyncService service.
// All implementations must embed UnimplementedUpstreamSyncServiceServer
// for forward compatibility.
type UpstreamSyncServiceServer interface {
	GetUpstreams(context.Context, *GetUpstreamsRequest) (*UpstreamSyncResponse, error)
	ReportUpstreams(context.Context, *ReportUpstreamsRequest) (*ReportUpstreamsResponse, error)
	mustEmbedUnimplementedUpstreamSyncServiceServer()
}

// UnimplementedUpstreamSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpstreamSyncServiceServer struct{}

func (UnimplementedUpstreamSyncServiceServer) GetUpstreams(context.Context, *GetUpstreamsRequest) (*UpstreamSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUpstreams not implemented")
}
func (UnimplementedUpstreamSyncServiceServer) ReportUpstreams(context.Context, *ReportUpstreamsRequest) (*ReportUpstreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUpstreams not implemented")
}
func (UnimplementedUpstreamSyncServiceServer) mustEmbedUnimplementedUpstreamSyncServiceServer() {}
func (UnimplementedUpstreamSyncServiceServer) testEmbeddedByValue()                             {}

// UnsafeUpstreamSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpstreamSyncServiceServer will
// result in compilation errors.
type UnsafeUpstreamSyncServiceServer interface {
	mustEmbedUnimplementedUpstreamSyncServiceServer()
}

func RegisterUpstreamSyncServiceServer(s grpc.ServiceRegistrar, srv UpstreamSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedUpstreamSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpstreamSyncService_ServiceDesc, srv)
}

func _UpstreamSyncService_GetUpstreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpstreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamSyncServiceServer).GetUpstreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpstreamSyncService_GetUpstreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamSyncServiceServer).GetUpstreams(ctx, req.(*GetUpstreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpstreamSyncService_ReportUpstreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportUpstreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpstreamSyncServiceServer).ReportUpstreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpstreamSyncService_ReportUpstreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpstreamSyncServiceServer).ReportUpstreams(ctx, req.(*ReportUpstreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpstreamSyncService_ServiceDesc is the grpc.ServiceDesc for UpstreamSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpstreamSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurora.sync.v1.UpstreamSyncService",
	HandlerType: (*UpstreamSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUpstreams",
			Handler:    _UpstreamSyncService_GetUpstreams_Handler,
		},
		{
			MethodName: "ReportUpstreams",
			Handler:    _UpstreamSyncService_ReportUpstreams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync/v1/upstreams.proto",
}
