// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: sync/v1/upstreams.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUpstreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpstreamsRequest) Reset() {
	*x = GetUpstreamsRequest{}
	mi := &file_sync_v1_upstreams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpstreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpstreamsRequest) ProtoMessage() {}

func (x *GetUpstreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_upstreams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpstreamsRequest.ProtoReflect.Descriptor instead.
func (*GetUpstreamsRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_upstreams_proto_rawDescGZIP(), []int{0}
}

func (x *GetUpstreamsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UpstreamSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReleaseId     int64                  `protobuf:"varint,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	ConfigContent string                 `protobuf:"bytes,3,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamSyncResponse) Reset() {
	*x = UpstreamSyncResponse{}
	mi := &file_sync_v1_upstreams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamSyncResponse) ProtoMessage() {}

func (x *UpstreamSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_upstreams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamSyncResponse.ProtoReflect.Descriptor instead.
func (*UpstreamSyncResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_upstreams_proto_rawDescGZIP(), []int{1}
}

func (x *UpstreamSyncResponse) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *UpstreamSyncResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *UpstreamSyncResponse) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

type ReportUpstreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ReleaseId     int64                  `protobuf:"varint,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUpstreamsRequest) Reset() {
	*x = ReportUpstreamsRequest{}
	mi := &file_sync_v1_upstreams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUpstreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUpstreamsRequest) ProtoMessage() {}

func (x *ReportUpstreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_upstreams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUpstreamsRequest.ProtoReflect.Descriptor instead.
func (*ReportUpstreamsRequest) Descriptor() ([]byte, []int) {
	return file_sync_v1_upstreams_proto_rawDescGZIP(), []int{2}
}

func (x *ReportUpstreamsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportUpstreamsRequest) GetReleaseId() int64 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *ReportUpstreamsRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ReportUpstreamsRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportUpstreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUpstreamsResponse) Reset() {
	*x = ReportUpstreamsResponse{}
	mi := &file_sync_v1_upstreams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUpstreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUpstreamsResponse) ProtoMessage() {}

func (x *ReportUpstreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_v1_upstreams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUpstreamsResponse.ProtoReflect.Descriptor instead.
func (*ReportUpstreamsResponse) Descriptor() ([]byte, []int) {
	return file_sync_v1_upstreams_proto_rawDescGZIP(), []int{3}
}

func (x *ReportUpstreamsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_sync_v1_upstreams_proto protoreflect.FileDescriptor

const file_sync_v1_upstreams_proto_rawDesc = "" +
	"\n" +
	"\x17sync/v1/upstreams.proto\x12\x0eaurora.sync.v1\".\n" +
	"\x13GetUpstreamsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"t\n" +
	"\x14UpstreamSyncResponse\x12\x1d\n" +
	"\n" +
	"release_id\x18\x01 \x01(\x03R\treleaseId\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12%\n" +
	"\x0econfig_content\x18\x03 \x01(\tR\rconfigContent\"\x80\x01\n" +
	"\x16ReportUpstreamsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\x03R\treleaseId\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"3\n" +
	"\x17ReportUpstreamsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd4\x01\n" +
	"\x13UpstreamSyncService\x12Y\n" +
	"\fGetUpstreams\x12#.aurora.sync.v1.GetUpstreamsRequest\x1a$.aurora.sync.v1.UpstreamSyncResponse\x12b\n" +
	"\x0fReportUpstreams\x12&.aurora.sync.v1.ReportUpstreamsRequest\x1a'.aurora.sync.v1.ReportUpstreamsResponseB>Z<aurora-waf.local/control-plane/internal/transport/grpc/pb;pbb\x06proto3"

var (
	file_sync_v1_upstreams_proto_rawDescOnce sync.Once
	file_sync_v1_upstreams_proto_rawDescData []byte
)

func file_sync_v1_upstreams_proto_rawDescGZIP() []byte {
	file_sync_v1_upstreams_proto_rawDescOnce.Do(func() {
		file_sync_v1_upstreams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_v1_upstreams_proto_rawDesc), len(file_sync_v1_upstreams_proto_rawDesc)))
	})
	return file_sync_v1_upstreams_proto_rawDescData
}

var file_sync_v1_upstreams_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sync_v1_upstreams_proto_goTypes = []any{
	(*GetUpstreamsRequest)(nil),     // 0: aurora.sync.v1.GetUpstreamsRequest
	(*UpstreamSyncResponse)(nil),    // 1: aurora.sync.v1.UpstreamSyncResponse
	(*ReportUpstreamsRequest)(nil),  // 2: aurora.sync.v1.ReportUpstreamsRequest
	(*ReportUpstreamsResponse)(nil), // 3: aurora.sync.v1.ReportUpstreamsResponse
}
var file_sync_v1_upstreams_proto_depIdxs = []int32{
	0, // 0: aurora.sync.v1.UpstreamSyncService.GetUpstreams:input_type -> aurora.sync.v1.GetUpstreamsRequest
	2, // 1: aurora.sync.v1.UpstreamSyncService.ReportUpstreams:input_type -> aurora.sync.v1.ReportUpstreamsRequest
	1, // 2: aurora.sync.v1.UpstreamSyncService.GetUpstreams:output_type -> aurora.sync.v1.UpstreamSyncResponse
	3, // 3: aurora.sync.v1.UpstreamSyncService.ReportUpstreams:output_type -> aurora.sync.v1.ReportUpstreamsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sync_v1_upstreams_proto_init() }
func file_sync_v1_upstreams_proto_init() {
	if File_sync_v1_upstreams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_v1_upstreams_proto_rawDesc), len(file_sync_v1_upstreams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_v1_upstreams_proto_goTypes,
		DependencyIndexes: file_sync_v1_upstreams_proto_depIdxs,
		MessageInfos:      file_sync_v1_upstreams_proto_msgTypes,
	}.Build()
	File_sync_v1_upstreams_proto = out.File
	file_sync_v1_upstreams_proto_goTypes = nil
	file_sync_v1_upstreams_proto_depIdxs = nil
}
