//! Extension Materialization Subsystem
//!
//! Translates high-level declarative extension specifications into concrete runtime configuration.
//! Native proxy extensions compile directly into NGINX directive blocks (`active-extensions.conf`
//! and `active-extensions-http.conf`), while engine-level extensions export structured policy files
//! consumed by Aurora's Rust dataplane filters.

#[path = "blue-green/mod.rs"]
pub mod blue_green;
#[path = "canary-release/mod.rs"]
pub mod canary_release;
pub mod common;
#[path = "compression-gzip/mod.rs"]
pub mod compression_gzip;
#[path = "connection-limit/mod.rs"]
pub mod connection_limit;
#[path = "correlation-id/mod.rs"]
pub mod correlation_id;
#[path = "cors/mod.rs"]
pub mod cors;
#[path = "ip-restriction/mod.rs"]
pub mod ip_restriction;
pub mod jwt;
#[path = "maintenance/mod.rs"]
pub mod maintenance;
#[path = "rate-limit/mod.rs"]
pub mod rate_limit;
#[path = "request-header-transform/mod.rs"]
pub mod request_header_transform;
#[path = "request-mirror/mod.rs"]
pub mod request_mirror;
#[path = "request-size-limit/mod.rs"]
pub mod request_size_limit;
#[path = "request-termination/mod.rs"]
pub mod request_termination;
#[path = "response-buffering/mod.rs"]
pub mod response_buffering;
#[path = "response-header-transform/mod.rs"]
pub mod response_header_transform;
#[path = "timeout-policy/mod.rs"]
pub mod timeout_policy;
#[path = "traffic-shaper/mod.rs"]
pub mod traffic_shaper;
#[path = "traffic-split/mod.rs"]
pub mod traffic_split;
#[path = "uri-rewrite/mod.rs"]
pub mod uri_rewrite;

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ExtensionInstanceSpec {
    pub instance_id: String,
    pub key: String,
    pub version: u32,
    #[serde(default)]
    pub renderer: String,
    #[serde(default)]
    pub manifest_digest: String,
    pub config_json: String,
}

pub struct RenderedExtensions {
    pub modules_conf: String,
    pub http_conf: String,
    pub server_conf: String,
    pub ip_restriction_policy: Option<Value>,
    pub jwt_policy: Option<Value>,
    pub rate_limit_policy: Option<Value>,
    pub conn_limit_policy: Option<Value>,
    pub traffic_shaper_policy: Option<Value>,
    pub request_size_limit_policy: Option<Value>,
    pub traffic_split_policy: Option<Value>,
    pub canary_release_policy: Option<Value>,
    pub blue_green_policy: Option<Value>,
    pub request_mirror_policy: Option<Value>,
    pub request_termination_policy: Option<Value>,
}

pub fn render_extensions(
    instances: &[ExtensionInstanceSpec],
) -> Result<RenderedExtensions, String> {
    let modules = String::from(
        "# Generated by Aurora Dataplane Agent for dynamic extension modules\n# No dynamic modules loaded\n",
    );
    let mut http =
        String::from("# Generated by Aurora Dataplane Agent for HTTP-level extension directives\n");
    let mut ingress_server = String::new();
    let mut regular_server = String::new();
    let has_http = false;
    let mut has_server = false;
    let mut ip_restriction_policy = None;
    let mut metrics_instances = 0;
    let mut opentelemetry_metrics_instances = 0;
    let mut opentelemetry_logs_instances = 0;
    let mut opentelemetry_tracing_instances = 0;
    let mut std_log_instances = 0;
    let mut jwt_policy = None;
    let mut rate_limit_policy = None;
    let mut conn_limit_policy = None;
    let mut traffic_shaper_policy = None;
    let mut request_size_limit_policy = None;
    let mut traffic_split_policy = None;
    let mut canary_release_policy = None;
    let mut blue_green_policy = None;
    let mut request_mirror_policy = None;
    let mut request_termination_policy = None;

    for instance in instances {
        if instance.renderer.trim().is_empty() {
            return Err(format!(
                "extension instance {} has empty renderer",
                instance.instance_id
            ));
        }

        let config = serde_json::from_str::<Value>(&instance.config_json)
            .map_err(|error| {
                format!(
                    "decode extension instance {} config: {error}",
                    instance.instance_id
                )
            })?
            .as_object()
            .cloned()
            .ok_or_else(|| {
                format!(
                    "extension instance {} config must be an object",
                    instance.instance_id
                )
            })?;

        match instance.renderer.as_str() {
            "ip-restriction" => ip_restriction::materialize(
                instance,
                &config,
                &mut ip_restriction_policy,
                &mut regular_server,
                &mut has_server,
            )?,
            "agent-metrics" => {
                crate::extension::prometheus::materialize(instance, config, &mut metrics_instances)?
            }
            "opentelemetry-metrics" => crate::extension::opentelemetry_metrics::materialize(
                instance,
                config,
                &mut opentelemetry_metrics_instances,
            )?,
            "opentelemetry-logs" => crate::extension::opentelemetry_logs::materialize(
                instance,
                config,
                &mut opentelemetry_logs_instances,
            )?,
            "opentelemetry-tracing" => crate::extension::opentelemetry_tracing::materialize(
                instance,
                config,
                &mut opentelemetry_tracing_instances,
            )?,
            "std-log" => {
                crate::extension::std_log::materialize(instance, config, &mut std_log_instances)?
            }
            "engine-jwt-rs256" => jwt::materialize(
                instance,
                config,
                &mut jwt_policy,
                &mut regular_server,
                &mut has_server,
            )?,
            "rate-limit" => rate_limit::materialize(
                instance,
                config,
                &mut rate_limit_policy,
                &mut regular_server,
                &mut has_server,
            )?,
            "connection-limit" => connection_limit::materialize(
                instance,
                config,
                &mut conn_limit_policy,
                &mut regular_server,
                &mut has_server,
            )?,
            "traffic-shaper" => traffic_shaper::materialize(
                instance,
                config,
                &mut traffic_shaper_policy,
                &mut regular_server,
                &mut has_server,
            )?,
            "request-size-limit" => request_size_limit::materialize(
                instance,
                config,
                &mut request_size_limit_policy,
                &mut regular_server,
                &mut has_server,
            )?,
            "traffic-split" => traffic_split::materialize(
                instance,
                config,
                &mut traffic_split_policy,
                &mut regular_server,
                &mut has_server,
            )?,
            "canary-release" => canary_release::materialize(
                instance,
                config,
                &mut canary_release_policy,
                &mut regular_server,
                &mut has_server,
            )?,
            "blue-green" => blue_green::materialize(
                instance,
                config,
                &mut blue_green_policy,
                &mut regular_server,
                &mut has_server,
            )?,
            "request-mirror" => request_mirror::materialize(
                instance,
                config,
                &mut request_mirror_policy,
                &mut regular_server,
                &mut has_server,
            )?,
            "request-termination" => request_termination::materialize(
                instance,
                config,
                &mut request_termination_policy,
                &mut regular_server,
                &mut has_server,
            )?,
            "correlation-id" => {
                correlation_id::materialize(&config, &mut regular_server, &mut has_server)?
            }
            "cors" => cors::materialize(&config, &mut regular_server, &mut has_server)?,
            "request-header-transform" => request_header_transform::materialize(
                &config,
                &mut ingress_server,
                &mut has_server,
            )?,
            "response-header-transform" => response_header_transform::materialize(
                &config,
                &mut regular_server,
                &mut has_server,
            )?,
            "compression-gzip" => {
                compression_gzip::materialize(&config, &mut regular_server, &mut has_server)?
            }
            "uri-rewrite" => {
                // Route-scoped extension: configured and evaluated on routes via location plugins
            }
            "response-buffering" => {
                response_buffering::materialize(&mut regular_server, &mut has_server)?
            }
            "timeout-policy" => {
                timeout_policy::materialize(&config, &mut regular_server, &mut has_server)?
            }
            "maintenance" => {
                maintenance::materialize(&config, &mut regular_server, &mut has_server)?
            }
            renderer => {
                return Err(format!(
                    "extension instance {} uses unsupported renderer {renderer}",
                    instance.instance_id
                ));
            }
        }
    }

    let mut server = String::from("# Generated by Aurora Dataplane Agent for active extensions\n");
    if !ingress_server.is_empty() {
        server.push_str(&ingress_server);
    }
    server.push_str(&regular_server);

    if !has_http {
        http.push_str("# No active HTTP-level extension directives\n");
    }
    if !has_server {
        server.push_str("# No active NGINX-level extension directives\n");
    }
    Ok(RenderedExtensions {
        modules_conf: modules,
        http_conf: http,
        server_conf: server,
        ip_restriction_policy,
        jwt_policy,
        rate_limit_policy,
        conn_limit_policy,
        traffic_shaper_policy,
        request_size_limit_policy,
        traffic_split_policy,
        canary_release_policy,
        blue_green_policy,
        request_mirror_policy,
        request_termination_policy,
    })
}
