pub mod access;
pub mod common;
#[path = "connection-limit/mod.rs"]
pub mod connection_limit;
pub mod jwt;
pub mod metrics;
pub mod nginx;
#[path = "rate-limit/mod.rs"]
pub mod rate_limit;
#[path = "traffic-shaper/mod.rs"]
pub mod traffic_shaper;

use crate::spec::extensions::ExtensionInstanceSpec;
use nginx::NginxDirectiveSink;
use serde_json::Value;
use std::collections::HashSet;

pub struct RenderedExtensions {
    pub modules_conf: String,
    pub http_conf: String,
    pub server_conf: String,
    pub access_rules: Vec<Value>,
    pub jwt_policy: Option<Value>,
    pub rate_limit_policy: Option<Value>,
    pub conn_limit_policy: Option<Value>,
    pub traffic_shaper_policy: Option<Value>,
}

pub fn render_extensions(
    instances: &[ExtensionInstanceSpec],
) -> Result<RenderedExtensions, String> {
    let mut modules =
        String::from("# Generated by Aurora Dataplane Agent for dynamic extension modules\n");
    let mut http =
        String::from("# Generated by Aurora Dataplane Agent for HTTP-level extension directives\n");
    let mut server = String::from("# Generated by Aurora Dataplane Agent for active extensions\n");
    let mut has_modules = false;
    let mut has_http = false;
    let mut has_server = false;
    let mut access_rules = Vec::new();
    let mut used_access_rule_ids = HashSet::new();
    let mut metrics_instances = 0;
    let mut jwt_policy = None;
    let mut rate_limit_policy = None;
    let mut conn_limit_policy = None;
    let mut traffic_shaper_policy = None;

    for instance in instances {
        if instance.renderer.trim().is_empty() {
            return Err(format!(
                "extension instance {} has empty renderer",
                instance.instance_id
            ));
        }

        let config = serde_json::from_str::<Value>(&instance.config_json)
            .map_err(|error| {
                format!(
                    "decode extension instance {} config: {error}",
                    instance.instance_id
                )
            })?
            .as_object()
            .cloned()
            .ok_or_else(|| {
                format!(
                    "extension instance {} config must be an object",
                    instance.instance_id
                )
            })?;

        match instance.renderer.as_str() {
            "access-policy" => access::materialize(
                instance,
                &config,
                &mut access_rules,
                &mut used_access_rule_ids,
            )?,
            "agent-metrics" => metrics::materialize(instance, config, &mut metrics_instances)?,
            "engine-jwt-rs256" => jwt::materialize(
                instance,
                config,
                &mut jwt_policy,
                &mut server,
                &mut has_server,
            )?,
            "rate-limit" => rate_limit::materialize(
                instance,
                config,
                &mut rate_limit_policy,
                &mut server,
                &mut has_server,
            )?,
            "connection-limit" => connection_limit::materialize(
                instance,
                config,
                &mut conn_limit_policy,
                &mut server,
                &mut has_server,
            )?,
            "traffic-shaper" | "bandwidth-limit" => traffic_shaper::materialize(
                instance,
                config,
                &mut traffic_shaper_policy,
                &mut server,
                &mut has_server,
            )?,
            renderer if renderer.starts_with("nginx-") => {
                let mut sink = NginxDirectiveSink {
                    modules: &mut modules,
                    has_modules: &mut has_modules,
                    http: &mut http,
                    has_http: &mut has_http,
                    server: &mut server,
                    has_server: &mut has_server,
                };
                nginx::materialize(renderer, instance, &config, &mut sink)?;
            }
            renderer => {
                return Err(format!(
                    "extension instance {} uses unsupported renderer {renderer}",
                    instance.instance_id
                ));
            }
        }
    }

    if !has_modules {
        modules.push_str("# No dynamic modules loaded\n");
    }
    if !has_http {
        http.push_str("# No active HTTP-level extension directives\n");
    }
    if !has_server {
        server.push_str("# No active NGINX-level extension directives\n");
    }
    Ok(RenderedExtensions {
        modules_conf: modules,
        http_conf: http,
        server_conf: server,
        access_rules,
        jwt_policy,
        rate_limit_policy,
        conn_limit_policy,
        traffic_shaper_policy,
    })
}
