use crate::extension::manifest::resolve;
use crate::spec::extensions::{ExtensionInstanceSpec, MetricsExtensionSpec};
use serde::Deserialize;
use serde_json::{Map, Value, json};
use sha2::{Digest, Sha256};
use std::collections::HashSet;
use std::net::IpAddr;

pub struct RenderedExtensions {
    pub modules_conf: String,
    pub http_conf: String,
    pub server_conf: String,
    pub access_rules: Vec<Value>,
    pub jwt_policy: Option<Value>,
    pub rate_limit_policy: Option<Value>,
}

pub fn render_extensions(
    instances: &[ExtensionInstanceSpec],
) -> Result<RenderedExtensions, String> {
    let mut modules =
        String::from("# Generated by Aurora Dataplane Agent for dynamic extension modules\n");
    let mut http =
        String::from("# Generated by Aurora Dataplane Agent for HTTP-level extension directives\n");
    let mut server = String::from("# Generated by Aurora Dataplane Agent for active extensions\n");
    let mut has_modules = false;
    let mut has_http = false;
    let mut has_server = false;
    let mut access_rules = Vec::new();
    let mut used_access_rule_ids = HashSet::new();
    let mut metrics_instances = 0;
    let mut jwt_policy = None;
    let mut rate_limit_policy = None;

    for instance in instances {
        let manifest = resolve(instance)?;
        let config = serde_json::from_str::<Value>(&instance.config_json)
            .map_err(|error| {
                format!(
                    "decode extension instance {} config: {error}",
                    instance.instance_id
                )
            })?
            .as_object()
            .cloned()
            .ok_or_else(|| {
                format!(
                    "extension instance {} config must be an object",
                    instance.instance_id
                )
            })?;

        match manifest.renderer.as_str() {
            "access-policy" => append_access_policy(
                instance,
                &config,
                &mut access_rules,
                &mut used_access_rule_ids,
            )?,
            "agent-metrics" => {
                metrics_instances += 1;
                if metrics_instances > 1 {
                    return Err(
                        "NodeSpec contains more than one agent-metrics extension".to_string()
                    );
                }
                serde_json::from_value::<MetricsExtensionSpec>(Value::Object(config)).map_err(
                    |error| {
                        format!(
                            "decode metrics extension {} config: {error}",
                            instance.instance_id
                        )
                    },
                )?;
            }
            "engine-jwt-rs256" => {
                if jwt_policy.is_some() {
                    return Err(
                        "NodeSpec contains more than one engine-jwt-rs256 extension".to_string()
                    );
                }
                let rules = array(&config, "rules").ok_or_else(|| {
                    format!(
                        "decode JWT extension {} config: rules must be an array",
                        instance.instance_id
                    )
                })?;
                if rules.is_empty() || rules.len() > 8 {
                    return Err(format!(
                        "JWT extension {} must contain 1..=8 rules",
                        instance.instance_id
                    ));
                }
                jwt_policy = Some(Value::Object(config));
                server.push_str("gateway_jwt_policy /var/lib/aurora-policy/active-jwt.json;\n");
                has_server = true;
            }
            "nginx-brotli" => {
                modules.push_str("load_module /opt/aurora-dependencies/brotli/ngx_http_brotli_filter_module.so;\n");
                modules.push_str("load_module /opt/aurora-dependencies/brotli/ngx_http_brotli_static_module.so;\n");
                has_modules = true;
                server.push_str("brotli on;\n");
                if let Some(level) = unsigned(&config, "quality") {
                    server.push_str(&format!("brotli_comp_level {level};\n"));
                }
                server.push_str("brotli_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;\n");
                has_server = true;
            }
            "rate-limit" => {
                if rate_limit_policy.is_some() {
                    return Err(
                        "NodeSpec contains more than one rate-limit extension".to_string(),
                    );
                }
                let rules = array(&config, "rules").ok_or_else(|| {
                    format!(
                        "decode rate-limit extension {} config: rules must be an array",
                        instance.instance_id
                    )
                })?;
                if rules.is_empty() || rules.len() > 64 {
                    return Err(format!(
                        "rate-limit extension {} must contain 1..=64 rules",
                        instance.instance_id
                    ));
                }
                let algorithm = string(&config, "algorithm").ok_or_else(|| {
                    format!(
                        "decode rate-limit extension {} config: missing algorithm",
                        instance.instance_id
                    )
                })?;
                if !matches!(algorithm, "token_bucket" | "leaky_bucket" | "fixed_window" | "sliding_window") {
                    return Err(format!(
                        "rate-limit extension {} has invalid algorithm: {algorithm}",
                        instance.instance_id
                    ));
                }
                let mem_mb = unsigned(&config, "memory_size_mb").ok_or_else(|| {
                    format!(
                        "decode rate-limit extension {} config: missing memory_size_mb",
                        instance.instance_id
                    )
                })?;
                if mem_mb == 0 || mem_mb > 1024 {
                    return Err(format!(
                        "rate-limit extension {} memory_size_mb must be 1..=1024",
                        instance.instance_id
                    ));
                }
                let max_keys = unsigned(&config, "max_keys").ok_or_else(|| {
                    format!(
                        "decode rate-limit extension {} config: missing max_keys",
                        instance.instance_id
                    )
                })?;
                if !(16..=5_000_000).contains(&max_keys) {
                    return Err(format!(
                        "rate-limit extension {} max_keys must be 16..=5000000",
                        instance.instance_id
                    ));
                }
                let eviction = string(&config, "eviction_policy").ok_or_else(|| {
                    format!(
                        "decode rate-limit extension {} config: missing eviction_policy",
                        instance.instance_id
                    )
                })?;
                if !matches!(eviction, "lru" | "lfu" | "fifo") {
                    return Err(format!(
                        "rate-limit extension {} has invalid eviction_policy: {eviction}",
                        instance.instance_id
                    ));
                }
                let overflow = string(&config, "overflow_strategy").ok_or_else(|| {
                    format!(
                        "decode rate-limit extension {} config: missing overflow_strategy",
                        instance.instance_id
                    )
                })?;
                if !matches!(overflow, "evict_and_track" | "drop_new" | "bypass_new") {
                    return Err(format!(
                        "rate-limit extension {} has invalid overflow_strategy: {overflow}",
                        instance.instance_id
                    ));
                }

                let mb_keys = (mem_mb * 1024 * 1024) / 128;
                if max_keys > mb_keys {
                    return Err(format!(
                        "rate-limit extension {} max_keys ({max_keys}) exceeds memory limit {mem_mb}MB ({mb_keys} keys)",
                        instance.instance_id
                    ));
                }

                let mut rule_ids = std::collections::HashSet::with_capacity(rules.len());
                for (idx, r_val) in rules.iter().enumerate() {
                    let r_obj = r_val.as_object().ok_or_else(|| {
                        format!("rate-limit extension {} rule #{idx} must be an object", instance.instance_id)
                    })?;
                    let id = r_obj.get("id").and_then(|v| v.as_str()).ok_or_else(|| {
                        format!("rate-limit extension {} rule #{idx} missing id", instance.instance_id)
                    })?;
                    if id.trim().is_empty() || id.len() > 128 || !rule_ids.insert(id.to_string()) {
                        return Err(format!("rate-limit extension {} invalid or duplicate rule id: {id}", instance.instance_id));
                    }
                    let host = r_obj.get("host").and_then(|v| v.as_str()).ok_or_else(|| {
                        format!("rate-limit extension {} rule {id} missing host", instance.instance_id)
                    })?;
                    if host.is_empty() || host.len() > 253 {
                        return Err(format!("rate-limit extension {} rule {id} invalid host", instance.instance_id));
                    }
                    let path = r_obj.get("path_prefix").and_then(|v| v.as_str()).ok_or_else(|| {
                        format!("rate-limit extension {} rule {id} missing path_prefix", instance.instance_id)
                    })?;
                    if !path.starts_with('/') || path.len() > 8192 || path.bytes().any(|b| b <= 32 || b >= 127) {
                        return Err(format!("rate-limit extension {} rule {id} invalid path_prefix", instance.instance_id));
                    }
                    let limit_by = r_obj.get("limit_by").and_then(|v| v.as_str()).ok_or_else(|| {
                        format!("rate-limit extension {} rule {id} missing limit_by", instance.instance_id)
                    })?;
                    if !matches!(limit_by, "client_ip" | "api_key" | "authorization" | "route_path") {
                        return Err(format!("rate-limit extension {} rule {id} invalid limit_by: {limit_by}", instance.instance_id));
                    }
                    let rate = r_obj.get("rate").and_then(|v| v.as_u64()).ok_or_else(|| {
                        format!("rate-limit extension {} rule {id} missing rate", instance.instance_id)
                    })?;
                    if rate == 0 || rate > 1_000_000 {
                        return Err(format!("rate-limit extension {} rule {id} invalid rate", instance.instance_id));
                    }
                    let period = r_obj.get("period_secs").and_then(|v| v.as_u64()).ok_or_else(|| {
                        format!("rate-limit extension {} rule {id} missing period_secs", instance.instance_id)
                    })?;
                    if period == 0 || period > 86400 {
                        return Err(format!("rate-limit extension {} rule {id} invalid period_secs", instance.instance_id));
                    }
                    let action = r_obj.get("action_on_exceeded").and_then(|v| v.as_str()).ok_or_else(|| {
                        format!("rate-limit extension {} rule {id} missing action_on_exceeded", instance.instance_id)
                    })?;
                    if !matches!(action, "throttle" | "block" | "audit" | "custom_response") {
                        return Err(format!("rate-limit extension {} rule {id} invalid action_on_exceeded: {action}", instance.instance_id));
                    }
                    if matches!(r_obj.get("burst").and_then(|v| v.as_u64()), Some(burst) if burst < rate) {
                        return Err(format!("rate-limit extension {} rule {id} burst cannot be less than rate ({rate})", instance.instance_id));
                    }
                    if matches!(r_obj.get("rejected_code").and_then(|v| v.as_u64()), Some(rejected_code) if !(200..=599).contains(&rejected_code)) {
                        return Err(format!("rate-limit extension {} rule {id} invalid rejected_code", instance.instance_id));
                    }
                }

                rate_limit_policy = Some(Value::Object(config));
                server.push_str("gateway_rate_limit_policy /var/lib/aurora-policy/active-rate-limit.json;\n");
                has_server = true;
            }
            "nginx-rate-limit-local" => {
                http.push_str(&format!(
                    "limit_req_zone $binary_remote_addr zone=aurora_rate_limit_local:10m rate={}r/s;\n",
                    unsigned_or(&config, "refill_rate", 100).max(1)
                ));
                has_http = true;
                server.push_str(&format!(
                    "limit_req_status {};\nlimit_req zone=aurora_rate_limit_local burst={} nodelay;\n",
                    unsigned_or(&config, "rejected_code", 429),
                    unsigned_or(&config, "capacity", 1000)
                ));
                has_server = true;
            }
            "nginx-connection-limit" => {
                http.push_str("limit_conn_zone $binary_remote_addr zone=aurora_conn_limit:10m;\n");
                has_http = true;
                server.push_str(&format!(
                    "limit_conn_status {};\nlimit_conn aurora_conn_limit {};\n",
                    unsigned_or(&config, "rejected_code", 503),
                    unsigned_or(&config, "max_connections_per_ip", 50)
                ));
                has_server = true;
            }
            "nginx-bandwidth-limit" => {
                if let Some(rate) = unsigned(&config, "rate_kb_per_sec") {
                    server.push_str(&format!("limit_rate {rate}k;\n"));
                    has_server = true;
                }
                if let Some(burst) = unsigned(&config, "burst_kb") {
                    server.push_str(&format!("limit_rate_after {burst}k;\n"));
                    has_server = true;
                }
            }
            "nginx-cors" => {
                let allow_credentials = boolean(&config, "allow_credentials").unwrap_or(false);
                let origin = if allow_credentials {
                    "$http_origin".to_string()
                } else {
                    strings(&config, "allow_origins")
                        .and_then(|items| (items.len() == 1).then(|| items[0].clone()))
                        .unwrap_or_else(|| "$http_origin".to_string())
                };
                let methods = strings(&config, "allow_methods")
                    .map(|items| items.join(", "))
                    .unwrap_or_else(|| "GET, POST, PUT, DELETE, PATCH, OPTIONS".to_string());
                let headers = strings(&config, "allow_headers")
                    .map(|items| items.join(", "))
                    .unwrap_or_else(|| "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-API-Key,X-Request-ID".to_string());
                server.push_str(&format!(
                    "add_header Access-Control-Allow-Origin {} always;\n",
                    nginx_quoted(&origin, "allow_origins")?
                ));
                server.push_str(&format!(
                    "add_header Access-Control-Allow-Methods {} always;\n",
                    nginx_quoted(&methods, "allow_methods")?
                ));
                server.push_str(&format!(
                    "add_header Access-Control-Allow-Headers {} always;\n",
                    nginx_quoted(&headers, "allow_headers")?
                ));
                server.push_str(&format!(
                    "add_header Access-Control-Max-Age {} always;\n",
                    unsigned_or(&config, "max_age", 86400)
                ));
                if allow_credentials {
                    server
                        .push_str("add_header Access-Control-Allow-Credentials \"true\" always;\n");
                }
                if let Some(expose_headers) = strings(&config, "expose_headers")
                    && !expose_headers.is_empty()
                {
                    server.push_str(&format!(
                        "add_header Access-Control-Expose-Headers {} always;\n",
                        nginx_quoted(&expose_headers.join(", "), "expose_headers")?
                    ));
                }
                server.push_str("if ($request_method = 'OPTIONS') {\n    return 204;\n}\n");
                has_server = true;
            }
            "nginx-request-header-transform" => {
                append_header_transforms(
                    &mut server,
                    &config,
                    "proxy_set_header",
                    "proxy_set_header",
                )?;
                has_server = true;
            }
            "nginx-response-header-transform" => {
                append_header_transforms(&mut server, &config, "add_header", "proxy_hide_header")?;
                has_server = true;
            }
            "nginx-maintenance" => {
                let message = string_or(
                    &config,
                    "message",
                    "Service undergoing planned maintenance.",
                );
                let body = serde_json::to_string(&json!({ "error": message }))
                    .map_err(|error| format!("encode maintenance response: {error}"))?;
                server.push_str(&format!(
                    "add_header Retry-After {} always;\n",
                    unsigned_or(&config, "retry_after_secs", 300)
                ));
                if let Some(bypass_header) = string(&config, "bypass_header") {
                    let variable = nginx_request_header_variable(bypass_header)?;
                    server.push_str("set $aurora_maintenance 1;\n");
                    server.push_str(&format!(
                        "if ({variable}) {{\n    set $aurora_maintenance 0;\n}}\n"
                    ));
                    server.push_str(&format!(
                        "if ($aurora_maintenance = 1) {{\n    return {} {};\n}}\n",
                        unsigned_or(&config, "status_code", 503),
                        nginx_quoted(&body, "message")?
                    ));
                } else {
                    server.push_str(&format!(
                        "return {} {};\n",
                        unsigned_or(&config, "status_code", 503),
                        nginx_quoted(&body, "message")?
                    ));
                }
                has_server = true;
            }
            "nginx-request-termination" => {
                if let Some(headers) = object(&config, "headers") {
                    for (name, value) in headers {
                        let value = value.as_str().ok_or_else(|| {
                            format!("request termination header {name} must be a string")
                        })?;
                        server.push_str(&format!(
                            "add_header {} {} always;\n",
                            nginx_header_name(name)?,
                            nginx_quoted(value, "headers")?
                        ));
                    }
                }
                server.push_str(&format!(
                    "return {} {};\n",
                    unsigned_or(&config, "status_code", 200),
                    nginx_quoted(
                        &string_or(&config, "body", r#"{"status":"mocked"}"#),
                        "body"
                    )?
                ));
                has_server = true;
            }
            "nginx-uri-rewrite" => {
                if let Some(rules) = array(&config, "rules") {
                    for (index, rule) in rules.iter().enumerate() {
                        let rule = rule
                            .as_object()
                            .ok_or_else(|| format!("uri-rewrite rule {index} must be an object"))?;
                        let pattern = required_string(rule, "pattern", "uri-rewrite rule")?;
                        let replacement = required_string(rule, "replacement", "uri-rewrite rule")?;
                        server.push_str(&format!(
                            "rewrite {} {} break;\n",
                            nginx_fragment(pattern, "rules.pattern")?,
                            nginx_fragment(replacement, "rules.replacement")?
                        ));
                    }
                    has_server = true;
                }
            }
            "nginx-request-size-limit" => {
                server.push_str(&format!(
                    "client_max_body_size {};\n",
                    unsigned_or(&config, "max_body_bytes", 1_048_576)
                ));
                has_server = true;
            }
            "nginx-response-buffering" => {
                server.push_str("proxy_buffering off;\n");
                has_server = true;
            }
            "nginx-gzip" => {
                server.push_str("gzip on;\n");
                if let Some(level) = unsigned(&config, "level") {
                    server.push_str(&format!("gzip_comp_level {level};\n"));
                }
                server.push_str("gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;\n");
                has_server = true;
            }
            "nginx-timeout-policy" => {
                if let Some(timeout) = unsigned(&config, "connect_timeout_ms") {
                    server.push_str(&format!("proxy_connect_timeout {timeout}ms;\n"));
                    has_server = true;
                }
                if let Some(timeout) = unsigned(&config, "read_timeout_ms") {
                    server.push_str(&format!("proxy_read_timeout {timeout}ms;\n"));
                    has_server = true;
                }
                if let Some(timeout) = unsigned(&config, "write_timeout_ms") {
                    server.push_str(&format!("proxy_send_timeout {timeout}ms;\n"));
                    has_server = true;
                }
            }
            renderer => {
                return Err(format!(
                    "extension instance {} uses unsupported renderer {renderer}",
                    instance.instance_id
                ));
            }
        }
    }

    if !has_modules {
        modules.push_str("# No dynamic modules loaded\n");
    }
    if !has_http {
        http.push_str("# No active HTTP-level extension directives\n");
    }
    if !has_server {
        server.push_str("# No active NGINX-level extension directives\n");
    }
    Ok(RenderedExtensions {
        modules_conf: modules,
        http_conf: http,
        server_conf: server,
        access_rules,
        jwt_policy,
        rate_limit_policy,
    })
}

#[derive(Deserialize)]
struct AccessPolicyConfig {
    #[serde(default)]
    whitelist: Vec<String>,
    #[serde(default)]
    blacklist: Vec<String>,
    #[serde(default)]
    rules: Vec<AccessPolicyRule>,
}

#[derive(Deserialize)]
struct AccessPolicyRule {
    id: String,
    cidr: String,
    r#type: String,
    match_value: String,
    action: String,
    #[serde(default)]
    priority: Option<u32>,
    #[serde(default = "default_rule_enabled")]
    enabled: bool,
}

fn default_rule_enabled() -> bool {
    true
}

fn append_access_policy(
    instance: &ExtensionInstanceSpec,
    config: &Map<String, Value>,
    rules: &mut Vec<Value>,
    used_ids: &mut HashSet<u64>,
) -> Result<(), String> {
    let config = serde_json::from_value::<AccessPolicyConfig>(Value::Object(config.clone()))
        .map_err(|error| {
            format!(
                "decode access-policy extension {} config: {error}",
                instance.instance_id
            )
        })?;
    for (index, cidr) in config.whitelist.iter().enumerate() {
        append_access_rule(
            instance,
            AccessRuleInput {
                source: &format!("whitelist:{index}"),
                cidr,
                action: "allow",
                priority: 10,
                path_prefix: "/",
            },
            rules,
            used_ids,
        )?;
    }
    for (index, cidr) in config.blacklist.iter().enumerate() {
        append_access_rule(
            instance,
            AccessRuleInput {
                source: &format!("blacklist:{index}"),
                cidr,
                action: "block",
                priority: 20,
                path_prefix: "/",
            },
            rules,
            used_ids,
        )?;
    }
    for (index, configured) in config.rules.iter().enumerate() {
        if !configured.enabled {
            continue;
        }
        let expected_action = match configured.r#type.as_str() {
            "whitelist" => "allow",
            "blacklist" => "block",
            other => {
                return Err(format!(
                    "access-policy rule {} has unsupported type {other}",
                    configured.id
                ));
            }
        };
        if configured.action != expected_action {
            return Err(format!(
                "access-policy rule {} action must be {expected_action} for {}",
                configured.id, configured.r#type
            ));
        }
        let priority = configured.priority.unwrap_or(100 + index as u32);
        if priority > 1_000_000 {
            return Err(format!(
                "access-policy rule {} priority exceeds 1000000",
                configured.id
            ));
        }
        append_access_rule(
            instance,
            AccessRuleInput {
                source: &format!("rule:{}", configured.id),
                cidr: &configured.cidr,
                action: &configured.action,
                priority,
                path_prefix: if configured.match_value.is_empty() {
                    "/"
                } else {
                    &configured.match_value
                },
            },
            rules,
            used_ids,
        )?;
    }
    if rules.len() > 512 {
        return Err("extension access policies exceed 512 rules".to_string());
    }
    Ok(())
}

struct AccessRuleInput<'a> {
    source: &'a str,
    cidr: &'a str,
    action: &'a str,
    priority: u32,
    path_prefix: &'a str,
}

fn append_access_rule(
    instance: &ExtensionInstanceSpec,
    input: AccessRuleInput<'_>,
    rules: &mut Vec<Value>,
    used_ids: &mut HashSet<u64>,
) -> Result<(), String> {
    let cidr = normalized_cidr(input.cidr)?;
    if !input.path_prefix.starts_with('/') {
        return Err(format!(
            "access-policy rule {} path must begin with /",
            input.source
        ));
    }
    let mut hasher = Sha256::new();
    hasher.update(instance.instance_id.as_bytes());
    hasher.update([0]);
    hasher.update(input.source.as_bytes());
    let digest = hasher.finalize();
    let mut id = u64::from_be_bytes(digest[..8].try_into().expect("SHA-256 prefix"));
    if id == 0 {
        id = 1;
    }
    while !used_ids.insert(id) {
        id = id.wrapping_add(1);
        if id == 0 {
            id = 1;
        }
    }
    rules.push(json!({
        "id": id,
        "priority": input.priority,
        "action": input.action,
        "networks": [cidr],
        "host": "*",
        "path_prefix": input.path_prefix,
        "method": "*",
        "schedule": "always",
        "expires_at": 0,
        "log": false,
        "reputation": false,
        "alert": false,
    }));
    Ok(())
}

fn normalized_cidr(raw: &str) -> Result<String, String> {
    let (address, prefix) = raw
        .trim()
        .split_once('/')
        .ok_or_else(|| format!("CIDR {raw:?} is missing a prefix length"))?;
    let address = address
        .parse::<IpAddr>()
        .map_err(|_| format!("CIDR {raw:?} has an invalid address"))?;
    let prefix = prefix
        .parse::<u8>()
        .map_err(|_| format!("CIDR {raw:?} has an invalid prefix length"))?;
    match address {
        IpAddr::V4(address) => {
            if prefix > 32 {
                return Err(format!("CIDR {raw:?} prefix exceeds 32"));
            }
            let mask = if prefix == 0 {
                0
            } else {
                u32::MAX << (32 - prefix)
            };
            Ok(format!(
                "{}/{}",
                std::net::Ipv4Addr::from(u32::from(address) & mask),
                prefix
            ))
        }
        IpAddr::V6(address) => {
            if prefix > 128 {
                return Err(format!("CIDR {raw:?} prefix exceeds 128"));
            }
            if address.to_ipv4_mapped().is_some() {
                return Err(format!(
                    "CIDR {raw:?} must not use an IPv4-mapped IPv6 address"
                ));
            }
            let mask = if prefix == 0 {
                0
            } else {
                u128::MAX << (128 - prefix)
            };
            Ok(format!(
                "{}/{}",
                std::net::Ipv6Addr::from(u128::from(address) & mask),
                prefix
            ))
        }
    }
}

fn append_header_transforms(
    server: &mut String,
    config: &Map<String, Value>,
    add_directive: &str,
    remove_directive: &str,
) -> Result<(), String> {
    if let Some(headers) = object(config, "add_headers") {
        for (name, value) in headers {
            let value = value
                .as_str()
                .ok_or_else(|| format!("extension header {name} must be a string"))?;
            server.push_str(&format!(
                "{add_directive} {} {}{};\n",
                nginx_header_name(name)?,
                nginx_quoted(value, "add_headers")?,
                if add_directive == "add_header" {
                    " always"
                } else {
                    ""
                }
            ));
        }
    }
    if let Some(headers) = strings(config, "remove_headers") {
        for name in headers {
            server.push_str(&format!(
                "{remove_directive} {}{};\n",
                nginx_header_name(&name)?,
                if remove_directive == "proxy_set_header" {
                    " \"\""
                } else {
                    ""
                }
            ));
        }
    }
    Ok(())
}

fn unsigned(config: &Map<String, Value>, field: &str) -> Option<u64> {
    config.get(field).and_then(Value::as_u64)
}

fn unsigned_or(config: &Map<String, Value>, field: &str, default: u64) -> u64 {
    unsigned(config, field).unwrap_or(default)
}

fn boolean(config: &Map<String, Value>, field: &str) -> Option<bool> {
    config.get(field).and_then(Value::as_bool)
}

fn string<'a>(config: &'a Map<String, Value>, field: &str) -> Option<&'a str> {
    config.get(field).and_then(Value::as_str)
}

fn string_or(config: &Map<String, Value>, field: &str, default: &str) -> String {
    string(config, field).unwrap_or(default).to_string()
}

fn strings(config: &Map<String, Value>, field: &str) -> Option<Vec<String>> {
    config.get(field).and_then(Value::as_array).map(|items| {
        items
            .iter()
            .filter_map(Value::as_str)
            .map(ToString::to_string)
            .collect()
    })
}

fn object<'a>(config: &'a Map<String, Value>, field: &str) -> Option<&'a Map<String, Value>> {
    config.get(field).and_then(Value::as_object)
}

fn array<'a>(config: &'a Map<String, Value>, field: &str) -> Option<&'a Vec<Value>> {
    config.get(field).and_then(Value::as_array)
}

fn required_string<'a>(
    value: &'a Map<String, Value>,
    field: &str,
    owner: &str,
) -> Result<&'a str, String> {
    value
        .get(field)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("{owner} requires string field {field}"))
}

fn nginx_header_name(name: &str) -> Result<&str, String> {
    if name.is_empty()
        || !name
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
    {
        return Err(format!("header name {name:?} is invalid"));
    }
    Ok(name)
}

fn nginx_request_header_variable(header: &str) -> Result<String, String> {
    let header = nginx_header_name(header)?;
    Ok(format!(
        "$http_{}",
        header.to_ascii_lowercase().replace('-', "_")
    ))
}

fn nginx_quoted(value: &str, field: &str) -> Result<String, String> {
    if value.contains(['\r', '\n', '\0']) {
        return Err(format!("{field} contains a prohibited control character"));
    }
    Ok(format!(
        "\"{}\"",
        value.replace('\\', "\\\\").replace('"', "\\\"")
    ))
}

fn nginx_fragment<'a>(value: &'a str, field: &str) -> Result<&'a str, String> {
    if value.contains(['\r', '\n', '\0', ';', '{', '}']) {
        return Err(format!("{field} contains a prohibited NGINX delimiter"));
    }
    Ok(value)
}
