use std::collections::HashMap;

/// Generates load_module directives for dynamic extensions (e.g. Brotli) in modules.conf.
pub fn generate_modules_conf(
    extensions: &HashMap<String, serde_yaml::Value>,
) -> String {
    let mut buf =
        String::from("# Generated by Aurora Dataplane Agent for dynamic extension modules\n");
    let mut has_modules = false;

    for (name, val) in extensions {
        if let serde_yaml::Value::Mapping(map) = val {
            let enabled = map
                .get(serde_yaml::Value::String("enabled".to_string()))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);

            if !enabled {
                continue;
            }

            if name == "compression-brotli" {
                buf.push_str("load_module /opt/aurora-dependencies/brotli/ngx_http_brotli_filter_module.so;\n");
                buf.push_str("load_module /opt/aurora-dependencies/brotli/ngx_http_brotli_static_module.so;\n");
                has_modules = true;
            }
        }
    }

    if !has_modules {
        buf.push_str("# No dynamic modules loaded\n");
    }
    buf
}

/// Generates HTTP-level directives (e.g. limit_req_zone, limit_conn_zone) for active extensions.
pub fn generate_extensions_http_conf(
    extensions: &HashMap<String, serde_yaml::Value>,
) -> String {
    let mut buf =
        String::from("# Generated by Aurora Dataplane Agent for HTTP-level extension directives\n");
    let mut has_directives = false;

    for (name, val) in extensions {
        if let serde_yaml::Value::Mapping(map) = val {
            let enabled = map
                .get(serde_yaml::Value::String("enabled".to_string()))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);

            if !enabled {
                continue;
            }

            match name.as_str() {
                "rate-limit" => {
                    let rate = map
                        .get(serde_yaml::Value::String("rate".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(100);
                    let period_secs = map
                        .get(serde_yaml::Value::String("period_secs".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(1);
                    let rate_str = if period_secs == 60 {
                        format!("{}r/m", rate)
                    } else {
                        format!("{}r/s", rate.max(1))
                    };
                    buf.push_str(&format!(
                        "limit_req_zone $binary_remote_addr zone=aurora_rate_limit:10m rate={};\n",
                        rate_str
                    ));
                    has_directives = true;
                }
                "rate-limit-local" => {
                    let refill_rate = map
                        .get(serde_yaml::Value::String("refill_rate".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(100);
                    buf.push_str(&format!(
                        "limit_req_zone $binary_remote_addr zone=aurora_rate_limit_local:10m rate={}r/s;\n",
                        refill_rate.max(1)
                    ));
                    has_directives = true;
                }
                "connection-limit" => {
                    buf.push_str(
                        "limit_conn_zone $binary_remote_addr zone=aurora_conn_limit:10m;\n",
                    );
                    has_directives = true;
                }
                _ => {}
            }
        }
    }

    if !has_directives {
        buf.push_str("# No active HTTP-level extension directives\n");
    }
    buf
}

/// Generates Server-level directives (e.g. limit_req, CORS headers, maintenance mode) for active extensions.
pub fn generate_extensions_nginx_conf(
    extensions: &HashMap<String, serde_yaml::Value>,
) -> String {
    let mut buf = String::from("# Generated by Aurora Dataplane Agent for active extensions\n");
    let mut has_directives = false;

    for (name, val) in extensions {
        if let serde_yaml::Value::Mapping(map) = val {
            let enabled = map
                .get(serde_yaml::Value::String("enabled".to_string()))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);

            if !enabled {
                continue;
            }

            match name.as_str() {
                "rate-limit" => {
                    let burst = map
                        .get(serde_yaml::Value::String("burst".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(200);
                    let rejected_code = map
                        .get(serde_yaml::Value::String("rejected_code".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(429);
                    buf.push_str(&format!("limit_req_status {};\n", rejected_code));
                    buf.push_str(&format!(
                        "limit_req zone=aurora_rate_limit burst={} nodelay;\n",
                        burst
                    ));
                    has_directives = true;
                }
                "rate-limit-local" => {
                    let capacity = map
                        .get(serde_yaml::Value::String("capacity".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(1000);
                    let rejected_code = map
                        .get(serde_yaml::Value::String("rejected_code".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(429);
                    buf.push_str(&format!("limit_req_status {};\n", rejected_code));
                    buf.push_str(&format!(
                        "limit_req zone=aurora_rate_limit_local burst={} nodelay;\n",
                        capacity
                    ));
                    has_directives = true;
                }
                "connection-limit" => {
                    let max_conn = map
                        .get(serde_yaml::Value::String(
                            "max_connections_per_ip".to_string(),
                        ))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(50);
                    let rejected_code = map
                        .get(serde_yaml::Value::String("rejected_code".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(503);
                    buf.push_str(&format!("limit_conn_status {};\n", rejected_code));
                    buf.push_str(&format!("limit_conn aurora_conn_limit {};\n", max_conn));
                    has_directives = true;
                }
                "bandwidth-limit" => {
                    if let Some(rate) = map
                        .get(serde_yaml::Value::String("rate_kb_per_sec".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("limit_rate {}k;\n", rate));
                        has_directives = true;
                    }
                    if let Some(burst) = map
                        .get(serde_yaml::Value::String("burst_kb".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("limit_rate_after {}k;\n", burst));
                        has_directives = true;
                    }
                }
                "cors" => {
                    let allow_credentials = map
                        .get(serde_yaml::Value::String("allow_credentials".to_string()))
                        .and_then(|v| v.as_bool())
                        .unwrap_or(false);

                    let origin_header = if allow_credentials {
                        "$http_origin"
                    } else if let Some(serde_yaml::Value::Sequence(origins)) =
                        map.get(serde_yaml::Value::String("allow_origins".to_string()))
                    {
                        if origins.len() == 1 {
                            origins[0].as_str().unwrap_or("*")
                        } else {
                            "$http_origin"
                        }
                    } else {
                        "*"
                    };

                    let methods = if let Some(serde_yaml::Value::Sequence(seq)) =
                        map.get(serde_yaml::Value::String("allow_methods".to_string()))
                    {
                        seq.iter()
                            .filter_map(|v| v.as_str())
                            .collect::<Vec<_>>()
                            .join(", ")
                    } else {
                        "GET, POST, PUT, DELETE, PATCH, OPTIONS".to_string()
                    };

                    let headers = if let Some(serde_yaml::Value::Sequence(seq)) =
                        map.get(serde_yaml::Value::String("allow_headers".to_string()))
                    {
                        seq.iter()
                            .filter_map(|v| v.as_str())
                            .collect::<Vec<_>>()
                            .join(", ")
                    } else {
                        "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-API-Key,X-Request-ID".to_string()
                    };

                    let max_age = map
                        .get(serde_yaml::Value::String("max_age".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(86400);

                    buf.push_str(&format!(
                        "add_header 'Access-Control-Allow-Origin' '{}' always;\n",
                        origin_header
                    ));
                    buf.push_str(&format!(
                        "add_header 'Access-Control-Allow-Methods' '{}' always;\n",
                        methods
                    ));
                    buf.push_str(&format!(
                        "add_header 'Access-Control-Allow-Headers' '{}' always;\n",
                        headers
                    ));
                    buf.push_str(&format!(
                        "add_header 'Access-Control-Max-Age' '{}' always;\n",
                        max_age
                    ));

                    if allow_credentials {
                        buf.push_str(
                            "add_header 'Access-Control-Allow-Credentials' 'true' always;\n",
                        );
                    }

                    if let Some(serde_yaml::Value::Sequence(seq)) =
                        map.get(serde_yaml::Value::String("expose_headers".to_string()))
                    {
                        let exp = seq
                            .iter()
                            .filter_map(|v| v.as_str())
                            .collect::<Vec<_>>()
                            .join(", ");
                        if !exp.is_empty() {
                            buf.push_str(&format!(
                                "add_header 'Access-Control-Expose-Headers' '{}' always;\n",
                                exp
                            ));
                        }
                    }

                    // Handle preflight OPTIONS
                    buf.push_str("if ($request_method = 'OPTIONS') {\n    return 204;\n}\n");

                    has_directives = true;
                }
                "request-header-transform" => {
                    if let Some(serde_yaml::Value::Mapping(add_map)) =
                        map.get(serde_yaml::Value::String("add_headers".to_string()))
                    {
                        for (k, v) in add_map {
                            if let (Some(ks), Some(vs)) = (k.as_str(), v.as_str()) {
                                buf.push_str(&format!(
                                    "proxy_set_header {} \"{}\";\n",
                                    ks,
                                    vs.replace('"', "\\\"")
                                ));
                                has_directives = true;
                            }
                        }
                    }
                    if let Some(serde_yaml::Value::Sequence(rem_seq)) =
                        map.get(serde_yaml::Value::String("remove_headers".to_string()))
                    {
                        for k in rem_seq {
                            if let Some(ks) = k.as_str() {
                                buf.push_str(&format!("proxy_set_header {} \"\";\n", ks));
                                has_directives = true;
                            }
                        }
                    }
                }
                "response-header-transform" => {
                    if let Some(serde_yaml::Value::Mapping(add_map)) =
                        map.get(serde_yaml::Value::String("add_headers".to_string()))
                    {
                        for (k, v) in add_map {
                            if let (Some(ks), Some(vs)) = (k.as_str(), v.as_str()) {
                                buf.push_str(&format!(
                                    "add_header {} \"{}\" always;\n",
                                    ks,
                                    vs.replace('"', "\\\"")
                                ));
                                has_directives = true;
                            }
                        }
                    }
                    if let Some(serde_yaml::Value::Sequence(rem_seq)) =
                        map.get(serde_yaml::Value::String("remove_headers".to_string()))
                    {
                        for k in rem_seq {
                            if let Some(ks) = k.as_str() {
                                buf.push_str(&format!("proxy_hide_header {};\n", ks));
                                has_directives = true;
                            }
                        }
                    }
                }
                "maintenance-mode" => {
                    let status_code = map
                        .get(serde_yaml::Value::String("status_code".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(503);
                    let retry_after = map
                        .get(serde_yaml::Value::String("retry_after_secs".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(300);
                    let message = map
                        .get(serde_yaml::Value::String("message".to_string()))
                        .and_then(|v| v.as_str())
                        .unwrap_or("Service undergoing planned maintenance. Please retry in a few moments.");
                    let bypass_header = map
                        .get(serde_yaml::Value::String("bypass_header".to_string()))
                        .and_then(|v| v.as_str());

                    buf.push_str(&format!("add_header Retry-After {} always;\n", retry_after));
                    let escaped_msg = message.replace('\'', "'\\''");
                    let body_json = format!("{{\"error\":\"{}\"}}", escaped_msg);

                    if let Some(bypass) = bypass_header {
                        let var_name = bypass.to_ascii_lowercase().replace('-', "_");
                        buf.push_str("set $aurora_maintenance 1;\n");
                        buf.push_str(&format!(
                            "if ($http_{}) {{\n    set $aurora_maintenance 0;\n}}\n",
                            var_name
                        ));
                        buf.push_str(&format!(
                            "if ($aurora_maintenance = 1) {{\n    return {} '{}';\n}}\n",
                            status_code, body_json
                        ));
                    } else {
                        buf.push_str(&format!("return {} '{}';\n", status_code, body_json));
                    }
                    has_directives = true;
                }
                "request-termination" => {
                    let status_code = map
                        .get(serde_yaml::Value::String("status_code".to_string()))
                        .and_then(|v| v.as_u64())
                        .unwrap_or(200);
                    if let Some(serde_yaml::Value::Mapping(hdrs)) =
                        map.get(serde_yaml::Value::String("headers".to_string()))
                    {
                        for (k, v) in hdrs {
                            if let (Some(ks), Some(vs)) = (k.as_str(), v.as_str()) {
                                buf.push_str(&format!(
                                    "add_header {} \"{}\" always;\n",
                                    ks,
                                    vs.replace('"', "\\\"")
                                ));
                            }
                        }
                    }
                    let body = map
                        .get(serde_yaml::Value::String("body".to_string()))
                        .and_then(|v| v.as_str())
                        .unwrap_or("{\"status\":\"mocked\"}");
                    let escaped_body = body.replace('\'', "'\\''");
                    buf.push_str(&format!("return {} '{}';\n", status_code, escaped_body));
                    has_directives = true;
                }
                "uri-rewrite" => {
                    if let Some(serde_yaml::Value::Sequence(rules)) =
                        map.get(serde_yaml::Value::String("rules".to_string()))
                    {
                        for r in rules {
                            if let serde_yaml::Value::Mapping(rmap) = r {
                                if let (Some(pat), Some(rep)) = (
                                    rmap.get(serde_yaml::Value::String("pattern".to_string()))
                                        .and_then(|v| v.as_str()),
                                    rmap.get(serde_yaml::Value::String("replacement".to_string()))
                                        .and_then(|v| v.as_str()),
                                ) {
                                    buf.push_str(&format!("rewrite {} {} break;\n", pat, rep));
                                    has_directives = true;
                                }
                            }
                        }
                    }
                }
                "request-size-limit" => {
                    if let Some(bytes) = map
                        .get(serde_yaml::Value::String("max_body_bytes".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("client_max_body_size {};\n", bytes));
                        has_directives = true;
                    }
                }
                "response-buffering" => {
                    buf.push_str("proxy_buffering off;\n");
                    has_directives = true;
                }
                "compression-brotli" => {
                    buf.push_str("brotli on;\n");
                    if let Some(level) = map
                        .get(serde_yaml::Value::String("quality".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("brotli_comp_level {};\n", level));
                    }
                    buf.push_str("brotli_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;\n");
                    has_directives = true;
                }
                "compression-gzip" => {
                    buf.push_str("gzip on;\n");
                    if let Some(level) = map
                        .get(serde_yaml::Value::String("level".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("gzip_comp_level {};\n", level));
                    }
                    buf.push_str("gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;\n");
                    has_directives = true;
                }
                "timeout-policy" => {
                    if let Some(ms) = map
                        .get(serde_yaml::Value::String("connect_timeout_ms".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("proxy_connect_timeout {}ms;\n", ms));
                        has_directives = true;
                    }
                    if let Some(ms) = map
                        .get(serde_yaml::Value::String("read_timeout_ms".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("proxy_read_timeout {}ms;\n", ms));
                        has_directives = true;
                    }
                    if let Some(ms) = map
                        .get(serde_yaml::Value::String("write_timeout_ms".to_string()))
                        .and_then(|v| v.as_u64())
                    {
                        buf.push_str(&format!("proxy_send_timeout {}ms;\n", ms));
                        has_directives = true;
                    }
                }
                _ => {}
            }
        }
    }

    if !has_directives {
        buf.push_str("# No active NGINX-level extension directives\n");
    }
    buf
}
