use crate::spec::l4::L4Spec;
use ipnet::IpNet;
use std::fmt::Write;

/// Generates NGINX stream block configuration for L4 stream proxying and CIDR access control.
pub fn generate_l4_streams_conf(l4: &Option<L4Spec>) -> Result<String, String> {
    let l4_spec = match l4 {
        Some(spec) => spec,
        None => {
            return Ok(String::from(
                "# Generated by Aurora Dataplane Agent for L4 Stream Proxying\n# No active L4 stream configuration\n",
            ));
        }
    };

    if l4_spec.upstreams.is_empty() && l4_spec.services.is_empty() {
        return Ok(String::from(
            "# Generated by Aurora Dataplane Agent for L4 Stream Proxying\n# No active L4 stream configuration\n",
        ));
    }

    // Pre-allocate buffer based on estimated size to prevent repeated vector reallocations
    let estimated_capacity = 128 + l4_spec.upstreams.len() * 256 + l4_spec.services.len() * 512;
    let mut buf = String::with_capacity(estimated_capacity);
    buf.push_str("# Generated by Aurora Dataplane Agent for L4 Stream Proxying\n");

    // 1. Upstreams
    for up in &l4_spec.upstreams {
        let _ = write!(
            buf,
            "upstream l4_{} {{\n    zone aurora_l4_{} 64k;\n",
            up.name, up.name
        );
        if up.algorithm == "least_conn" {
            buf.push_str("    least_conn;\n");
        // The control-plane calls its client-affinity algorithm `ip_hash`.
        // NGINX stream has no `ip_hash` directive, so materialize it as a
        // consistent hash of the client address. Keep `hash` for already
        // persisted NodeSpecs from earlier revisions.
        } else if up.algorithm == "ip_hash" || up.algorithm == "hash" {
            buf.push_str("    hash $remote_addr consistent;\n");
        }
        for s in &up.servers {
            let _ = write!(buf, "    server {}", s.addr);
            if s.weight > 1 {
                let _ = write!(buf, " weight={}", s.weight);
            }
            if let Some(mf) = s.max_fails {
                let _ = write!(buf, " max_fails={}", mf);
            }
            if let Some(ref ft) = s.fail_timeout {
                let _ = write!(buf, " fail_timeout={}", ft);
            }
            if s.backup {
                buf.push_str(" backup");
            }
            buf.push_str(" resolve;\n");
        }
        buf.push_str("}\n\n");
    }

    // 2. Services
    for svc in &l4_spec.services {
        if !svc.enabled {
            continue;
        }
        buf.push_str("server {\n");
        let listen_opt = if svc.protocol.eq_ignore_ascii_case("udp") {
            " udp"
        } else {
            ""
        };
        let _ = write!(buf, "    listen {}{};\n", svc.listen_port, listen_opt);

        // Sort references without cloning underlying ACL rule strings
        let mut acl_refs: Vec<&_> = svc.acl.iter().collect();
        acl_refs.sort_unstable_by_key(|rule| std::cmp::Reverse(rule.priority));

        for (i, acl) in acl_refs.iter().enumerate() {
            if acl.priority == 0 || acl.priority > 1_000_000 {
                return Err(format!(
                    "L4 service {:?} has an invalid ACL priority {}",
                    svc.name, acl.priority
                ));
            }
            // In a sorted list, duplicate priorities are adjacent (eliminates HashSet allocation)
            if i > 0 && acl_refs[i - 1].priority == acl.priority {
                return Err(format!(
                    "L4 service {:?} has duplicate ACL priority {}",
                    svc.name, acl.priority
                ));
            }
            let action = if acl.action.eq_ignore_ascii_case("allow") {
                "allow"
            } else if acl.action.eq_ignore_ascii_case("deny") {
                "deny"
            } else {
                return Err(format!(
                    "L4 service {:?} has an invalid ACL action {:?}",
                    svc.name, acl.action
                ));
            };
            acl.cidr.parse::<IpNet>().map_err(|error| {
                format!(
                    "L4 service {:?} has an invalid ACL CIDR {:?}: {error}",
                    svc.name, acl.cidr
                )
            })?;
            let _ = write!(buf, "    {} {};\n", action, acl.cidr);
        }

        let is_endpoint = svc.forward_target_type.as_deref() == Some("endpoint")
            || (svc.upstream.trim().is_empty()
                && svc
                    .endpoint
                    .as_deref()
                    .map(|e| !e.trim().is_empty())
                    .unwrap_or(false));

        let is_l7_http_pipeline = is_endpoint
            && svc.protocol.eq_ignore_ascii_case("tcp")
            && svc
                .endpoint
                .as_deref()
                .map(|endpoint| endpoint.trim() == "127.0.0.1:80")
                .unwrap_or(false);

        let is_l7_tls_pipeline = is_endpoint
            && svc.protocol.eq_ignore_ascii_case("tcp")
            && svc
                .endpoint
                .as_deref()
                .map(|endpoint| endpoint.trim() == "127.0.0.1:9443")
                .unwrap_or(false);

        if is_l7_http_pipeline {
            // The internal HTTP bridge restores the client address from this PROXY header
            // before forwarding to the domain routing servers.
            buf.push_str("    proxy_protocol on;\n");
            buf.push_str("    proxy_pass 127.0.0.1:9082;\n");
        } else if is_l7_tls_pipeline {
            // The TLS bridge terminates HTTPS after reading PROXY protocol, so
            // the L7 access engine receives the original stream client IP.
            buf.push_str("    proxy_protocol on;\n");
            buf.push_str("    proxy_pass 127.0.0.1:9443;\n");
        } else if is_endpoint {
            if let Some(ref ep) = svc.endpoint {
                let _ = write!(buf, "    proxy_pass {};\n", ep.trim());
            }
        } else if !svc.upstream.trim().is_empty() {
            let _ = write!(buf, "    proxy_pass l4_{};\n", svc.upstream.trim());
        }
        if let Some(ref pt) = svc.proxy_timeout
            && !pt.trim().is_empty()
        {
            let _ = write!(buf, "    proxy_timeout {};\n", pt.trim());
        }
        if let Some(ref pct) = svc.proxy_connect_timeout
            && !pct.trim().is_empty()
        {
            let _ = write!(buf, "    proxy_connect_timeout {};\n", pct.trim());
        }
        if svc.protocol.eq_ignore_ascii_case("tcp") {
            buf.push_str("    tcp_nodelay on;\n");
            buf.push_str("    proxy_socket_keepalive on;\n");
        } else if svc.protocol.eq_ignore_ascii_case("udp") {
            buf.push_str("    proxy_responses 1;\n");
        }
        buf.push_str("}\n\n");
    }

    Ok(buf)
}
