use crate::spec::l4::L4Spec;

/// Generates NGINX stream block configuration for L4 stream proxying and CIDR access control.
pub fn generate_l4_streams_conf(l4: &Option<L4Spec>) -> String {
    let mut buf = String::from("# Generated by Aurora Dataplane Agent for L4 Stream Proxying\n");
    let l4_spec = match l4 {
        Some(spec) => spec,
        None => {
            buf.push_str("# No active L4 stream configuration\n");
            return buf;
        }
    };

    if l4_spec.upstreams.is_empty() && l4_spec.services.is_empty() {
        buf.push_str("# No active L4 stream configuration\n");
        return buf;
    }

    // 1. Upstreams
    for up in &l4_spec.upstreams {
        buf.push_str(&format!("upstream l4_{} {{\n", up.name));
        if up.algorithm == "least_conn" {
            buf.push_str("    least_conn;\n");
        } else if up.algorithm == "hash" {
            buf.push_str("    hash $remote_addr consistent;\n");
        }
        for s in &up.servers {
            let mut line = format!("    server {}", s.addr);
            if s.weight > 1 {
                line.push_str(&format!(" weight={}", s.weight));
            }
            if let Some(mf) = s.max_fails {
                line.push_str(&format!(" max_fails={}", mf));
            }
            if let Some(ref ft) = s.fail_timeout {
                line.push_str(&format!(" fail_timeout={}", ft));
            }
            line.push_str(";\n");
            buf.push_str(&line);
        }
        buf.push_str("}\n\n");
    }

    // 2. Services
    for svc in &l4_spec.services {
        if !svc.enabled {
            continue;
        }
        buf.push_str("server {\n");
        let listen_opt = if svc.protocol.to_lowercase() == "udp" { " udp" } else { "" };
        buf.push_str(&format!("    listen {}{};\n", svc.listen_port, listen_opt));

        for acl in &svc.acl {
            let action = acl.action.to_lowercase();
            if action == "allow" || action == "deny" {
                buf.push_str(&format!("    {} {};\n", action, acl.cidr));
            }
        }

        let is_endpoint = svc.forward_target_type.as_deref() == Some("endpoint")
            || (svc.upstream.trim().is_empty()
                && svc
                    .endpoint
                    .as_deref()
                    .map(|e| !e.trim().is_empty())
                    .unwrap_or(false));

        if is_endpoint {
            if let Some(ref ep) = svc.endpoint {
                buf.push_str(&format!("    proxy_pass {};\n", ep.trim()));
            }
        } else if !svc.upstream.trim().is_empty() {
            buf.push_str(&format!("    proxy_pass l4_{};\n", svc.upstream.trim()));
        }
        if let Some(ref pt) = svc.proxy_timeout {
            if !pt.trim().is_empty() {
                buf.push_str(&format!("    proxy_timeout {};\n", pt));
            }
        }
        if let Some(ref pct) = svc.proxy_connect_timeout {
            if !pct.trim().is_empty() {
                buf.push_str(&format!("    proxy_connect_timeout {};\n", pct));
            }
        }
        buf.push_str("}\n\n");
    }

    buf
}
