use super::atomic_write_if_changed;
use super::tls::CertificateSpec;
use crate::spec::schema::Spec;
use serde::{Deserialize, Serialize};
use std::cmp::Reverse;
use std::collections::{BTreeMap, HashMap};
use std::path::Path;
use tracing::info;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RoutingSpec {
    #[serde(default)]
    pub domains: Vec<DomainRoutingSpec>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct DomainRoutingSpec {
    pub host: String,
    #[serde(default)]
    pub locations: Vec<LocationRoutingSpec>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct LocationRoutingSpec {
    pub path: String,
    pub upstream: String,
    #[serde(default)]
    pub strip_path: bool,
    #[serde(default)]
    pub websocket: bool,
    #[serde(default)]
    pub priority: i32,
    #[serde(default)]
    pub plugins_json: Option<String>,
    #[serde(default)]
    pub origin_tls: Option<OriginTLSSpec>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct OriginTLSSpec {
    #[serde(default)]
    pub enabled: bool,
    #[serde(default)]
    pub verify_cert: bool,
    #[serde(default)]
    pub sni_host: String,
    #[serde(default)]
    pub ca_cert: String,
    #[serde(default)]
    pub mtls: bool,
    #[serde(default)]
    pub client_cert: String,
    #[serde(default)]
    pub client_key: String,
}

/// Matches hostname against SNI pattern (supports exact match and wildcard *.example.com).
pub fn matches_sni(pattern: &str, host: &str) -> bool {
    let p = pattern.trim();
    let h = host.trim();
    if p.eq_ignore_ascii_case(h) || p == "*" {
        return true;
    }
    if let Some(suffix) = p.strip_prefix("*.")
        && let Some((sub, base)) = h.split_once('.')
    {
        return !sub.is_empty() && base.eq_ignore_ascii_case(suffix);
    }
    false
}

/// Finds the most appropriate SSL CertificateSpec matching given host based on its SANs.
pub fn find_matching_certificate<'a>(
    certs: &'a [CertificateSpec],
    host: &str,
) -> Option<&'a CertificateSpec> {
    // 1. Exact SAN match
    for cert in certs {
        if cert
            .sans()
            .iter()
            .any(|s| s.trim().eq_ignore_ascii_case(host))
        {
            return Some(cert);
        }
    }
    // 2. Wildcard SAN match
    certs
        .iter()
        .find(|cert| cert.sans().iter().any(|s| matches_sni(s, host)))
}

/// Generates consolidated active-domain-routing.conf with SNI matching, mTLS, and longest prefix location sorting.
pub fn generate_domain_routing_conf(spec: &Spec, routing_dir: &Path) -> String {
    if let Some(ref raw) = spec.routing_conf {
        return raw.clone();
    }
    if spec.routing.domains.is_empty() {
        return "# No configured domains yet\n".to_string();
    }

    let certs_dir = routing_dir.join("certs");
    let mut buf = String::from("# Generated by Aurora Dataplane Agent\n");

    // Group domains by host
    let mut host_map: BTreeMap<String, Vec<LocationRoutingSpec>> = BTreeMap::new();
    for d in &spec.routing.domains {
        let host = d.host.trim().to_ascii_lowercase();
        if host.is_empty() {
            continue;
        }
        host_map
            .entry(host)
            .or_default()
            .extend(d.locations.clone());
    }

    let mut is_first_quic = true;
    for (host, locations) in host_map {
        // Deduplicate identical paths within the same host, preserving highest priority
        let mut path_map: HashMap<String, LocationRoutingSpec> = HashMap::new();
        for loc in locations {
            let p = loc.path.trim().to_string();
            if let Some(existing) = path_map.get_mut(&p) {
                if loc.priority > existing.priority {
                    *existing = loc;
                }
            } else {
                path_map.insert(p, loc);
            }
        }
        let mut deduped: Vec<LocationRoutingSpec> = path_map.into_values().collect();
        // Sort locations by longest prefix path first (length DESC)
        deduped.sort_by_key(|location| Reverse(location.path.len()));

        let matched_cert = find_matching_certificate(&spec.certificates, &host);

        // 1. HTTP Server Block
        buf.push_str(&format!(
            "server {{\n    listen 80;\n    server_name {};\n    include /etc/nginx/gateway-pipeline.conf;\n",
            host
        ));
        render_locations_into(&mut buf, &deduped, routing_dir);
        buf.push_str("}\n\n");

        // 2. HTTPS Server Block (if certificate matches)
        if let Some(cert) = matched_cert {
            let cert_file = certs_dir.join(format!("{}.crt", cert.id));
            let key_file = certs_dir.join(format!("{}.key", cert.id));
            let quic_listen = if is_first_quic {
                is_first_quic = false;
                "    listen 443 quic reuseport;\n"
            } else {
                "    listen 443 quic;\n"
            };
            buf.push_str(&format!(
                "server {{\n    listen 443 ssl;\n{}    server_name {};\n    include /etc/nginx/gateway-pipeline.conf;\n\n    ssl_certificate {};\n    ssl_certificate_key {};\n    ssl_protocols TLSv1.2 TLSv1.3;\n    ssl_ciphers HIGH:!aNULL:!MD5;\n\n    http2 on;\n    http3 on;\n    quic_retry on;\n    add_header Alt-Svc 'h3=\":443\"; ma=86400' always;\n",
                quic_listen,
                host,
                cert_file.display(),
                key_file.display()
            ));

            if cert.mtls_enabled && !cert.client_ca_pem.trim().is_empty() {
                let ca_file = certs_dir.join(format!("{}_ca.crt", cert.id));
                let depth = if cert.verify_depth > 0 {
                    cert.verify_depth
                } else {
                    1
                };
                buf.push_str(&format!(
                    "    ssl_client_certificate {};\n    ssl_verify_client on;\n    ssl_verify_depth {};\n",
                    ca_file.display(),
                    depth
                ));
            }

            render_locations_into(&mut buf, &deduped, routing_dir);
            buf.push_str("}\n\n");
        }
    }

    buf
}

pub fn render_locations_into(
    buf: &mut String,
    locations: &[LocationRoutingSpec],
    routing_dir: &Path,
) {
    for loc in locations {
        buf.push_str(&format!("    location {} {{\n", loc.path));

        if loc.upstream.trim().is_empty() {
            buf.push_str("        return 503 \"No upstream configured\\n\";\n    }\n");
            continue;
        }

        if loc.websocket {
            buf.push_str("        proxy_http_version 1.1;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection \"upgrade\";\n");
        }

        if loc.strip_path && loc.path.trim() != "/" {
            let clean_path = loc.path.trim().trim_end_matches('/');
            buf.push_str(&format!(
                "        rewrite ^{}/?(.*)$ /$1 break;\n",
                clean_path
            ));
        }

        buf.push_str("        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n        proxy_connect_timeout 5s;\n");

        let mut scheme = "http";
        if let Some(tls) = loc.origin_tls.as_ref().filter(|tls| tls.enabled) {
            scheme = "https";
            buf.push_str("        proxy_ssl_protocols TLSv1.2 TLSv1.3;\n");
            if !tls.sni_host.is_empty() {
                buf.push_str("        proxy_ssl_server_name on;\n");
                buf.push_str(&format!("        proxy_ssl_name {};\n", tls.sni_host));
            }
            if tls.verify_cert {
                buf.push_str("        proxy_ssl_verify on;\n");
                if tls.ca_cert.trim().is_empty() {
                    buf.push_str(
                        "        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;\n",
                    );
                } else {
                    buf.push_str(&format!(
                        "        proxy_ssl_trusted_certificate {};\n",
                        routing_dir
                            .join("origin-tls")
                            .join(format!("{}_ca.crt", loc.upstream))
                            .display()
                    ));
                }
            } else {
                buf.push_str("        proxy_ssl_verify off;\n");
            }
            if tls.mtls {
                let origin_tls_dir = routing_dir.join("origin-tls");
                buf.push_str(&format!(
                    "        proxy_ssl_certificate {};\n        proxy_ssl_certificate_key {};\n",
                    origin_tls_dir
                        .join(format!("{}_client.crt", loc.upstream))
                        .display(),
                    origin_tls_dir
                        .join(format!("{}_client.key", loc.upstream))
                        .display()
                ));
            }
        }

        buf.push_str(&format!(
            "        proxy_pass {}://{};\n        proxy_next_upstream error timeout http_502 http_503;\n    }}\n",
            scheme, loc.upstream
        ));
    }
}

/// Materializes domain routing configuration into `routing_dir/active-domain-routing.conf`.
pub async fn materialize_routes(
    spec: &Spec,
    routing_dir: &Path,
) -> Result<bool, Box<dyn std::error::Error + Send + Sync>> {
    let routing_path = routing_dir.join("active-domain-routing.conf");
    let routing_content = generate_domain_routing_conf(spec, routing_dir);
    if atomic_write_if_changed(&routing_path, routing_content.as_bytes()).await? {
        info!("Updated active-domain-routing.conf");
        return Ok(true);
    }
    Ok(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spec::schema::Spec;

    #[test]
    fn test_matches_sni() {
        assert!(matches_sni("api.aurora.local", "api.aurora.local"));
        assert!(matches_sni("API.Aurora.Local", "api.aurora.local"));
        assert!(matches_sni("*.aurora.local", "api.aurora.local"));
        assert!(matches_sni("*.aurora.local", "billing.aurora.local"));
        assert!(!matches_sni("*.aurora.local", "aurora.local"));
        assert!(!matches_sni("*.aurora.local", "foo.bar.aurora.local"));
        assert!(matches_sni("*", "anything.com"));
        assert!(!matches_sni("api.aurora.local", "other.aurora.local"));
    }

    #[test]
    fn test_find_matching_certificate() {
        let certs = vec![
            CertificateSpec {
                id: "wildcard-cert".to_string(),
                name: "Wildcard".to_string(),
                snis: vec!["*.aurora.local".to_string()],
                cert_pem: "CERT1".to_string(),
                key_pem: "KEY1".to_string(),
                mtls_enabled: false,
                client_ca_pem: String::new(),
                verify_depth: 1,
            },
            CertificateSpec {
                id: "exact-cert".to_string(),
                name: "Exact".to_string(),
                snis: vec!["api.aurora.local".to_string()],
                cert_pem: "CERT2".to_string(),
                key_pem: "KEY2".to_string(),
                mtls_enabled: true,
                client_ca_pem: "CA".to_string(),
                verify_depth: 2,
            },
        ];

        let exact = find_matching_certificate(&certs, "api.aurora.local");
        assert!(exact.is_some());
        assert_eq!(exact.unwrap().id, "exact-cert");

        let wildcard = find_matching_certificate(&certs, "billing.aurora.local");
        assert!(wildcard.is_some());
        assert_eq!(wildcard.unwrap().id, "wildcard-cert");

        let none = find_matching_certificate(&certs, "other-domain.com");
        assert!(none.is_none());
    }

    #[test]
    fn test_http3_quic_reuseport_materialization() {
        let certs = vec![
            CertificateSpec {
                id: "cert-1".to_string(),
                name: "Cert 1".to_string(),
                snis: vec!["a.aurora.local".to_string()],
                cert_pem: "C1".to_string(),
                key_pem: "K1".to_string(),
                mtls_enabled: false,
                client_ca_pem: String::new(),
                verify_depth: 1,
            },
            CertificateSpec {
                id: "cert-2".to_string(),
                name: "Cert 2".to_string(),
                snis: vec!["b.aurora.local".to_string()],
                cert_pem: "C2".to_string(),
                key_pem: "K2".to_string(),
                mtls_enabled: false,
                client_ca_pem: String::new(),
                verify_depth: 1,
            },
        ];

        let spec = Spec {
            routing: RoutingSpec {
                domains: vec![
                    DomainRoutingSpec {
                        host: "a.aurora.local".to_string(),
                        locations: vec![LocationRoutingSpec {
                            path: "/".to_string(),
                            upstream: "pool_a".to_string(),
                            strip_path: false,
                            websocket: false,
                            priority: 10,
                            plugins_json: None,
                            origin_tls: None,
                        }],
                    },
                    DomainRoutingSpec {
                        host: "b.aurora.local".to_string(),
                        locations: vec![LocationRoutingSpec {
                            path: "/".to_string(),
                            upstream: "pool_b".to_string(),
                            strip_path: false,
                            websocket: false,
                            priority: 10,
                            plugins_json: None,
                            origin_tls: None,
                        }],
                    },
                ],
            },
            certificates: certs,
            ..Default::default()
        };

        let conf = generate_domain_routing_conf(&spec, Path::new("/var/lib/aurora-routing"));

        // Verify that reuseport is only present ONCE across the entire configuration
        let reuseport_count = conf.matches("listen 443 quic reuseport;").count();
        assert_eq!(
            reuseport_count, 1,
            "reuseport must appear exactly once to avoid NGINX duplicate listen options error"
        );

        // Verify that the second HTTPS server block has listen 443 quic; without reuseport
        let quic_non_reuseport_count = conf.matches("listen 443 quic;\n").count();
        assert_eq!(
            quic_non_reuseport_count, 1,
            "second server block must use standard 'listen 443 quic;' without reuseport"
        );

        // Verify HTTP/3 and Alt-Svc directives are present in both
        assert_eq!(conf.matches("http3 on;").count(), 2);
        assert_eq!(conf.matches("quic_retry on;").count(), 2);
        assert_eq!(
            conf.matches("add_header Alt-Svc 'h3=\":443\"; ma=86400' always;")
                .count(),
            2
        );
        assert!(
            conf.contains("include /etc/nginx/gateway-pipeline.conf;"),
            "server blocks must include gateway-pipeline.conf"
        );
    }
}
