use crate::spec::certificate::CertificateSpec;
use crate::spec::routing::LocationRoutingSpec;
use crate::spec::schema::Spec;
use std::cmp::Reverse;
use std::collections::{BTreeMap, HashMap};
use std::path::Path;

/// Matches hostname against SNI pattern (supports exact match and wildcard *.example.com).
pub fn matches_sni(pattern: &str, host: &str) -> bool {
    let p = pattern.trim().to_ascii_lowercase();
    let h = host.trim().to_ascii_lowercase();
    if p == h || p == "*" {
        return true;
    }
    if let Some(suffix) = p.strip_prefix("*.")
        && let Some((sub, base)) = h.split_once('.')
    {
        return !sub.is_empty() && base == suffix;
    }
    false
}

/// Finds the most appropriate SSL CertificateSpec matching given host.
pub fn find_matching_certificate<'a>(
    certs: &'a [CertificateSpec],
    host: &str,
) -> Option<&'a CertificateSpec> {
    // 1. Exact SNI match
    for cert in certs {
        if cert
            .snis
            .iter()
            .any(|s| s.trim().eq_ignore_ascii_case(host))
        {
            return Some(cert);
        }
    }
    // 2. Wildcard SNI match
    certs
        .iter()
        .find(|cert| cert.snis.iter().any(|s| matches_sni(s, host)))
}

/// Generates consolidated active-domain-routing.conf with SNI matching, mTLS, and longest prefix location sorting.
pub fn generate_domain_routing_conf(spec: &Spec, routing_dir: &Path) -> String {
    if let Some(ref raw) = spec.routing_conf {
        return raw.clone();
    }
    if spec.routing.domains.is_empty() {
        return "# No configured domains yet\n".to_string();
    }

    let certs_dir = routing_dir.join("certs");
    let mut buf = String::from("# Generated by Aurora Dataplane Agent\n");

    // Group domains by host
    let mut host_map: BTreeMap<String, Vec<LocationRoutingSpec>> = BTreeMap::new();
    for d in &spec.routing.domains {
        let host = d.host.trim().to_ascii_lowercase();
        if host.is_empty() {
            continue;
        }
        host_map
            .entry(host)
            .or_default()
            .extend(d.locations.clone());
    }

    for (host, locations) in host_map {
        // Deduplicate identical paths within the same host, preserving highest priority
        let mut path_map: HashMap<String, LocationRoutingSpec> = HashMap::new();
        for loc in locations {
            let p = loc.path.trim().to_string();
            if let Some(existing) = path_map.get_mut(&p) {
                if loc.priority > existing.priority {
                    *existing = loc;
                }
            } else {
                path_map.insert(p, loc);
            }
        }
        let mut deduped: Vec<LocationRoutingSpec> = path_map.into_values().collect();
        // Sort locations by longest prefix path first (length DESC)
        deduped.sort_by_key(|location| Reverse(location.path.len()));

        let matched_cert = find_matching_certificate(&spec.certificates, &host);

        // 1. HTTP Server Block
        buf.push_str(&format!(
            "server {{\n    listen 80;\n    server_name {};\n    include /etc/nginx/domain-waf.conf;\n",
            host
        ));
        render_locations_into(&mut buf, &deduped, routing_dir);
        buf.push_str("}\n\n");

        // 2. HTTPS Server Block (if certificate matches)
        if let Some(cert) = matched_cert {
            let cert_file = certs_dir.join(format!("{}.crt", cert.id));
            let key_file = certs_dir.join(format!("{}.key", cert.id));
            buf.push_str(&format!(
                "server {{\n    listen 443 ssl;\n    listen 127.0.0.1:9443 ssl proxy_protocol;\n    server_name {};\n    include /etc/nginx/domain-waf.conf;\n\n    ssl_certificate {};\n    ssl_certificate_key {};\n    ssl_protocols TLSv1.2 TLSv1.3;\n    ssl_ciphers HIGH:!aNULL:!MD5;\n",
                host,
                cert_file.display(),
                key_file.display()
            ));

            if cert.mtls_enabled && !cert.client_ca_pem.trim().is_empty() {
                let ca_file = certs_dir.join(format!("{}_ca.crt", cert.id));
                let depth = if cert.verify_depth > 0 {
                    cert.verify_depth
                } else {
                    1
                };
                buf.push_str(&format!(
                    "    ssl_client_certificate {};\n    ssl_verify_client on;\n    ssl_verify_depth {};\n",
                    ca_file.display(),
                    depth
                ));
            }

            render_locations_into(&mut buf, &deduped, routing_dir);
            buf.push_str("}\n\n");
        }
    }

    buf
}

pub fn render_locations_into(
    buf: &mut String,
    locations: &[LocationRoutingSpec],
    routing_dir: &Path,
) {
    for loc in locations {
        buf.push_str(&format!("    location {} {{\n", loc.path));

        if loc.upstream.trim().is_empty() {
            buf.push_str("        return 503 \"No upstream configured\\n\";\n    }\n");
            continue;
        }

        if loc.websocket {
            buf.push_str("        proxy_http_version 1.1;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection \"upgrade\";\n");
        }

        if loc.strip_path && loc.path.trim() != "/" {
            let clean_path = loc.path.trim().trim_end_matches('/');
            buf.push_str(&format!(
                "        rewrite ^{}/?(.*)$ /$1 break;\n",
                clean_path
            ));
        }

        if let Some(ref plugins_str) = loc.plugins_json
            && let Ok(val) = serde_json::from_str::<serde_json::Value>(plugins_str)
            && let Some(rules) = val
                .get("uri-rewrite")
                .and_then(|uri_rewrite| uri_rewrite.get("rules"))
                .and_then(|rules| rules.as_array())
        {
            for rule in rules {
                if let Some(rewrite_path) = rule.get("rewrite_path").and_then(|path| path.as_str())
                {
                    if let Some(match_header) = rule
                        .get("match_header")
                        .and_then(|header| header.as_object())
                    {
                        for (header_name, header_value) in match_header {
                            let value = header_value.as_str().unwrap_or("");
                            let variable = format!(
                                "$http_{}",
                                header_name.to_ascii_lowercase().replace('-', "_")
                            );
                            buf.push_str(&format!(
                                "        if ({variable} = \"{value}\") {{\n            rewrite ^ {rewrite_path} break;\n        }}\n"
                            ));
                        }
                    } else {
                        buf.push_str(&format!("        rewrite ^ {rewrite_path} break;\n"));
                    }
                }
            }
        }

        buf.push_str("        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n        proxy_connect_timeout 5s;\n");

        let mut scheme = "http";
        if let Some(tls) = loc.origin_tls.as_ref().filter(|tls| tls.enabled) {
            scheme = "https";
            buf.push_str("        proxy_ssl_protocols TLSv1.2 TLSv1.3;\n");
            if !tls.sni_host.is_empty() {
                buf.push_str("        proxy_ssl_server_name on;\n");
                buf.push_str(&format!("        proxy_ssl_name {};\n", tls.sni_host));
            }
            if tls.verify_cert {
                buf.push_str("        proxy_ssl_verify on;\n");
                if tls.ca_cert.trim().is_empty() {
                    buf.push_str(
                        "        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;\n",
                    );
                } else {
                    buf.push_str(&format!(
                        "        proxy_ssl_trusted_certificate {};\n",
                        routing_dir
                            .join("origin-tls")
                            .join(format!("{}_ca.crt", loc.upstream))
                            .display()
                    ));
                }
            } else {
                buf.push_str("        proxy_ssl_verify off;\n");
            }
            if tls.mtls {
                let origin_tls_dir = routing_dir.join("origin-tls");
                buf.push_str(&format!(
                    "        proxy_ssl_certificate {};\n        proxy_ssl_certificate_key {};\n",
                    origin_tls_dir
                        .join(format!("{}_client.crt", loc.upstream))
                        .display(),
                    origin_tls_dir
                        .join(format!("{}_client.key", loc.upstream))
                        .display()
                ));
            }
        }

        buf.push_str(&format!(
            "        proxy_pass {}://{};\n        proxy_next_upstream error timeout http_502 http_503;\n    }}\n",
            scheme, loc.upstream
        ));
    }
}
