use super::atomic_write_if_changed;
use crate::spec::schema::Spec;
use serde::{Deserialize, Serialize};
use std::path::Path;
use tracing::info;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct UpstreamSpec {
    pub name: String,
    #[serde(default)]
    pub servers: Vec<UpstreamServerSpec>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct UpstreamServerSpec {
    pub addr: String,
    #[serde(default = "default_weight")]
    pub weight: u32,
}

fn default_weight() -> u32 {
    1
}

/// Generates NGINX `upstream` configuration blocks from `spec.upstreams` or raw override.
pub fn generate_upstreams_conf(upstreams: &[UpstreamSpec], raw_override: Option<&str>) -> String {
    if let Some(raw) = raw_override {
        return raw.to_string();
    }
    if upstreams.is_empty() {
        return "# No active upstreams configured\n".to_string();
    }

    let mut buf = String::from("# Generated by Aurora Dataplane Agent\n");
    for up in upstreams {
        buf.push_str(&format!("upstream {} {{\n", up.name));
        buf.push_str(&format!("    zone aurora_http_{} 64k;\n", up.name));
        for s in &up.servers {
            buf.push_str(&format!(
                "    server {} weight={} resolve;\n",
                s.addr, s.weight
            ));
        }
        buf.push_str("}\n");
    }
    buf
}

/// Materializes upstream configuration into `policy_dir/active-upstreams.conf`.
pub async fn materialize_upstreams(
    spec: &Spec,
    policy_dir: &Path,
) -> Result<bool, Box<dyn std::error::Error + Send + Sync>> {
    let upstreams_path = policy_dir.join("active-upstreams.conf");
    let content = generate_upstreams_conf(&spec.upstreams, spec.upstreams_conf.as_deref());
    if atomic_write_if_changed(&upstreams_path, content.as_bytes()).await? {
        info!("Updated active-upstreams.conf");
        return Ok(true);
    }
    Ok(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_upstreams_conf_empty() {
        let conf = generate_upstreams_conf(&[], None);
        assert_eq!(conf, "# No active upstreams configured\n");
    }

    #[test]
    fn test_generate_upstreams_conf_raw_override() {
        let conf = generate_upstreams_conf(&[], Some("upstream custom { server 127.0.0.1:8080; }"));
        assert_eq!(conf, "upstream custom { server 127.0.0.1:8080; }");
    }

    #[test]
    fn test_generate_upstreams_conf_multiple_servers() {
        let upstreams = vec![UpstreamSpec {
            name: "backend_api".to_string(),
            servers: vec![
                UpstreamServerSpec {
                    addr: "10.0.0.1:8080".to_string(),
                    weight: 3,
                },
                UpstreamServerSpec {
                    addr: "10.0.0.2:8080".to_string(),
                    weight: 1,
                },
            ],
        }];
        let conf = generate_upstreams_conf(&upstreams, None);
        assert!(conf.contains("upstream backend_api {"));
        assert!(conf.contains("zone aurora_http_backend_api 64k;"));
        assert!(conf.contains("server 10.0.0.1:8080 weight=3 resolve;"));
        assert!(conf.contains("server 10.0.0.2:8080 weight=1 resolve;"));
    }
}
